// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { API_SCOPES } from "../../domain/constants"
import { createModule, idParams } from "../../lib/http"
import { atLeast } from "../../middleware/auth"
import { orgService } from "./service"

export const organizationModule = createModule("Organization", "")
const { route } = organizationModule

const everyone = atLeast("viewer")
const admins = atLeast("admin")
const role = z.enum(["admin", "member", "viewer"])

// ---------- Organization ----------
route({
  method: "get",
  path: "/org",
  summary: "Get the current organization (with seat usage)",
  handler: async ({ orgId }) => ({ ...(await orgService.get(orgId)), seatsUsed: await orgService.seatsUsed(orgId) }),
})

route({
  method: "patch",
  path: "/org",
  summary: "Update organization details",
  roles: admins,
  body: z.object({
    name: z.string().trim().min(1).max(120).optional(),
    domain: z.string().trim().regex(/^[a-z0-9.-]+\.[a-z]{2,}$/i, "Enter a valid domain").optional(),
    timezone: z.string().min(1).optional(),
  }),
  handler: ({ orgId, body }) => orgService.update(orgId, body),
})

route({
  method: "post",
  path: "/org/plan",
  summary: "Change subscription plan",
  roles: ["owner"],
  status: 200,
  body: z.object({ plan: z.enum(["starter", "growth", "enterprise"]) }),
  handler: ({ orgId, body }) => orgService.changePlan(orgId, body.plan),
})

// ---------- Profile & preferences ----------
route({
  method: "patch",
  path: "/me",
  summary: "Update your profile",
  roles: everyone,
  body: z.object({
    name: z.string().trim().min(1).max(120).optional(),
    title: z.string().trim().max(120).optional(),
    email: z.string().trim().email().optional(),
  }),
  handler: ({ orgId, auth, body }) => orgService.updateProfile(orgId, auth.userId, body),
})

route({
  method: "get",
  path: "/me/preferences",
  summary: "Get notification preferences",
  handler: ({ orgId, auth }) => orgService.getPreferences(orgId, auth.userId),
})

route({
  method: "put",
  path: "/me/preferences",
  summary: "Replace notification preferences",
  roles: everyone,
  body: z.object({ notifications: z.record(z.string(), z.boolean()), channels: z.record(z.string(), z.boolean()) }),
  handler: ({ orgId, auth, body }) =>
    orgService.setPreferences(orgId, auth.userId, body as Parameters<typeof orgService.setPreferences>[2]),
})

// ---------- Team ----------
route({
  method: "get",
  path: "/users",
  summary: "List team members",
  handler: ({ orgId }) => orgService.listUsers(orgId),
})

route({
  method: "post",
  path: "/users/invite",
  summary: "Invite a team member",
  roles: admins,
  body: z.object({ email: z.string().trim().email(), role, title: z.string().max(120).optional() }),
  handler: ({ orgId, body }) => orgService.invite(orgId, body.email, body.role, body.title),
})

route({
  method: "post",
  path: "/users/:id/resend-invite",
  summary: "Re-issue an invitation",
  roles: admins,
  status: 200,
  params: idParams,
  handler: ({ orgId, params }) => orgService.resendInvite(orgId, params.id),
})

route({
  method: "patch",
  path: "/users/:id",
  summary: "Update a member's role or title",
  roles: admins,
  params: idParams,
  body: z.object({ role: role.optional(), title: z.string().max(120).optional(), name: z.string().min(1).max(120).optional() }),
  handler: ({ orgId, auth, params, body }) => orgService.updateUser(orgId, auth, params.id, body),
})

route({
  method: "delete",
  path: "/users/:id",
  summary: "Remove a member (their records are reassigned)",
  roles: admins,
  params: idParams,
  handler: async ({ orgId, auth, params }) => {
    await orgService.removeUser(orgId, auth.userId, params.id)
  },
})

// ---------- API keys ----------
route({
  method: "get",
  path: "/api-keys",
  summary: "List API keys",
  roles: admins,
  handler: ({ orgId }) => orgService.listApiKeys(orgId),
})

route({
  method: "post",
  path: "/api-keys",
  summary: "Create an API key (the secret is returned once)",
  roles: admins,
  body: z.object({
    name: z.string().trim().min(1).max(80),
    scopes: z.array(z.enum(API_SCOPES as [string, ...string[]])).min(1),
  }),
  handler: ({ orgId, auth, body }) => orgService.createApiKey(orgId, auth.userId, body.name, body.scopes),
})

route({
  method: "post",
  path: "/api-keys/:id/revoke",
  summary: "Revoke an API key",
  roles: admins,
  status: 200,
  params: idParams,
  handler: ({ orgId, params }) => orgService.revokeApiKey(orgId, params.id),
})
