// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import bcrypt from "bcryptjs"
import { db } from "../../db/index"
import { INTEGRATION_CATALOG } from "../../domain/constants"
import type { ApiKey, Organization, Role, Stored, User, UserRecord } from "../../domain/types"
import { randomSecret, sha256 } from "../../lib/crypto"
import { badRequest, conflict, forbidden, notFound, unauthorized } from "../../lib/errors"
import { newId, nowIso } from "../../lib/ids"
import { signToken } from "../../middleware/auth"
import { scoringService } from "../scoring/service"

export const PLAN_SEATS: Record<Organization["plan"], number> = { starter: 3, growth: 10, enterprise: 50 }

const AVATAR_COLORS = ["bg-indigo-500", "bg-emerald-500", "bg-amber-500", "bg-rose-500", "bg-sky-500", "bg-violet-500"]

export const DEFAULT_PREFERENCES = {
  notifications: { highIntentSignal: true, draftsAwaitingApproval: true, positiveReplies: true, dealStageChanges: false, integrationErrors: true },
  channels: { inApp: true, email: true, slack: false },
}

/** Strips server-only fields. */
export function toPublicUser(u: Stored<UserRecord>): User {
  const { id, name, email, role, avatarColor, title, status, lastActiveAt } = u
  return { id, name, email, role, avatarColor, title, status, lastActiveAt }
}

export function toPublicApiKey(k: Stored<ApiKey> & { hash?: string }): ApiKey {
  const { id, name, prefix, scopes, createdAt, lastUsedAt, createdBy, revoked } = k
  return { id, name, prefix, scopes, createdAt, lastUsedAt, createdBy, revoked }
}

const hashPassword = (pw: string) => bcrypt.hash(pw, 10)

/**
 * Creates an organization with its owner, default ICP and integration catalog.
 * Used by /auth/register and the bootstrap script.
 */
export async function createOrganization(input: {
  orgName: string
  domain: string
  ownerName: string
  ownerEmail: string
  password: string
  plan?: Organization["plan"]
}) {
  const email = input.ownerEmail.trim().toLowerCase()
  if (await db.users.findGlobal({ email })) throw conflict("An account with this email already exists")
  const orgId = newId("org")
  const now = nowIso()
  const plan = input.plan ?? "growth"
  const org = await db.organizations.create(orgId, {
    id: orgId,
    name: input.orgName,
    domain: input.domain.toLowerCase(),
    plan,
    seats: PLAN_SEATS[plan],
    timezone: "America/New_York",
    settings: { autopilot: true, waterfallOrder: ["clearbit", "apollo", "fullenrich", "prospeo", "limadata"] },
    createdAt: now,
    updatedAt: now,
  })
  const owner = await db.users.create(orgId, {
    name: input.ownerName,
    email,
    role: "owner",
    title: "Owner",
    status: "active",
    avatarColor: AVATAR_COLORS[0],
    passwordHash: await hashPassword(input.password),
    lastActiveAt: now,
  })
  await scoringService.getIcp(orgId)
  await db.integrations.createMany(
    orgId,
    INTEGRATION_CATALOG.map((c) => ({
      ...c,
      connected: false,
      status: "disconnected" as const,
      settings: {
        autoSync: true,
        syncInterval: "hourly",
        writeBack: c.category === "crm",
        ...(c.category === "enrichment" || c.category === "contacts" ? { useInWaterfall: true } : {}),
        ...(c.category === "llm" ? { model: "claude-opus-5", tokenBudget: "5000" } : {}),
      },
    })),
  )
  return { org, owner }
}

export const authService = {
  async register(input: { orgName: string; domain: string; name: string; email: string; password: string }) {
    const { org, owner } = await createOrganization({
      orgName: input.orgName,
      domain: input.domain,
      ownerName: input.name,
      ownerEmail: input.email,
      password: input.password,
    })
    return { token: signToken(owner), user: toPublicUser(owner), org }
  },

  async login(email: string, password: string) {
    const user = await db.users.findGlobal({ email: email.trim().toLowerCase() })
    if (!user?.passwordHash || !(await bcrypt.compare(password, user.passwordHash))) {
      throw unauthorized("Invalid email or password")
    }
    if (user.status !== "active") throw unauthorized("Your invitation has not been accepted yet")
    const updated = await db.users.update(user.orgId, user.id, { lastActiveAt: nowIso() })
    const org = await db.organizations.get(user.orgId, user.orgId)
    return { token: signToken(updated), user: toPublicUser(updated), org }
  },

  async acceptInvite(token: string, password: string, name?: string) {
    const user = await db.users.findGlobal({ inviteToken: token, status: "invited" })
    if (!user) throw badRequest("Invitation is invalid or already used")
    const updated = await db.users.update(user.orgId, user.id, {
      passwordHash: await hashPassword(password),
      status: "active",
      inviteToken: undefined,
      name: name ?? user.name,
      lastActiveAt: nowIso(),
    })
    const org = await db.organizations.get(user.orgId, user.orgId)
    return { token: signToken(updated), user: toPublicUser(updated), org }
  },

  async me(orgId: string, userId: string) {
    const [user, org] = await Promise.all([db.users.get(orgId, userId), db.organizations.get(orgId, orgId)])
    if (!user || !org) throw unauthorized()
    return { user: toPublicUser(user), org }
  },

  async changePassword(orgId: string, userId: string, current: string, next: string) {
    const user = await db.users.get(orgId, userId)
    if (!user?.passwordHash || !(await bcrypt.compare(current, user.passwordHash))) {
      throw badRequest("Current password is incorrect")
    }
    await db.users.update(orgId, userId, { passwordHash: await hashPassword(next) })
  },
}

export const orgService = {
  async get(orgId: string) {
    const org = await db.organizations.get(orgId, orgId)
    if (!org) throw notFound("Organization")
    return org
  },

  async update(orgId: string, patch: Partial<Pick<Organization, "name" | "domain" | "timezone">>) {
    return db.organizations.update(orgId, orgId, patch)
  },

  async seatsUsed(orgId: string) {
    return db.users.count(orgId)
  },

  async changePlan(orgId: string, plan: Organization["plan"]) {
    const used = await this.seatsUsed(orgId)
    if (PLAN_SEATS[plan] < used) throw badRequest(`The ${plan} plan has ${PLAN_SEATS[plan]} seats but ${used} are in use`)
    return db.organizations.update(orgId, orgId, { plan, seats: PLAN_SEATS[plan] })
  },

  // ---------- Team ----------
  async listUsers(orgId: string) {
    const users = await db.users.find(orgId, undefined, { field: "createdAt", dir: "asc" })
    return users.map(toPublicUser)
  },

  async invite(orgId: string, email: string, role: Role, title?: string) {
    if (role === "owner") throw badRequest("Cannot invite another owner")
    const normalized = email.trim().toLowerCase()
    if (await db.users.findGlobal({ email: normalized })) throw conflict("This email is already a member of a workspace")
    const org = await this.get(orgId)
    if ((await this.seatsUsed(orgId)) >= org.seats) throw badRequest("All seats are in use — upgrade your plan to invite more members")
    const count = await db.users.count(orgId)
    const inviteToken = randomSecret("inv_", 24)
    const user = await db.users.create(orgId, {
      email: normalized,
      name: normalized.split("@")[0].replace(/[._-]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
      role,
      title,
      status: "invited",
      avatarColor: AVATAR_COLORS[count % AVATAR_COLORS.length],
      inviteToken,
    })
    // Email delivery goes through the email provider in production; the token is returned for local testing.
    return { user: toPublicUser(user), inviteToken }
  },

  async resendInvite(orgId: string, id: string) {
    const user = await db.users.get(orgId, id)
    if (!user) throw notFound("User")
    if (user.status !== "invited") throw badRequest("User has already joined")
    const inviteToken = randomSecret("inv_", 24)
    await db.users.update(orgId, id, { inviteToken })
    return { user: toPublicUser(user), inviteToken }
  },

  async updateUser(orgId: string, actor: { userId: string; role: Role }, id: string, patch: Partial<Pick<User, "role" | "title" | "name">>) {
    const target = await db.users.get(orgId, id)
    if (!target) throw notFound("User")
    if (patch.role) {
      if (patch.role === "owner") throw badRequest("Ownership transfer is not supported")
      if (target.role === "owner") throw forbidden("The owner's role cannot be changed")
      if (id === actor.userId) throw forbidden("You cannot change your own role")
    }
    return toPublicUser(await db.users.update(orgId, id, patch))
  },

  async removeUser(orgId: string, actorId: string, id: string) {
    const target = await db.users.get(orgId, id)
    if (!target) throw notFound("User")
    if (target.role === "owner") throw forbidden("The owner cannot be removed")
    if (id === actorId) throw forbidden("You cannot remove yourself")
    await db.users.remove(orgId, id)
    await db.userPreferences.removeMany(orgId, { userId: id })
    await db.accounts.updateMany(orgId, { ownerId: id }, { ownerId: null })
    await db.contacts.updateMany(orgId, { ownerId: id }, { ownerId: null })
    const fallback = actorId
    await db.deals.updateMany(orgId, { ownerId: id }, { ownerId: fallback })
    await db.sequences.updateMany(orgId, { ownerId: id }, { ownerId: fallback })
  },

  async updateProfile(orgId: string, userId: string, patch: Partial<Pick<User, "name" | "title" | "email">>) {
    if (patch.email) {
      patch.email = patch.email.trim().toLowerCase()
      const other = await db.users.findGlobal({ email: patch.email })
      if (other && other.id !== userId) throw conflict("Email is already in use")
    }
    return toPublicUser(await db.users.update(orgId, userId, patch))
  },

  // ---------- Preferences ----------
  async getPreferences(orgId: string, userId: string) {
    const p = await db.userPreferences.findOne(orgId, { userId })
    return p ? { notifications: p.notifications, channels: p.channels } : DEFAULT_PREFERENCES
  },

  async setPreferences(orgId: string, userId: string, prefs: typeof DEFAULT_PREFERENCES) {
    if (!Object.values(prefs.channels).some(Boolean)) throw badRequest("Enable at least one notification channel")
    const existing = await db.userPreferences.findOne(orgId, { userId })
    const saved = existing
      ? await db.userPreferences.update(orgId, existing.id, prefs)
      : await db.userPreferences.create(orgId, { userId, ...prefs })
    return { notifications: saved.notifications, channels: saved.channels }
  },

  // ---------- API keys ----------
  async listApiKeys(orgId: string) {
    const keys = await db.apiKeys.find(orgId, undefined, { field: "createdAt", dir: "desc" })
    return keys.map(toPublicApiKey)
  },

  async createApiKey(orgId: string, userId: string, name: string, scopes: string[]) {
    const secret = randomSecret("se_live_", 32)
    const key = await db.apiKeys.create(orgId, {
      name,
      scopes,
      prefix: secret.slice(0, 12),
      hash: sha256(secret),
      createdBy: userId,
      revoked: false,
    })
    return { apiKey: toPublicApiKey(key), secret }
  },

  async revokeApiKey(orgId: string, id: string) {
    const key = await db.apiKeys.get(orgId, id)
    if (!key) throw notFound("API key")
    return toPublicApiKey(await db.apiKeys.update(orgId, id, { revoked: true }))
  },
}
