// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { config } from "../../config"
import {
  ACTION_LABELS,
  API_SCOPES,
  COUNTRIES,
  DEAL_STAGES,
  FUNDING_STAGES,
  INDUSTRIES,
  INTEGRATION_CATALOG,
  SIGNAL_LABELS,
  SIGNAL_SOURCES,
  STAGE_LABELS,
  STEP_CHANNEL_LABELS,
  TECHNOLOGIES,
} from "../../domain/constants"
import { createModule } from "../../lib/http"
import { PLAN_SEATS } from "../organization/service"

export const metaModule = createModule("Meta", "/meta")
const { route } = metaModule

route({
  method: "get",
  path: "/",
  summary: "Business constants and feature flags used by clients",
  handler: () => ({
    industries: INDUSTRIES,
    countries: COUNTRIES,
    technologies: TECHNOLOGIES,
    fundingStages: FUNDING_STAGES,
    signalLabels: SIGNAL_LABELS,
    signalSources: SIGNAL_SOURCES,
    stageLabels: STAGE_LABELS,
    dealStages: DEAL_STAGES,
    actionLabels: ACTION_LABELS,
    stepChannelLabels: STEP_CHANNEL_LABELS,
    apiScopes: API_SCOPES,
    integrationCategories: [...new Set(INTEGRATION_CATALOG.map((i) => i.category))],
    planSeats: PLAN_SEATS,
    features: { simulation: config.enableSimulation, adminReset: config.enableAdminReset },
  }),
})
