// Single entry point for the frontend data layer: `import { useAccounts } from "@/lib/api"`.
export { api, ApiError, API_URL, downloadText, errorMessage } from "./client"
export { useAuthStore } from "./auth-store"
export { useApiMutation, useApiQuery } from "./query"
export * from "./hooks/auth"
export * from "./hooks/meta"
export * from "./hooks/accounts"
export * from "./hooks/contacts"
export * from "./hooks/signals"
export * from "./hooks/agent"
export * from "./hooks/outreach"
export * from "./hooks/pipeline"
export * from "./hooks/activity"
export * from "./hooks/analytics"
export * from "./hooks/integrations"
