// AUTO-GENERATED by scripts/sync-mock-core.mjs (browser override) — do not edit. Run `npm run mock:sync`.
// Browser replacement for backend/src/db/json/json-repository.ts:
// the same in-memory repository, persisted to localStorage instead of files.
import type { ID, Stored } from "../../domain/types"
import { MemoryRepository } from "../memory/memory-repository"

export { matches, sortRecords } from "../memory/memory-repository"

export const MOCK_DB_PREFIX = "selleasy-mock-db:"

let persistenceSuspended = false
/** Stops all further writes (used right before wiping storage and reloading). */
export function suspendPersistence() {
  persistenceSuspended = true
}

const storage = () => {
  try {
    return typeof window === "undefined" ? null : window.localStorage
  } catch {
    return null
  }
}

export class JsonRepository<T extends { id: ID }> extends MemoryRepository<T> {
  private timer: ReturnType<typeof setTimeout> | null = null
  private pending: Stored<T>[] | null = null

  constructor(name: string, _dataDir: string, idPrefix: string) {
    super(name, idPrefix)
  }

  private get key() {
    return `${MOCK_DB_PREFIX}${this.name}`
  }

  protected async loadRows(): Promise<Stored<T>[]> {
    const raw = storage()?.getItem(this.key)
    if (!raw) return []
    try {
      const rows = JSON.parse(raw)
      return Array.isArray(rows) ? (rows as Stored<T>[]) : []
    } catch {
      return []
    }
  }

  // Debounced: bulk operations (seeding, re-scoring) trigger many writes in a row.
  protected async persistRows(rows: Stored<T>[]) {
    this.pending = rows
    if (this.timer) return
    this.timer = setTimeout(() => {
      this.timer = null
      const data = this.pending
      this.pending = null
      if (!data || persistenceSuspended) return
      try {
        storage()?.setItem(this.key, JSON.stringify(data))
      } catch (err) {
        console.warn(`[mock-api] could not persist ${this.name} (storage full?)`, err)
      }
    }, 250)
  }
}
