// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { config } from "../../config"
import { createModule, fileResponse } from "../../lib/http"
import { importService } from "./service"

export const importModule = createModule("Import", "/import")
const { route } = importModule

const importBody = z.object({
  format: z.enum(["csv", "json"]),
  content: z
    .string()
    .min(1, "content is required")
    .refine((s) => new TextEncoder().encode(s).length <= config.IMPORT_MAX_BYTES, `content must be at most ${config.IMPORT_MAX_BYTES} bytes`),
  dryRun: z.boolean().default(false),
  updateExisting: z.boolean().default(false),
})

route({
  method: "post",
  path: "/accounts",
  summary: "Bulk import accounts from CSV or JSON",
  description:
    "Columns (case-insensitive, common aliases accepted): name, domain (required), industry, employees, revenue, country, city, fundingStage, description, linkedinUrl, technologies, tags, ownerEmail. Dedups by normalized domain. dryRun validates without writing. Error rows are spreadsheet line numbers (CSV) or 1-based array indexes (JSON).",
  status: 200,
  body: importBody,
  handler: ({ orgId, auth, body }) => importService.importAccounts(orgId, auth.userId, body),
})

route({
  method: "post",
  path: "/contacts",
  summary: "Bulk import contacts from CSV or JSON",
  description:
    "Columns: firstName, lastName (or name), email, title, seniority, department, phone, linkedinUrl, location, and an account via accountId, accountDomain or accountName. Unknown domains create the account. Dedups by email.",
  status: 200,
  body: importBody,
  handler: ({ orgId, auth, body }) => importService.importContacts(orgId, auth.userId, body),
})

route({
  method: "get",
  path: "/templates/:type",
  summary: "Download a CSV import template",
  produces: "text/csv",
  params: z.object({ type: z.enum(["accounts", "contacts"]) }),
  handler: ({ params }) => fileResponse(`${params.type}-import-template.csv`, importService.template(params.type)),
})
