// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { parse } from "csv-parse/browser/esm/sync"
import { db } from "../../db/index"
import type { Account, Contact, Seniority, Stored } from "../../domain/types"
import { badRequest, HttpError } from "../../lib/errors"
import { accountService, normalizeDomain } from "../accounts/service"
import { contactService } from "../contacts/service"
import { scoringService } from "../scoring/service"

export type ImportFormat = "csv" | "json"
export type ImportType = "accounts" | "contacts"

export interface ImportOptions {
  format: ImportFormat
  content: string
  dryRun?: boolean
  updateExisting?: boolean
}

export interface ImportResult {
  total: number
  created: number
  updated: number
  skipped: number
  errors: { row: number; message: string }[]
  dryRun: boolean
}

type Row = Record<string, string>
interface SourceRow {
  /** Spreadsheet line (CSV) or 1-based array index (JSON). */
  line: number
  data: Row
}

class RowError extends Error {}

// ---------- Parsing ----------
const keyOf = (h: string) => h.trim().toLowerCase().replace(/[^a-z0-9]/g, "")

/** Normalized header → canonical field. Canonical names map to themselves via keyOf. */
const ACCOUNT_ALIASES: Record<string, string> = {
  company: "name",
  companyname: "name",
  accountname: "name",
  organization: "name",
  organisation: "name",
  website: "domain",
  url: "domain",
  websiteurl: "domain",
  companydomain: "domain",
  companywebsite: "domain",
  employeecount: "employees",
  headcount: "employees",
  numberofemployees: "employees",
  companysize: "employees",
  size: "employees",
  annualrevenue: "revenue",
  tech: "technologies",
  techstack: "technologies",
  technology: "technologies",
  funding: "fundingstage",
  linkedin: "linkedinurl",
  companylinkedinurl: "linkedinurl",
  owner: "owneremail",
  tag: "tags",
  location: "city",
}

const CONTACT_ALIASES: Record<string, string> = {
  first: "firstname",
  givenname: "firstname",
  last: "lastname",
  surname: "lastname",
  familyname: "lastname",
  name: "fullname",
  contactname: "fullname",
  emailaddress: "email",
  workemail: "email",
  jobtitle: "title",
  position: "title",
  level: "seniority",
  phonenumber: "phone",
  mobile: "phone",
  linkedin: "linkedinurl",
  linkedinprofile: "linkedinurl",
  city: "location",
  account: "accountid",
  domain: "accountdomain",
  companydomain: "accountdomain",
  website: "accountdomain",
  companywebsite: "accountdomain",
  company: "accountname",
  companyname: "accountname",
  organization: "accountname",
}

function parseRows(opts: ImportOptions, aliases: Record<string, string>): SourceRow[] {
  const canon = (h: string) => {
    const k = keyOf(h)
    return aliases[k] ?? k
  }
  const toRow = (obj: Record<string, unknown>) => {
    const row: Row = {}
    for (const [k, v] of Object.entries(obj)) {
      if (v === null || v === undefined) continue
      const val = Array.isArray(v) ? v.join(", ") : String(v).trim()
      const key = canon(k)
      if (!(key in row) || (row[key] === "" && val !== "")) row[key] = val
    }
    return row
  }

  if (opts.format === "json") {
    let data: unknown
    try {
      data = JSON.parse(opts.content)
    } catch (e) {
      throw badRequest(`Invalid JSON: ${(e as Error).message}`)
    }
    if (!Array.isArray(data)) throw badRequest("JSON content must be an array of objects")
    return data.map((item, i) => {
      if (!item || typeof item !== "object" || Array.isArray(item)) return { line: i + 1, data: { __invalid: "1" } }
      return { line: i + 1, data: toRow(item as Record<string, unknown>) }
    })
  }

  let records: { record: string[]; info: { lines: number } }[]
  try {
    records = parse(opts.content, {
      bom: true,
      skip_empty_lines: true,
      relax_column_count: true,
      relax_quotes: true,
      trim: true,
      info: true,
    }) as unknown as { record: string[]; info: { lines: number } }[]
  } catch (e) {
    throw badRequest(`Invalid CSV: ${(e as Error).message}`)
  }
  const [header, ...body] = records
  if (!header) throw badRequest("CSV is empty")
  const cols = header.record.map(canon)
  return body
    .filter((r) => r.record.some((v) => v !== ""))
    .map((r) => {
      const obj: Record<string, string> = {}
      cols.forEach((c, i) => {
        const v = r.record[i] ?? ""
        if (!(c in obj) || (obj[c] === "" && v !== "")) obj[c] = v
      })
      return { line: r.info.lines, data: toRow(obj) }
    })
}

// ---------- Field helpers ----------
const str = (r: Row, k: string) => (r[k] ?? "").trim()
const list = (v: string) =>
  v
    .split(/[;,|]/)
    .map((s) => s.trim())
    .filter(Boolean)

/** "1,200" · "$5M" · "12.5k" · "2 billion" → number. Empty → undefined. */
export function parseNumber(raw: string, field: string): number | undefined {
  const s = raw.trim().toLowerCase().replace(/[$€£,\s]/g, "")
  if (!s) return undefined
  const m = s.match(/^(\d+(?:\.\d+)?)(?:-\d+(?:\.\d+)?)?(k|m|mm|b|bn|thousand|million|billion)?\+?$/)
  if (!m) throw new RowError(`${field} must be a number (got "${raw}")`)
  const mult = { k: 1e3, thousand: 1e3, m: 1e6, mm: 1e6, million: 1e6, b: 1e9, bn: 1e9, billion: 1e9 }[m[2] ?? ""] ?? 1
  return Math.round(Number(m[1]) * mult)
}

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

const SENIORITY_MAP: Record<string, Seniority> = {
  clevel: "C-Level",
  csuite: "C-Level",
  cxo: "C-Level",
  executive: "C-Level",
  founder: "C-Level",
  owner: "C-Level",
  vp: "VP",
  vicepresident: "VP",
  svp: "VP",
  evp: "VP",
  head: "VP",
  director: "Director",
  manager: "Manager",
  lead: "Manager",
  ic: "IC",
  individualcontributor: "IC",
  entry: "IC",
  senior: "IC",
  staff: "IC",
}

export function inferSeniority(title: string): Seniority {
  const t = title.toLowerCase()
  if (/\b(chief|ceo|cto|cfo|coo|cmo|cro|cio|ciso|cpo|founder|co-founder|president|owner)\b/.test(t) && !/vice president/.test(t)) return "C-Level"
  if (/\b(vp|svp|evp|vice president|head of)\b/.test(t)) return "VP"
  if (/\bdirector\b/.test(t)) return "Director"
  if (/\b(manager|lead|supervisor)\b/.test(t)) return "Manager"
  return "IC"
}

function normalizeSeniority(raw: string, title: string): Seniority {
  if (!raw) return inferSeniority(title)
  const hit = SENIORITY_MAP[keyOf(raw)]
  if (hit) return hit
  throw new RowError(`Unknown seniority "${raw}" (use C-Level, VP, Director, Manager or IC)`)
}

function errorMessage(e: unknown) {
  if (e instanceof RowError || e instanceof HttpError) return e.message
  throw e
}

/** Only keep keys whose value is defined and not an empty string/array. */
function compact<T extends object>(obj: T): Partial<T> {
  return Object.fromEntries(
    Object.entries(obj).filter(([, v]) => v !== undefined && v !== "" && !(Array.isArray(v) && v.length === 0)),
  ) as Partial<T>
}

// ---------- Accounts ----------
async function userLookup(orgId: string) {
  const users = await db.users.find(orgId)
  const byEmail = new Map(users.map((u) => [u.email.toLowerCase(), u.id]))
  return (email: string) => {
    if (!email) return undefined
    const id = byEmail.get(email.toLowerCase())
    if (!id) throw new RowError(`No team member with email ${email}`)
    return id
  }
}

function accountFromRow(r: Row, ownerFor: (email: string) => string | undefined) {
  if (r.__invalid) throw new RowError("Row must be an object")
  const domainRaw = str(r, "domain")
  const domain = domainRaw ? normalizeDomain(domainRaw) : ""
  if (!domain) throw new RowError("domain is required")
  if (!/^[a-z0-9.-]+\.[a-z]{2,}$/.test(domain)) throw new RowError(`Invalid domain "${domainRaw}"`)
  const name = str(r, "name") || domain
  return {
    name,
    domain,
    fields: compact<Partial<Account>>({
      industry: str(r, "industry"),
      employees: parseNumber(str(r, "employees"), "employees"),
      revenue: parseNumber(str(r, "revenue"), "revenue"),
      country: str(r, "country"),
      city: str(r, "city"),
      fundingStage: str(r, "fundingstage"),
      description: str(r, "description"),
      linkedinUrl: str(r, "linkedinurl"),
      technologies: list(str(r, "technologies")),
      tags: list(str(r, "tags")),
      ownerId: ownerFor(str(r, "owneremail")),
    }),
    hasName: !!str(r, "name"),
  }
}

function sourceLabel(format: ImportFormat) {
  return format === "csv" ? "CSV import" : "JSON import"
}

export const importService = {
  async importAccounts(orgId: string, actorId: string, opts: ImportOptions): Promise<ImportResult> {
    const rows = parseRows(opts, ACCOUNT_ALIASES)
    const dryRun = !!opts.dryRun
    const source = sourceLabel(opts.format)
    const result: ImportResult = { total: rows.length, created: 0, updated: 0, skipped: 0, errors: [], dryRun }
    const ownerFor = await userLookup(orgId)
    const existing = await domainIndex(orgId)
    const seen = new Set<string>()

    for (const { line, data } of rows) {
      try {
        const parsed = accountFromRow(data, ownerFor)
        if (seen.has(parsed.domain)) {
          result.skipped++
          continue
        }
        seen.add(parsed.domain)
        const cur = existing.get(parsed.domain)
        if (cur) {
          if (!opts.updateExisting) {
            result.skipped++
            continue
          }
          const patch: Partial<Account> = { ...parsed.fields, ...(parsed.hasName ? { name: parsed.name } : {}) }
          if (!dryRun) await accountService.update(orgId, cur.id, patch, source)
          result.updated++
          continue
        }
        if (!dryRun) {
          const { account } = await accountService.create(orgId, actorId, { name: parsed.name, domain: parsed.domain, ...parsed.fields }, source)
          existing.set(account.domain, account)
        }
        result.created++
      } catch (e) {
        result.errors.push({ row: line, message: errorMessage(e) })
      }
    }

    if (!dryRun && result.created > 0) await scoringService.rescoreAll(orgId, "Import")
    return result
  },

  async importContacts(orgId: string, actorId: string, opts: ImportOptions): Promise<ImportResult & { accountsCreated: number }> {
    const rows = parseRows(opts, CONTACT_ALIASES)
    const dryRun = !!opts.dryRun
    const source = sourceLabel(opts.format)
    const result = { total: rows.length, created: 0, updated: 0, skipped: 0, errors: [] as ImportResult["errors"], dryRun, accountsCreated: 0 }

    const accounts = await db.accounts.find(orgId)
    const byId = new Map(accounts.map((a) => [a.id, a]))
    const byDomain = await domainIndex(orgId, accounts)
    const byName = new Map<string, string>()
    for (const a of accounts) if (!a.duplicateOf || !byName.has(a.name.toLowerCase())) byName.set(a.name.toLowerCase(), a.id)
    /** Domains of accounts that a dry run would create. */
    const pendingDomains = new Set<string>()

    const existingContacts = new Map((await db.contacts.find(orgId)).filter((c) => c.email).map((c) => [c.email.toLowerCase(), c]))
    const seenEmails = new Set<string>()

    const resolveAccount = async (r: Row): Promise<string> => {
      const accountId = str(r, "accountid")
      if (accountId) {
        if (!byId.has(accountId)) throw new RowError(`Account ${accountId} not found`)
        return accountId
      }
      const domainRaw = str(r, "accountdomain")
      const companyName = str(r, "accountname")
      if (domainRaw) {
        const domain = normalizeDomain(domainRaw)
        if (!/^[a-z0-9.-]+\.[a-z]{2,}$/.test(domain)) throw new RowError(`Invalid account domain "${domainRaw}"`)
        const hit = byDomain.get(domain)
        if (hit) return hit.id
        if (pendingDomains.has(domain)) return `pending:${domain}`
        result.accountsCreated++
        if (dryRun) {
          pendingDomains.add(domain)
          return `pending:${domain}`
        }
        const { account } = await accountService.create(orgId, actorId, { name: companyName || domain, domain }, source)
        byDomain.set(account.domain, account)
        byId.set(account.id, account)
        return account.id
      }
      if (companyName) {
        const id = byName.get(companyName.toLowerCase())
        if (!id) throw new RowError(`Account "${companyName}" not found — add an account domain column to create it`)
        return id
      }
      throw new RowError("An account is required (accountId, accountDomain or accountName)")
    }

    for (const { line, data: r } of rows) {
      try {
        if (r.__invalid) throw new RowError("Row must be an object")
        let firstName = str(r, "firstname")
        let lastName = str(r, "lastname")
        const full = str(r, "fullname")
        if (!firstName && full) {
          const [f, ...rest] = full.split(/\s+/)
          firstName = f ?? ""
          lastName = lastName || rest.join(" ")
        }
        if (!firstName) throw new RowError("firstName (or name) is required")
        const email = str(r, "email").toLowerCase()
        if (email && !EMAIL_RE.test(email)) throw new RowError(`Invalid email "${email}"`)
        const title = str(r, "title")
        const seniorityRaw = str(r, "seniority")
        const fields = compact<Partial<Contact>>({
          title,
          department: str(r, "department"),
          phone: str(r, "phone"),
          linkedinUrl: str(r, "linkedinurl"),
          location: str(r, "location"),
        })

        if (email && seenEmails.has(email)) {
          result.skipped++
          continue
        }
        if (email) seenEmails.add(email)
        const cur = email ? existingContacts.get(email) : undefined
        if (cur) {
          if (!opts.updateExisting) {
            result.skipped++
            continue
          }
          const hasAccount = ["accountid", "accountdomain", "accountname"].some((k) => str(r, k))
          const accountId = hasAccount ? await resolveAccount(r) : undefined
          const patch: Partial<Contact> = {
            ...fields,
            firstName,
            ...(lastName ? { lastName } : {}),
            ...(seniorityRaw || title ? { seniority: normalizeSeniority(seniorityRaw, title) } : {}),
            ...(accountId && !accountId.startsWith("pending:") ? { accountId } : {}),
          }
          if (!dryRun) await contactService.update(orgId, cur.id, patch)
          result.updated++
          continue
        }

        const accountId = await resolveAccount(r)
        const seniority = normalizeSeniority(seniorityRaw, title)
        if (!dryRun) {
          const created = await contactService.create(orgId, actorId, { ...fields, accountId, firstName, lastName, email, seniority })
          if (created.email) existingContacts.set(created.email, created)
        }
        result.created++
      } catch (e) {
        result.errors.push({ row: line, message: errorMessage(e) })
      }
    }

    if (!dryRun && result.accountsCreated > 0) await scoringService.rescoreAll(orgId, "Import")
    return result
  },

  template(type: ImportType) {
    const t = TEMPLATES[type]
    const esc = (v: string) => (/[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v)
    return [t.headers, t.example].map((r) => r.map(esc).join(",")).join("\n") + "\n"
  },
}

/** Normalized domain → canonical (non-duplicate preferred) account. */
async function domainIndex(orgId: string, accounts?: Stored<Account>[]) {
  const all = accounts ?? (await db.accounts.find(orgId))
  const map = new Map<string, Stored<Account>>()
  for (const a of all) {
    const d = normalizeDomain(a.domain)
    if (!map.has(d) || (map.get(d)!.duplicateOf && !a.duplicateOf)) map.set(d, a)
  }
  return map
}

const TEMPLATES: Record<ImportType, { headers: string[]; example: string[] }> = {
  accounts: {
    headers: ["name", "domain", "industry", "employees", "revenue", "country", "city", "fundingStage", "description", "linkedinUrl", "technologies", "tags", "ownerEmail"],
    example: [
      "Acme Corp",
      "acme.com",
      "SaaS",
      "250",
      "30000000",
      "United States",
      "San Francisco",
      "Series B",
      "Workflow automation for finance teams",
      "https://www.linkedin.com/company/acme",
      "Salesforce; Snowflake; Segment",
      "priority; conference-2026",
      "",
    ],
  },
  contacts: {
    headers: ["firstName", "lastName", "email", "title", "seniority", "department", "phone", "linkedinUrl", "location", "accountDomain", "accountName"],
    example: [
      "Jane",
      "Doe",
      "jane.doe@acme.com",
      "VP of Sales",
      "VP",
      "Sales",
      "+1 415 555 0100",
      "https://www.linkedin.com/in/janedoe",
      "San Francisco, United States",
      "acme.com",
      "Acme Corp",
    ],
  },
}
