// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { db } from "../../db/index"
import { withContacts } from "../../lib/expand"
import { boolQuery, createModule, csvList, idList, idParams, listQuery, paged, parseSort } from "../../lib/http"
import { activityService } from "../activities/service"
import { scoringService } from "../scoring/service"
import { ACCOUNT_SORT_FIELDS, accountService } from "./service"

export const accountsModule = createModule("Accounts", "/accounts")
const { route } = accountsModule

const tier = z.enum(["A", "B", "C", "D"])
const stage = z.enum(["new", "researching", "engaged", "opportunity", "customer", "disqualified"])

const accountFields = z.object({
  name: z.string().trim().min(1).max(200),
  domain: z.string().trim().min(3).max(253),
  industry: z.string().trim().max(100).optional(),
  employees: z.coerce.number().int().min(0).max(10_000_000).optional(),
  revenue: z.coerce.number().min(0).optional(),
  country: z.string().trim().max(100).optional(),
  city: z.string().trim().max(100).optional(),
  technologies: z.array(z.string().trim().min(1)).max(100).optional(),
  fundingStage: z.string().trim().max(50).optional(),
  description: z.string().max(5000).optional(),
  linkedinUrl: z.string().max(500).optional(),
  ownerId: z.string().nullable().optional(),
  stage: stage.optional(),
  tags: z.array(z.string().trim().min(1)).max(50).optional(),
})

const listFilters = listQuery.extend({
  view: z.enum(["all", "mine", "unassigned", "duplicates"]).optional(),
  tier: csvList.pipe(z.array(tier).optional()),
  industry: csvList,
  stage: csvList.pipe(z.array(stage).optional()),
  country: csvList,
  ownerId: z.string().optional(),
  excludeDuplicates: boolQuery,
})

route({
  method: "get",
  path: "/",
  summary: "List accounts",
  description: "Filters: view (mine|unassigned|duplicates), excludeDuplicates, tier, industry, stage, country (comma-separated), ownerId (or 'none'), q. Sort fields: " + ACCOUNT_SORT_FIELDS.join(", "),
  query: listFilters,
  handler: async ({ orgId, auth, query }) => {
    const sort = parseSort(query.sort, ACCOUNT_SORT_FIELDS, { field: "score", dir: "desc" })
    return paged(await accountService.list(orgId, auth.userId, query, query.page, query.pageSize, sort))
  },
})

route({
  method: "get",
  path: "/counts",
  summary: "Tab counts (all / mine / unassigned / duplicates)",
  handler: ({ orgId, auth }) => accountService.counts(orgId, auth.userId),
})

route({
  method: "get",
  path: "/duplicates",
  summary: "Duplicate candidates with their canonical records",
  handler: async ({ orgId }) => {
    const dups = await db.accounts.find(orgId, { duplicateOf: { exists: true } }, { field: "createdAt", dir: "desc" })
    const canon = await db.accounts.find(orgId, { id: { in: dups.map((d) => d.duplicateOf!) } })
    const counts = await db.contacts.find(orgId, { accountId: { in: [...dups, ...canon].map((a) => a.id) } })
    const n = (id: string) => counts.filter((c) => c.accountId === id).length
    return dups.map((d) => {
      const c = canon.find((x) => x.id === d.duplicateOf)
      return {
        duplicate: { ...d, contactCount: n(d.id), source: d.versions[0]?.source ?? "Unknown" },
        canonical: c ? { ...c, contactCount: n(c.id), source: c.versions[0]?.source ?? "Unknown" } : null,
      }
    })
  },
})

route({
  method: "post",
  path: "/",
  summary: "Create an account (scored and checked for duplicates)",
  body: accountFields,
  handler: ({ orgId, auth, body }) => accountService.create(orgId, auth.userId, body),
})

route({
  method: "get",
  path: "/:id",
  summary: "Get an account with related counts",
  params: idParams,
  handler: async ({ orgId, params }) => {
    const account = await accountService.get(orgId, params.id)
    return { ...account, related: await accountService.related(orgId, params.id) }
  },
})

route({
  method: "patch",
  path: "/:id",
  summary: "Update an account (versioned; re-scores when firmographics change)",
  params: idParams,
  body: accountFields.partial(),
  handler: ({ orgId, params, body }) => accountService.update(orgId, params.id, body),
})

route({
  method: "delete",
  path: "/:id",
  summary: "Delete an account and its related records",
  params: idParams,
  handler: async ({ orgId, params }) => {
    await accountService.get(orgId, params.id)
    await accountService.removeMany(orgId, [params.id])
  },
})

// ---------- Bulk ----------
route({
  method: "post",
  path: "/bulk-delete",
  summary: "Delete many accounts",
  status: 200,
  body: idList,
  handler: async ({ orgId, body }) => ({ deleted: await accountService.removeMany(orgId, body.ids) }),
})

route({
  method: "post",
  path: "/bulk-assign",
  summary: "Assign an owner to many accounts (null to unassign)",
  status: 200,
  body: idList.extend({ ownerId: z.string().nullable() }),
  handler: ({ orgId, body }) => accountService.assignOwner(orgId, body.ids, body.ownerId),
})

route({
  method: "post",
  path: "/bulk-enrich",
  summary: "Run waterfall enrichment on many accounts",
  status: 200,
  body: idList,
  handler: ({ orgId, auth, body }) => accountService.enrich(orgId, body.ids, auth.userId),
})

route({
  method: "post",
  path: "/bulk-rescore",
  summary: "Re-score many accounts",
  status: 200,
  body: idList,
  handler: async ({ orgId, body }) => ({ results: await scoringService.rescoreMany(orgId, body.ids, "Manual re-score") }),
})

route({
  method: "post",
  path: "/bulk-enroll",
  summary: "Enroll all contacts of the given accounts into a sequence",
  status: 200,
  body: idList.extend({ sequenceId: z.string().min(1) }),
  handler: ({ orgId, body }) => accountService.enrollContacts(orgId, body.ids, body.sequenceId),
})

// ---------- Single-account actions ----------
route({
  method: "post",
  path: "/:id/enrich",
  summary: "Enrich one account",
  status: 200,
  params: idParams,
  handler: async ({ orgId, auth, params }) => {
    await accountService.get(orgId, params.id)
    const r = await accountService.enrich(orgId, [params.id], auth.userId)
    return { ...r.results[0], account: await accountService.get(orgId, params.id) }
  },
})

route({
  method: "post",
  path: "/:id/rescore",
  summary: "Re-score one account",
  status: 200,
  params: idParams,
  handler: async ({ orgId, params }) => {
    await accountService.get(orgId, params.id)
    return scoringService.rescoreAccount(orgId, params.id, "Manual re-score")
  },
})

route({
  method: "post",
  path: "/:id/merge",
  summary: "Merge a duplicate into its canonical record",
  status: 200,
  params: idParams,
  handler: ({ orgId, auth, params }) => accountService.merge(orgId, auth.userId, params.id),
})

route({
  method: "post",
  path: "/:id/dismiss-duplicate",
  summary: "Mark a flagged record as not a duplicate",
  status: 200,
  params: idParams,
  handler: ({ orgId, params }) => accountService.dismissDuplicate(orgId, params.id),
})

route({
  method: "post",
  path: "/:id/enroll",
  summary: "Enroll this account's contacts (optionally a subset) into a sequence",
  status: 200,
  params: idParams,
  body: z.object({ sequenceId: z.string().min(1), contactIds: z.array(z.string()).optional() }),
  handler: async ({ orgId, params, body }) => {
    await accountService.get(orgId, params.id)
    return accountService.enrollContacts(orgId, [params.id], body.sequenceId, body.contactIds)
  },
})

// ---------- Related ----------
route({
  method: "get",
  path: "/:id/score-breakdown",
  summary: "Fit breakdown and intent contributors",
  params: idParams,
  handler: async ({ orgId, params }) => scoringService.breakdown(orgId, await accountService.get(orgId, params.id)),
})

route({
  method: "get",
  path: "/:id/versions",
  summary: "Entity version history (newest first)",
  params: idParams,
  handler: async ({ orgId, params }) => [...(await accountService.get(orgId, params.id)).versions].reverse(),
})

route({
  method: "get",
  path: "/:id/contacts",
  summary: "Contacts on this account",
  params: idParams,
  handler: ({ orgId, params }) => db.contacts.find(orgId, { accountId: params.id }, { field: "firstName", dir: "asc" }),
})

route({
  method: "get",
  path: "/:id/signals",
  summary: "Signals for this account",
  params: idParams,
  handler: async ({ orgId, params }) =>
    withContacts(orgId, await db.signals.find(orgId, { accountId: params.id }, { field: "occurredAt", dir: "desc" })),
})

route({
  method: "get",
  path: "/:id/deals",
  summary: "Deals on this account",
  params: idParams,
  handler: ({ orgId, params }) => db.deals.find(orgId, { accountId: params.id }, { field: "updatedAt", dir: "desc" }),
})

route({
  method: "get",
  path: "/:id/activities",
  summary: "Activity timeline for this account",
  params: idParams,
  query: z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(200).default(50) }),
  handler: async ({ orgId, params, query }) =>
    paged(await activityService.list(orgId, { accountId: params.id, page: query.page, pageSize: query.pageSize })),
})
