// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import type { Where } from "../../db/repository"
import type { Account, AccountStage, EntityVersion, Stored, Tier } from "../../domain/types"
import { bus } from "../../events/bus"
import { badRequest, conflict, notFound } from "../../lib/errors"
import { nowIso } from "../../lib/ids"
import { providers } from "../../providers/index"
import { activityService } from "../activities/service"
import { enrollmentService } from "../outreach/enrollment"
import { scoringService } from "../scoring/service"
import { scoreAccount } from "../scoring/engine"

export const ACCOUNT_SORT_FIELDS = ["name", "score", "intentScore", "fitScore", "employees", "updatedAt", "createdAt", "enrichedAt"] as const

export interface AccountFilters {
  view?: "all" | "mine" | "unassigned" | "duplicates"
  tier?: Tier[]
  industry?: string[]
  stage?: AccountStage[]
  ownerId?: string
  country?: string[]
  excludeDuplicates?: boolean
  q?: string
}

/** Fields that affect the fit score — changing them triggers a re-score. */
const SCORING_FIELDS: (keyof Account)[] = ["industry", "employees", "revenue", "country", "technologies", "fundingStage"]
/** Fields that are bookkeeping and never versioned. */
const UNVERSIONED = new Set(["updatedAt", "scoreHistory", "versions", "fitScore", "intentScore", "score", "tier"])

export const normalizeDomain = (d: string) =>
  d.trim().toLowerCase().replace(/^https?:\/\//, "").replace(/^www\./, "").replace(/\/.*$/, "")

const fmt = (v: unknown) => (v === undefined || v === null || v === "" ? "—" : Array.isArray(v) ? v.join(", ") : String(v))

export function diffVersion(cur: Account, patch: Partial<Account>, source: string): EntityVersion | null {
  const changes = Object.entries(patch)
    .filter(([k]) => !UNVERSIONED.has(k))
    .filter(([k, v]) => v !== undefined && JSON.stringify(cur[k as keyof Account] ?? null) !== JSON.stringify(v ?? null))
    .map(([k, v]) => ({ field: k, from: fmt(cur[k as keyof Account]), to: fmt(v) }))
  if (!changes.length) return null
  return { version: cur.versions.length + 1, at: nowIso(), source, changes }
}

export function accountWhere(f: AccountFilters, userId: string): Where<Stored<Account>> {
  return {
    tier: f.tier?.length ? { in: f.tier } : undefined,
    industry: f.industry?.length ? { in: f.industry } : undefined,
    stage: f.stage?.length ? { in: f.stage } : undefined,
    country: f.country?.length ? { in: f.country } : undefined,
    ownerId: f.view === "mine" ? userId : f.view === "unassigned" ? null : f.ownerId === "none" ? null : f.ownerId,
    // The "all" tab hides flagged duplicates (they have their own tab).
    duplicateOf:
      f.view === "duplicates" ? { exists: true } : f.excludeDuplicates || f.view === "all" ? { exists: false } : undefined,
    $or: f.q ? [{ name: { contains: f.q } }, { domain: { contains: f.q } }] : undefined,
  }
}

export type AccountCreateInput = Pick<Account, "name" | "domain"> & Partial<Omit<Account, "id" | "createdAt" | "updatedAt">>

export const accountService = {
  async list(orgId: string, userId: string, f: AccountFilters, page: number, pageSize: number, sort: { field: (typeof ACCOUNT_SORT_FIELDS)[number]; dir: "asc" | "desc" }) {
    return db.accounts.list(orgId, { where: accountWhere(f, userId), sort: [sort, { field: "name", dir: "asc" }], page, pageSize })
  },

  async counts(orgId: string, userId: string) {
    const all = await db.accounts.find(orgId)
    return {
      all: all.filter((a) => !a.duplicateOf).length,
      mine: all.filter((a) => a.ownerId === userId).length,
      unassigned: all.filter((a) => !a.ownerId).length,
      duplicates: all.filter((a) => a.duplicateOf).length,
    }
  },

  async get(orgId: string, id: string) {
    const a = await db.accounts.get(orgId, id)
    if (!a) throw notFound("Account")
    return a
  },

  async create(orgId: string, actorId: string, input: AccountCreateInput, source = "Manual entry") {
    const domain = normalizeDomain(input.domain)
    if (!domain.includes(".")) throw badRequest("Domain must look like example.com")
    const dup = await db.accounts.findOne(orgId, { domain, duplicateOf: { exists: false } })
    const [icp, now] = [await scoringService.getIcp(orgId), nowIso()]
    const base: Omit<Account, "id"> = {
      industry: "Other",
      employees: 0,
      country: "",
      city: "",
      technologies: [],
      fundingStage: "",
      description: "",
      linkedinUrl: "",
      ownerId: null,
      stage: "new",
      enrichmentSources: [],
      tags: [],
      ...input,
      revenue: input.revenue ?? (input.employees ?? 0) * 120_000,
      domain,
      fitScore: 0,
      intentScore: 0,
      score: 0,
      tier: "D",
      scoreHistory: [],
      versions: [{ version: 1, at: now, source, changes: [{ field: "record", from: "—", to: "created" }] }],
      duplicateOf: dup?.id,
      createdAt: now,
      updatedAt: now,
    }
    const sc = scoreAccount({ ...base, id: "new" }, [], icp)
    const created = await db.accounts.create(orgId, {
      ...base,
      fitScore: sc.fit,
      intentScore: sc.intent,
      score: sc.score,
      tier: sc.tier,
      scoreHistory: [{ at: now, fit: sc.fit, intent: sc.intent, score: sc.score, reason: "Initial score" }],
    })
    await activityService.log(orgId, { accountId: created.id, type: "note", title: "Account created", detail: source, actorId })
    await bus.publish("account.created", { orgId, accountId: created.id })
    return { account: created, duplicateOf: dup ? { id: dup.id, name: dup.name } : null }
  },

  async update(orgId: string, id: string, patch: Partial<Account>, source = "Manual edit") {
    const cur = await this.get(orgId, id)
    if (patch.domain) patch.domain = normalizeDomain(patch.domain)
    const version = diffVersion(cur, patch, source)
    await db.accounts.update(orgId, id, { ...patch, versions: version ? [...cur.versions, version] : cur.versions })
    if (SCORING_FIELDS.some((f) => patch[f] !== undefined && JSON.stringify(patch[f]) !== JSON.stringify(cur[f]))) {
      const r = await scoringService.rescoreAccount(orgId, id, `${source}: firmographics changed`)
      return { account: r.account!, rescore: { before: r.before, after: r.after, tier: r.tier } }
    }
    return { account: await this.get(orgId, id), rescore: null }
  },

  async removeMany(orgId: string, ids: string[]) {
    const contacts = await db.contacts.find(orgId, { accountId: { in: ids } })
    const contactIds = contacts.map((c) => c.id)
    await db.enrollments.removeMany(orgId, { contactId: { in: contactIds } })
    await db.inbox.removeMany(orgId, { contactId: { in: contactIds } })
    await db.contacts.removeMany(orgId, { accountId: { in: ids } })
    await db.deals.removeMany(orgId, { accountId: { in: ids } })
    await db.signals.removeMany(orgId, { accountId: { in: ids } })
    await db.drafts.removeMany(orgId, { accountId: { in: ids } })
    await db.runs.removeMany(orgId, { accountId: { in: ids } })
    await db.activities.removeMany(orgId, { accountId: { in: ids } })
    // Duplicates pointing at removed canonicals become standalone records.
    await db.accounts.updateMany(orgId, { duplicateOf: { in: ids } }, { duplicateOf: undefined })
    return db.accounts.removeMany(orgId, { id: { in: ids } })
  },

  async assignOwner(orgId: string, ids: string[], ownerId: string | null, source = "Owner assignment") {
    if (ownerId) {
      const owner = await db.users.get(orgId, ownerId)
      if (!owner) throw badRequest("Owner not found in this organization")
    }
    for (const id of ids) {
      const cur = await db.accounts.get(orgId, id)
      if (!cur) continue
      const version = diffVersion(cur, { ownerId }, source)
      await db.accounts.update(orgId, id, { ownerId, versions: version ? [...cur.versions, version] : cur.versions })
    }
    await db.contacts.updateMany(orgId, { accountId: { in: ids } }, { ownerId })
    return { updated: ids.length }
  },

  async enrich(orgId: string, ids: string[], actorId: string | "agent" | "system" = "system") {
    const org = await db.organizations.get(orgId, orgId)
    const waterfall = await enrichmentWaterfall(orgId, org?.settings.waterfallOrder ?? [])
    const results = []
    for (const id of ids) {
      const cur = await db.accounts.get(orgId, id)
      if (!cur) continue
      const { patch, sources } = await providers.enrichment.enrichAccount(cur, waterfall)
      const label = `Waterfall enrichment (${sources.join(" → ")})`
      const { rescore } = await this.update(
        orgId,
        id,
        { ...patch, enrichedAt: nowIso(), enrichmentSources: [...new Set([...cur.enrichmentSources, ...sources])] },
        label,
      )
      await activityService.log(orgId, { accountId: id, type: "enrichment", title: "Account enriched", detail: sources.join(" → "), actorId })
      results.push({ id, sources, rescore })
    }
    return { enriched: results.length, results }
  },

  async merge(orgId: string, actorId: string, dupId: string) {
    const dup = await this.get(orgId, dupId)
    if (!dup.duplicateOf) throw conflict("Account is not flagged as a duplicate")
    const target = await db.accounts.get(orgId, dup.duplicateOf)
    if (!target) throw notFound("Canonical account")
    const move = { accountId: target.id }
    await db.contacts.updateMany(orgId, { accountId: dupId }, move)
    await db.signals.updateMany(orgId, { accountId: dupId }, move)
    await db.deals.updateMany(orgId, { accountId: dupId }, move)
    await db.activities.updateMany(orgId, { accountId: dupId }, move)
    await db.drafts.updateMany(orgId, { accountId: dupId }, move)
    await db.runs.updateMany(orgId, { accountId: dupId }, move)
    await db.accounts.remove(orgId, dupId)
    await this.update(
      orgId,
      target.id,
      {
        tags: [...new Set([...target.tags, ...dup.tags])],
        technologies: [...new Set([...target.technologies, ...dup.technologies])],
        ownerId: target.ownerId ?? dup.ownerId,
      },
      `Merged duplicate “${dup.name}”`,
    )
    await activityService.log(orgId, { accountId: target.id, type: "note", title: `Merged duplicate record “${dup.name}”`, actorId })
    await scoringService.rescoreAccount(orgId, target.id, "Duplicate merged")
    return this.get(orgId, target.id)
  },

  async dismissDuplicate(orgId: string, id: string) {
    await this.get(orgId, id)
    return db.accounts.update(orgId, id, { duplicateOf: undefined })
  },

  async enrollContacts(orgId: string, accountIds: string[], sequenceId: string, contactIds?: string[]) {
    const contacts = await db.contacts.find(orgId, { accountId: { in: accountIds } })
    const ids = contacts.map((c) => c.id).filter((id) => !contactIds || contactIds.includes(id))
    return enrollmentService.enroll(orgId, ids, sequenceId)
  },

  async related(orgId: string, id: string) {
    const [contacts, signals, deals] = await Promise.all([
      db.contacts.count(orgId, { accountId: id }),
      db.signals.count(orgId, { accountId: id }),
      db.deals.find(orgId, { accountId: id }),
    ])
    const open = deals.filter((d) => !d.stage.startsWith("closed"))
    return { contacts, signals, deals: deals.length, openDeals: open.length, openPipeline: open.reduce((s, d) => s + d.amount, 0) }
  },
}

/** Connected enrichment/contacts vendors that are enabled for the waterfall, in configured order. */
export async function enrichmentWaterfall(orgId: string, order: string[]) {
  const ints = await db.integrations.find(orgId, { connected: true, category: { in: ["enrichment", "contacts"] } })
  const enabled = ints.filter((i) => i.settings.useInWaterfall !== false)
  enabled.sort((a, b) => {
    const ia = order.indexOf(a.key)
    const ib = order.indexOf(b.key)
    return (ia < 0 ? 999 : ia) - (ib < 0 ? 999 : ib)
  })
  return enabled.map((i) => i.name)
}
