// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import type { IntegrationCategory } from "../../domain/types"
import { boolQuery, createModule, csvList, idParams } from "../../lib/http"
import { atLeast } from "../../middleware/auth"
import { integrationService } from "./service"

export const integrationsModule = createModule("Integrations", "/integrations")
const { route } = integrationsModule

const CATEGORIES = ["enrichment", "intent", "contacts", "scraping", "email", "linkedin", "calls", "crm", "llm"] as const

route({
  method: "get",
  path: "/",
  summary: "List integrations (catalog order)",
  query: z.object({
    category: csvList.pipe(z.array(z.enum(CATEGORIES)).optional()),
    connected: boolQuery,
    q: z.string().trim().optional(),
  }),
  handler: ({ orgId, query }) =>
    integrationService.list(orgId, {
      category: query.category as IntegrationCategory[] | undefined,
      connected: query.connected,
      q: query.q,
    }),
})

route({
  method: "get",
  path: "/stats",
  summary: "Connected / error counts and usage totals",
  handler: ({ orgId }) => integrationService.stats(orgId),
})

// Declared before "/:id" so it isn't captured by the param route.
route({
  method: "get",
  path: "/waterfall",
  summary: "Enrichment waterfall providers in order",
  handler: ({ orgId }) => integrationService.waterfall(orgId),
})

route({
  method: "put",
  path: "/waterfall",
  summary: "Save the enrichment waterfall order (integration keys)",
  roles: atLeast("admin"),
  body: z.object({ keys: z.array(z.string().trim().min(1)).max(50) }),
  handler: ({ orgId, body }) => integrationService.setWaterfall(orgId, body.keys),
})

route({
  method: "get",
  path: "/:id",
  summary: "Get an integration with recent sync log",
  params: idParams,
  handler: ({ orgId, params }) => integrationService.get(orgId, params.id),
})

route({
  method: "post",
  path: "/:id/connect",
  summary: "Connect with an API key (verified against the vendor)",
  status: 200,
  roles: atLeast("admin"),
  params: idParams,
  body: z.object({ apiKey: z.string().trim().min(8).max(500) }),
  handler: ({ orgId, params, body }) => integrationService.connect(orgId, params.id, body.apiKey),
})

route({
  method: "post",
  path: "/:id/disconnect",
  summary: "Disconnect and discard the stored credential",
  status: 200,
  roles: atLeast("admin"),
  params: idParams,
  handler: ({ orgId, params }) => integrationService.disconnect(orgId, params.id),
})

route({
  method: "post",
  path: "/:id/sync",
  summary: "Trigger a sync now",
  status: 200,
  params: idParams,
  handler: ({ orgId, params }) => integrationService.sync(orgId, params.id),
})

route({
  method: "patch",
  path: "/:id/settings",
  summary: "Merge integration settings",
  roles: atLeast("admin"),
  params: idParams,
  body: z.record(z.string().min(1).max(64), z.union([z.string().max(500), z.boolean()])),
  handler: ({ orgId, params, body }) => integrationService.updateSettings(orgId, params.id, body),
})
