// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import { INTEGRATION_CATALOG } from "../../domain/constants"
import type { Integration, IntegrationCategory, Stored } from "../../domain/types"
import { encrypt, mask } from "../../lib/crypto"
import { badRequest, notFound } from "../../lib/errors"
import { nowIso } from "../../lib/ids"
import { providers } from "../../providers/index"

export type PublicIntegration = Omit<Stored<Integration>, "apiKeyEncrypted">

/** Strips server-only fields (the encrypted vendor credential). */
export function toPublicIntegration(i: Stored<Integration>): PublicIntegration {
  const { apiKeyEncrypted: _secret, ...rest } = i
  return rest
}

const WATERFALL_CATEGORIES: IntegrationCategory[] = ["enrichment", "contacts"]

const catalogRank = (key: string) => {
  const i = INTEGRATION_CATALOG.findIndex((c) => c.key === key)
  return i < 0 ? INTEGRATION_CATALOG.length : i
}

const byCatalog = (a: Integration, b: Integration) => catalogRank(a.key) - catalogRank(b.key) || a.name.localeCompare(b.name)

const SYNC_INTERVAL_MS: Record<string, number> = { "15min": 15 * 60_000, hourly: 60 * 60_000, daily: 24 * 60 * 60_000 }

const hash = (s: string) => [...s].reduce((h, c) => (h * 31 + c.charCodeAt(0)) >>> 0, 7)

export interface SyncLogEntry {
  at: string
  ok: boolean
  message: string
  durationMs: number
}

/** Deterministic, plausible recent sync history derived from lastSyncAt / status. */
function buildSyncLog(i: Integration): SyncLogEntry[] {
  if (!i.lastSyncAt) return []
  const base = new Date(i.lastSyncAt).getTime()
  const interval = SYNC_INTERVAL_MS[String(i.settings.syncInterval ?? "hourly")] ?? SYNC_INTERVAL_MS.hourly
  const noun = i.category === "llm" ? "requests" : i.category === "intent" ? "signals" : "records"
  return Array.from({ length: 5 }, (_, idx) => {
    const failed = idx === 0 && i.status === "error"
    const count = (hash(`${i.id}-${idx}`) % 180) + 12
    return {
      at: new Date(base - idx * interval).toISOString(),
      ok: !failed,
      message: failed ? "401 Unauthorized — API key rejected" : `Synced ${count} ${noun}`,
      durationMs: 400 + (hash(`${i.id}:${idx}`) % 2600),
    }
  })
}

export interface IntegrationFilters {
  category?: IntegrationCategory[]
  connected?: boolean
  q?: string
}

export const integrationService = {
  async getRaw(orgId: string, id: string) {
    const i = await db.integrations.get(orgId, id)
    if (!i) throw notFound("Integration")
    return i
  },

  async list(orgId: string, f: IntegrationFilters) {
    const items = await db.integrations.find(orgId, {
      category: f.category?.length ? { in: f.category } : undefined,
      connected: f.connected,
      $or: f.q ? [{ name: { contains: f.q } }, { description: { contains: f.q } }, { feeds: { contains: f.q } }] : undefined,
    })
    return items.sort(byCatalog).map(toPublicIntegration)
  },

  async stats(orgId: string) {
    const all = await db.integrations.find(orgId)
    const connected = all.filter((i) => i.connected)
    return {
      total: all.length,
      connected: connected.length,
      errors: all.filter((i) => i.status === "error").length,
      errorIds: all.filter((i) => i.status === "error").map((i) => i.id),
      creditsUsed: connected.reduce((s, i) => s + (i.usage && i.usage.unit === "credits" ? i.usage.used : 0), 0),
      tokensUsed: connected.reduce((s, i) => s + (i.usage && i.usage.unit !== "credits" ? i.usage.used : 0), 0),
    }
  },

  async get(orgId: string, id: string) {
    const i = await this.getRaw(orgId, id)
    return { ...toPublicIntegration(i), syncLog: buildSyncLog(i) }
  },

  async connect(orgId: string, id: string, apiKey: string) {
    const i = await this.getRaw(orgId, id)
    const result = await providers.connections.test(i.key, apiKey)
    if (!result.ok) throw badRequest(result.message ?? `Could not connect to ${i.name}`)
    const updated = await db.integrations.update(orgId, id, {
      connected: true,
      status: "ok",
      lastSyncAt: nowIso(),
      apiKeyEncrypted: encrypt(apiKey),
      apiKeyMasked: mask(apiKey),
      usage: i.usage ?? { used: 0, limit: 10_000, unit: i.category === "llm" ? "k tokens" : "credits" },
    })
    return toPublicIntegration(updated)
  },

  async disconnect(orgId: string, id: string) {
    await this.getRaw(orgId, id)
    const updated = await db.integrations.update(orgId, id, {
      connected: false,
      status: "disconnected",
      apiKeyEncrypted: undefined,
      apiKeyMasked: undefined,
      lastSyncAt: undefined,
    })
    return toPublicIntegration(updated)
  },

  async sync(orgId: string, id: string) {
    const i = await this.getRaw(orgId, id)
    if (!i.connected) throw badRequest(`${i.name} is not connected`)
    const updated = await db.integrations.update(orgId, id, {
      status: "ok",
      lastSyncAt: nowIso(),
      usage: i.usage && { ...i.usage, used: Math.min(i.usage.limit, i.usage.used + Math.floor(Math.random() * 151)) },
    })
    return toPublicIntegration(updated)
  },

  async updateSettings(orgId: string, id: string, settings: Integration["settings"]) {
    const i = await this.getRaw(orgId, id)
    const updated = await db.integrations.update(orgId, id, { settings: { ...i.settings, ...settings } })
    return toPublicIntegration(updated)
  },

  async getOrg(orgId: string) {
    const org = await db.organizations.get(orgId, orgId)
    if (!org) throw notFound("Organization")
    return org
  },

  /** Connected enrichment/contacts vendors enabled for the waterfall, in the org's configured order. */
  async waterfall(orgId: string) {
    const org = await this.getOrg(orgId)
    const order = org.settings?.waterfallOrder ?? []
    const ints = await db.integrations.find(orgId, { connected: true, category: { in: WATERFALL_CATEGORIES } })
    const rank = (key: string) => {
      const idx = order.indexOf(key)
      return idx < 0 ? 999 : idx
    }
    return ints
      .filter((i) => i.settings.useInWaterfall !== false)
      .sort((a, b) => rank(a.key) - rank(b.key) || byCatalog(a, b))
      .map((i, idx) => ({ ...toPublicIntegration(i), position: idx + 1 }))
  },

  async setWaterfall(orgId: string, keys: string[]) {
    const org = await this.getOrg(orgId)
    const unique = [...new Set(keys)]
    const known = await db.integrations.find(orgId, { key: { in: unique }, category: { in: WATERFALL_CATEGORIES } })
    const knownKeys = new Set(known.map((i) => i.key))
    const unknown = unique.filter((k) => !knownKeys.has(k))
    if (unknown.length) throw badRequest(`Not enrichment/contacts integrations: ${unknown.join(", ")}`)
    // Keep previously-ordered keys that weren't included (e.g. disconnected vendors) after the new order.
    const prev = org.settings?.waterfallOrder ?? []
    const waterfallOrder = [...unique, ...prev.filter((k) => !unique.includes(k))]
    await db.organizations.update(orgId, orgId, { settings: { ...org.settings, waterfallOrder } })
    return this.waterfall(orgId)
  },
}
