// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import type { Repository } from "../repository"

/**
 * Placeholder for the PostgreSQL (RDS) driver.
 *
 * To implement:
 *  1. `npm i pg` and create a pool from DATABASE_URL (DB_POOL_MIN/MAX).
 *  2. One table per collection (see ../index.ts) with columns: id text pk, org_id text,
 *     created_at timestamptz, updated_at timestamptz, data jsonb — or fully normalized columns.
 *     Put DDL in ./migrations/NNN_name.sql.
 *  3. Translate `Where<T>` (see ../repository.ts) into SQL: eq → =, in → = ANY($n),
 *     gt/gte/lt/lte → comparisons, contains → ILIKE, exists → IS [NOT] NULL, $or → OR.
 *  4. Always filter by org_id.
 */
export function createPostgresRepository<T extends { id: string }>(name: string): Repository<T> {
  throw new Error(
    `DB_DRIVER=postgres is not implemented yet (collection "${name}"). ` +
      "Set DB_DRIVER=json or implement src/db/postgres/postgres-repository.ts.",
  )
}
