// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { createModule, fileResponse } from "../../lib/http"
import { analyticsService, ANALYTICS_RANGES, type RangeDays } from "./service"

export const analyticsModule = createModule("Analytics", "/analytics")
const { route } = analyticsModule

const rangeQuery = z.object({
  days: z
    .enum(ANALYTICS_RANGES)
    .default("90")
    .transform((v) => Number(v) as RangeDays),
})

route({
  method: "get",
  path: "/dashboard",
  summary: "Dashboard aggregates (stats, 30-day activity, pipeline by stage, hot accounts, latest signals and agent runs)",
  handler: ({ orgId }) => analyticsService.dashboard(orgId),
})

route({
  method: "get",
  path: "/overview",
  summary: "Analytics overview for a date range (KPIs, weekly pipeline, attribution, funnel, tiers, sequences, reps, source mix)",
  description: "Deals are in range by createdAt, won deals by closeDate, accounts by createdAt, signals by occurredAt. Sequence stats are all-time.",
  query: rangeQuery,
  handler: ({ orgId, query }) => analyticsService.overview(orgId, query.days),
})

route({
  method: "get",
  path: "/deals.csv",
  summary: "Export deals created in the date range as CSV",
  produces: "text/csv",
  query: rangeQuery,
  handler: async ({ orgId, query }) => {
    const { csv } = await analyticsService.dealsCsv(orgId, query.days)
    const date = new Date().toISOString().slice(0, 10)
    return fileResponse(`selleasy-deals-${query.days}d-${date}.csv`, csv)
  },
})
