// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import { DEAL_STAGE_LABEL, DEAL_STAGES, SIGNAL_LABELS } from "../../domain/constants"
import type { Deal, SignalType, Stored, Tier } from "../../domain/types"
import { DAY_MS } from "../../lib/ids"

const TIERS: Tier[] = ["A", "B", "C", "D"]
const ENGAGED_STAGES = new Set(["engaged", "opportunity", "customer"])

const ratio = (a: number, b: number) => (b > 0 ? (a / b) * 100 : 0)
const time = (iso: string) => new Date(iso).getTime()
const sum = <T>(items: T[], f: (t: T) => number) => items.reduce((s, t) => s + f(t), 0)
const isClosed = (d: Pick<Deal, "stage">) => d.stage.startsWith("closed")
/** Deals opened by the orchestration agent carry a source starting with "Agent". */
export const isAgentSourced = (source: string) => source.startsWith("Agent")
/** UTC calendar day, yyyy-mm-dd. */
const isoDay = (ms: number) => new Date(ms).toISOString().slice(0, 10)
/** Start (Sunday 00:00 UTC) of the week containing `ms`. */
function weekStart(ms: number) {
  const d = new Date(ms)
  d.setUTCHours(0, 0, 0, 0)
  d.setUTCDate(d.getUTCDate() - d.getUTCDay())
  return d.getTime()
}

export const ANALYTICS_RANGES = ["30", "90", "180"] as const
export type RangeDays = 30 | 90 | 180

export const DEAL_CSV_HEADERS = [
  "Deal ID",
  "Deal",
  "Account",
  "Tier",
  "Stage",
  "Amount",
  "Probability",
  "Weighted",
  "Close date",
  "Owner",
  "Source",
  "CRM ID",
  "Synced",
  "Created",
  "Updated",
]

const csvEscape = (v: unknown) => {
  const s = v === null || v === undefined ? "" : String(v)
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}
export const toCsv = (headers: string[], rows: unknown[][]) => [headers, ...rows].map((r) => r.map(csvEscape).join(",")).join("\n")

/** Deals created within the range (the analytics page's scope). */
function dealsInRange(deals: Stored<Deal>[], cutoff: number) {
  return deals.filter((d) => time(d.createdAt) >= cutoff)
}

export const analyticsService = {
  async dashboard(orgId: string) {
    const [accounts, signals, deals, runs, drafts, positiveReplies] = await Promise.all([
      db.accounts.find(orgId),
      db.signals.find(orgId, undefined, { field: "occurredAt", dir: "desc" }),
      db.deals.find(orgId),
      db.runs.find(orgId, undefined, { field: "startedAt", dir: "desc" }),
      db.drafts.count(orgId, { status: "pending" }),
      db.inbox.count(orgId, { sentiment: "positive" }),
    ])
    const now = Date.now()
    const open = deals.filter((d) => !isClosed(d))
    const weekAgo = now - 7 * DAY_MS
    const real = accounts.filter((a) => !a.duplicateOf)
    const names = new Map(accounts.map((a) => [a.id, a.name]))

    const stats = {
      pipeline: sum(open, (d) => d.amount),
      weighted: sum(open, (d) => (d.amount * d.probability) / 100),
      won: sum(
        deals.filter((d) => d.stage === "closed_won"),
        (d) => d.amount,
      ),
      hotAccounts: real.filter((a) => a.tier === "A").length,
      signals7d: signals.filter((s) => time(s.occurredAt) > weekAgo).length,
      positiveReplies,
      pendingDrafts: drafts,
      openDeals: open.length,
    }

    const days = Array.from({ length: 30 }, (_, i) => isoDay(now - (29 - i) * DAY_MS))
    const activity = new Map(days.map((day) => [day, { day, signals: 0, agentActions: 0 }]))
    for (const s of signals) {
      const row = activity.get(isoDay(time(s.occurredAt)))
      if (row) row.signals++
    }
    for (const r of runs) {
      const row = activity.get(isoDay(time(r.startedAt)))
      if (row && r.status !== "skipped") row.agentActions++
    }

    const pipelineByStage = DEAL_STAGES.filter((s) => !s.id.startsWith("closed")).map((s) => {
      const inStage = open.filter((d) => d.stage === s.id)
      return { stage: s.id, label: s.label, amount: sum(inStage, (d) => d.amount), count: inStage.length }
    })

    const hotAccounts = [...real]
      .sort((a, b) => b.intentScore - a.intentScore)
      .slice(0, 6)
      .map((a) => ({
        id: a.id,
        name: a.name,
        industry: a.industry,
        employees: a.employees,
        tier: a.tier,
        intentScore: a.intentScore,
        score: a.score,
      }))

    const latestSignals = signals.slice(0, 6).map((s) => ({ ...s, accountName: names.get(s.accountId) ?? null }))
    const latestRuns = runs.slice(0, 6).map((r) => ({
      id: r.id,
      accountId: r.accountId,
      accountName: names.get(r.accountId) ?? null,
      status: r.status,
      trigger: r.trigger,
      startedAt: r.startedAt,
    }))

    return { stats, activity30d: [...activity.values()], pipelineByStage, hotAccounts, latestSignals, latestRuns }
  },

  async overview(orgId: string, days: RangeDays) {
    const [accounts, deals, signals, sequences, users] = await Promise.all([
      db.accounts.find(orgId),
      db.deals.find(orgId),
      db.signals.find(orgId),
      db.sequences.find(orgId),
      db.users.find(orgId),
    ])
    const now = Date.now()
    const cutoff = now - days * DAY_MS

    const realAccounts = accounts.filter((a) => !a.duplicateOf)
    const accountsInRange = realAccounts.filter((a) => time(a.createdAt) >= cutoff)
    const inRange = dealsInRange(deals, cutoff)
    const wonInRange = deals.filter((d) => d.stage === "closed_won" && time(d.closeDate) >= cutoff)
    const signalsInRange = signals.filter((s) => time(s.occurredAt) >= cutoff)

    // ---------- KPIs ----------
    const created = sum(inRange, (d) => d.amount)
    const agent = sum(
      inRange.filter((d) => isAgentSourced(d.source)),
      (d) => d.amount,
    )
    const totals = {
      sent: sum(sequences, (q) => q.stats.sent),
      replied: sum(sequences, (q) => q.stats.replied),
      meetings: sum(sequences, (q) => q.stats.meetings),
    }
    const stats = {
      pipelineCreated: created,
      dealsCreated: inRange.length,
      revenueWon: sum(wonInRange, (d) => d.amount),
      dealsWon: wonInRange.length,
      replyRate: ratio(totals.replied, totals.sent),
      replies: totals.replied,
      meetings: totals.meetings,
      agentPipeline: agent,
      agentPct: ratio(agent, created),
      signals: signalsInRange.length,
    }

    // ---------- Pipeline created by week ----------
    const weeks = new Map<number, { week: string; agent: number; sequence: number; other: number }>()
    for (let w = weekStart(cutoff); w <= now; w += 7 * DAY_MS) weeks.set(w, { week: isoDay(w), agent: 0, sequence: 0, other: 0 })
    for (const d of inRange) {
      const row = weeks.get(weekStart(time(d.createdAt)))
      if (!row) continue
      if (isAgentSourced(d.source)) row.agent += d.amount
      else if (d.source === "Sequence reply") row.sequence += d.amount
      else row.other += d.amount
    }

    // ---------- Attribution by signal type ----------
    const signalsByAccount = new Map<string, typeof signals>()
    for (const s of signals) {
      const list = signalsByAccount.get(s.accountId)
      if (list) list.push(s)
      else signalsByAccount.set(s.accountId, [s])
    }
    const attribution = (Object.keys(SIGNAL_LABELS) as SignalType[])
      .map((type) => {
        const touched = inRange.filter((d) =>
          (signalsByAccount.get(d.accountId) ?? []).some((s) => s.type === type && time(s.occurredAt) < time(d.createdAt)),
        )
        return { type, label: SIGNAL_LABELS[type], amount: sum(touched, (d) => d.amount), deals: touched.length }
      })
      .sort((a, b) => b.amount - a.amount)

    // ---------- Funnel ----------
    const withDeal = new Set(deals.map((d) => d.accountId))
    const withWon = new Set(deals.filter((d) => d.stage === "closed_won").map((d) => d.accountId))
    const steps = [
      { step: "Accounts", count: accountsInRange.length },
      { step: "Engaged", count: accountsInRange.filter((a) => ENGAGED_STAGES.has(a.stage) || withDeal.has(a.id)).length },
      { step: "Opportunities", count: accountsInRange.filter((a) => withDeal.has(a.id)).length },
      { step: "Won", count: accountsInRange.filter((a) => withWon.has(a.id)).length },
    ]
    const funnel = steps.map((s, i) => ({ ...s, conversion: i === 0 ? 100 : ratio(s.count, steps[i - 1]!.count) }))

    // ---------- Tier performance ----------
    const tiers = TIERS.map((tier) => {
      const ids = new Set(realAccounts.filter((a) => a.tier === tier).map((a) => a.id))
      const tierDeals = inRange.filter((d) => ids.has(d.accountId))
      const won = tierDeals.filter((d) => d.stage === "closed_won")
      const lost = tierDeals.filter((d) => d.stage === "closed_lost")
      const wonAmount = sum(won, (d) => d.amount)
      return {
        tier,
        accounts: ids.size,
        deals: tierDeals.length,
        closed: won.length + lost.length,
        winRate: ratio(won.length, won.length + lost.length),
        avgDeal: won.length ? wonAmount / won.length : 0,
        pipeline: sum(tierDeals, (d) => d.amount),
        won: wonAmount,
      }
    })

    // ---------- Sequences (all-time stats) ----------
    const sequenceRows = sequences
      .map((q) => ({
        id: q.id,
        name: q.name,
        status: q.status,
        stats: q.stats,
        openRate: ratio(q.stats.opened, q.stats.sent),
        replyRate: ratio(q.stats.replied, q.stats.sent),
        meetingRate: ratio(q.stats.meetings, q.stats.replied),
      }))
      .sort((a, b) => b.replyRate - a.replyRate)

    // ---------- Reps ----------
    const reps = users
      .filter((u) => u.role !== "viewer")
      .map((u) => {
        const won = wonInRange.filter((d) => d.ownerId === u.id)
        return {
          user: { id: u.id, name: u.name, email: u.email, role: u.role, avatarColor: u.avatarColor, title: u.title },
          accountsOwned: realAccounts.filter((a) => a.ownerId === u.id).length,
          openPipeline: sum(
            deals.filter((d) => d.ownerId === u.id && !isClosed(d)),
            (d) => d.amount,
          ),
          wonAmount: sum(won, (d) => d.amount),
          dealsWon: won.length,
        }
      })
      .sort((a, b) => b.wonAmount - a.wonAmount || b.openPipeline - a.openPipeline)

    // ---------- Signal source mix ----------
    const counts = new Map<string, number>()
    for (const s of signalsInRange) counts.set(s.source, (counts.get(s.source) ?? 0) + 1)
    const sorted = [...counts.entries()].sort((a, b) => b[1] - a[1])
    const rest = sum(sorted.slice(4), ([, n]) => n)
    const sourceMix = [...sorted.slice(0, 4), ...(rest ? [["Other", rest] as [string, number]] : [])].map(([source, count]) => ({
      source,
      count,
    }))

    return {
      range: { days, from: new Date(cutoff).toISOString(), to: new Date(now).toISOString() },
      stats,
      pipelineByWeek: [...weeks.values()],
      attribution,
      funnel,
      tiers,
      sequences: sequenceRows,
      reps,
      sourceMix,
    }
  },

  async dealsCsv(orgId: string, days: RangeDays) {
    const [deals, accounts, users] = await Promise.all([db.deals.find(orgId, undefined, { field: "createdAt", dir: "desc" }), db.accounts.find(orgId), db.users.find(orgId)])
    const accById = new Map(accounts.map((a) => [a.id, a]))
    const userById = new Map(users.map((u) => [u.id, u]))
    const rows = dealsInRange(deals, Date.now() - days * DAY_MS).map((d) => [
      d.id,
      d.name,
      accById.get(d.accountId)?.name ?? "",
      accById.get(d.accountId)?.tier ?? "",
      DEAL_STAGE_LABEL[d.stage],
      d.amount,
      d.probability,
      Math.round((d.amount * d.probability) / 100),
      d.closeDate.slice(0, 10),
      userById.get(d.ownerId)?.name ?? "",
      d.source,
      d.crmId ?? "",
      d.syncedAt ? "yes" : "no",
      d.createdAt.slice(0, 10),
      d.updatedAt.slice(0, 10),
    ])
    return { csv: toCsv(DEAL_CSV_HEADERS, rows), count: rows.length }
  },
}
