// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
export class HttpError extends Error {
  constructor(
    public status: number,
    public code: string,
    message: string,
    public details?: unknown,
  ) {
    super(message)
    this.name = "HttpError"
  }
}

export const badRequest = (message: string, details?: unknown) => new HttpError(400, "bad_request", message, details)
export const unauthorized = (message = "Authentication required") => new HttpError(401, "unauthorized", message)
export const forbidden = (message = "You do not have permission to perform this action") =>
  new HttpError(403, "forbidden", message)
export const notFound = (what = "Resource") => new HttpError(404, "not_found", `${what} not found`)
export const conflict = (message: string, details?: unknown) => new HttpError(409, "conflict", message, details)
export const unprocessable = (message: string, details?: unknown) =>
  new HttpError(422, "unprocessable", message, details)

/** Throws 404 when the value is null/undefined, otherwise narrows it. */
export function must<T>(value: T | null | undefined, what: string): T {
  if (value === null || value === undefined) throw notFound(what)
  return value
}
