// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../db/index"

export interface AccountRef {
  id: string
  name: string
  domain: string
  tier: string
  score: number
  industry: string
}
export interface ContactRef {
  id: string
  firstName: string
  lastName: string
  title: string
  email: string
  accountId: string
}

/** Attaches `account` summaries to items that carry an accountId. */
export async function withAccounts<T extends { accountId: string }>(orgId: string, items: T[]) {
  const ids = [...new Set(items.map((i) => i.accountId))]
  const accounts = ids.length ? await db.accounts.find(orgId, { id: { in: ids } }) : []
  const map = new Map(accounts.map((a) => [a.id, a]))
  return items.map((i) => {
    const a = map.get(i.accountId)
    const account: AccountRef | null = a
      ? { id: a.id, name: a.name, domain: a.domain, tier: a.tier, score: a.score, industry: a.industry }
      : null
    return { ...i, account }
  })
}

/** Attaches `contact` summaries to items with an optional contactId. */
export async function withContacts<T extends { contactId?: string }>(orgId: string, items: T[]) {
  const ids = [...new Set(items.map((i) => i.contactId).filter((x): x is string => !!x))]
  const contacts = ids.length ? await db.contacts.find(orgId, { id: { in: ids } }) : []
  const map = new Map(contacts.map((c) => [c.id, c]))
  return items.map((i) => {
    const c = i.contactId ? map.get(i.contactId) : undefined
    const contact: ContactRef | null = c
      ? { id: c.id, firstName: c.firstName, lastName: c.lastName, title: c.title, email: c.email, accountId: c.accountId }
      : null
    return { ...i, contact }
  })
}
