// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
// Portable (Node ≥ 20 and browsers): uses the global Web Crypto RNG.
const ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

/** Random alphanumeric string of the given length. */
export function randomToken(length: number) {
  const bytes = globalThis.crypto.getRandomValues(new Uint8Array(length))
  return Array.from(bytes, (b) => ALPHABET[b % ALPHABET.length]).join("")
}

export const randomHex = (bytes: number) =>
  Array.from(globalThis.crypto.getRandomValues(new Uint8Array(bytes)), (b) => b.toString(16).padStart(2, "0")).join("")

export const newId = (prefix: string) => `${prefix}_${randomToken(8)}`

export const nowIso = () => new Date().toISOString()

export const DAY_MS = 86_400_000
