// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import type { Role } from "../domain/types"
import { forbidden, unauthorized } from "./errors"

export interface AuthContext {
  userId: string
  orgId: string
  role: Role
  via: "jwt" | "apiKey"
  scopes?: string[]
}

const RANK: Record<Role, number> = { viewer: 0, member: 1, admin: 2, owner: 3 }

/** Every role at or above the given one. */
export const atLeast = (role: Role): Role[] => (Object.keys(RANK) as Role[]).filter((r) => RANK[r] >= RANK[role])

export function assertRole(auth: AuthContext | undefined, roles: Role[]) {
  if (!auth) throw unauthorized()
  if (!roles.includes(auth.role)) throw forbidden()
}
