// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
/**
 * Transport-agnostic route runtime: route definitions, validation, auth/role checks and the
 * response envelope. The Express binding lives in ./http.ts; the frontend's mock mode runs the
 * same definitions in the browser (see frontend/src/mock-api). Keep this file free of Node/Express imports.
 */
import { z, type ZodType } from "zod"
import type { Page } from "../db/repository"
import type { Role } from "../domain/types"
import { authenticateRequest } from "../middleware/auth"
import { badRequest, HttpError, unauthorized } from "./errors"
import { assertRole, atLeast, type AuthContext } from "./roles"

export type Method = "get" | "post" | "put" | "patch" | "delete"
export type AuthMode = "user" | "apiKey" | "none"

export interface RouteContext<B, Q, P> {
  body: B
  query: Q
  params: P
  auth: AuthContext
  /** Convenience: auth.orgId */
  orgId: string
}

export interface RouteDef<B, Q, P> {
  method: Method
  path: string
  summary: string
  description?: string
  /** "user" (JWT, default) · "apiKey" (x-api-key) · "none" (public) */
  auth?: AuthMode
  /** Allowed roles. Defaults: GET → everyone, writes → member and above. */
  roles?: Role[]
  /** Required API key scope when auth = "apiKey". */
  scope?: string
  body?: ZodType<B>
  query?: ZodType<Q>
  params?: ZodType<P>
  status?: number
  /** OpenAPI response content type (default application/json). */
  produces?: string
  handler: (ctx: RouteContext<B, Q, P>) => unknown | Promise<unknown>
}

/** Wrap a repository page so the response gets a `meta` block. */
export class PageResult<T> {
  constructor(public page: Page<T>) {}
}
export const paged = <T>(page: Page<T>) => new PageResult(page)

/** Return from a handler to send a file download instead of JSON. */
export class FileResult {
  constructor(
    public filename: string,
    public content: string,
    public contentType = "text/csv",
  ) {}
}
export const fileResponse = (filename: string, content: string, contentType = "text/csv") =>
  new FileResult(filename, content, contentType)

export interface RegisteredRoute {
  tag: string
  fullPath: string
  def: RouteDef<unknown, unknown, unknown>
}
export const routeRegistry: RegisteredRoute[] = []

export interface RouteInput {
  params: unknown
  query: unknown
  body: unknown
  headers: Record<string, string | undefined>
}

export type RouteOutput =
  | { status: number; json: unknown }
  | { status: 204 }
  | { status: number; file: FileResult }

function parse<T>(schema: ZodType<T> | undefined, value: unknown, where: string): T {
  if (!schema) return (value ?? {}) as T
  const result = schema.safeParse(value ?? {})
  if (!result.success) {
    throw badRequest(`Invalid ${where}`, z.flattenError(result.error as z.ZodError<Record<string, unknown>>))
  }
  return result.data
}

/** Runs a route definition end to end. Throws HttpError for client errors. */
export async function executeRoute(def: RouteDef<unknown, unknown, unknown>, input: RouteInput): Promise<RouteOutput> {
  const mode = def.auth ?? "user"
  let auth: AuthContext | undefined
  if (mode !== "none") {
    auth = await authenticateRequest(mode, input.headers, def.scope)
    assertRole(auth, def.roles ?? (def.method === "get" ? atLeast("viewer") : atLeast("member")))
  }
  const ctx: RouteContext<unknown, unknown, unknown> = {
    body: parse(def.body, input.body, "request body"),
    query: parse(def.query, input.query, "query parameters"),
    params: parse(def.params, input.params, "path parameters"),
    get auth() {
      if (!auth) throw unauthorized()
      return auth
    },
    get orgId() {
      if (!auth) throw unauthorized()
      return auth.orgId
    },
  }
  const result = await def.handler(ctx)
  if (result instanceof FileResult) return { status: 200, file: result }
  if (result === undefined) return { status: 204 }
  const status = def.status ?? (def.method === "post" ? 201 : 200)
  if (result instanceof PageResult) {
    const { items, total, page, pageSize } = result.page
    return { status: def.method === "post" ? 200 : status, json: { data: items, meta: { total, page, pageSize } } }
  }
  return { status, json: { data: result } }
}

/** Error → `{ status, json }` envelope (non-HttpErrors are rethrown). */
export function errorOutput(err: unknown): { status: number; json: unknown } {
  if (err instanceof HttpError) {
    return { status: err.status, json: { error: { code: err.code, message: err.message, details: err.details } } }
  }
  throw err
}

// ---------- Shared schemas ----------
export const idParams = z.object({ id: z.string().min(1) })

export const listQuery = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(1000).default(25),
  q: z.string().trim().optional(),
  sort: z
    .string()
    .regex(/^[a-zA-Z_]+:(asc|desc)$/, "sort must look like field:asc|desc")
    .optional(),
})

export function parseSort<F extends string>(sort: string | undefined, allowed: readonly F[], fallback: { field: F; dir: "asc" | "desc" }) {
  if (!sort) return fallback
  const [field, dir] = sort.split(":") as [F, "asc" | "desc"]
  if (!allowed.includes(field)) throw badRequest(`Cannot sort by "${field}". Allowed: ${allowed.join(", ")}`)
  return { field, dir }
}

/** Accepts "a,b" or repeated params and returns string[] | undefined. */
export const csvList = z
  .union([z.string(), z.array(z.string())])
  .optional()
  .transform((v) => (v === undefined ? undefined : (Array.isArray(v) ? v : v.split(",")).map((s) => s.trim()).filter(Boolean)))

export const boolQuery = z
  .enum(["true", "false"])
  .optional()
  .transform((v) => (v === undefined ? undefined : v === "true"))

export const idList = z.object({ ids: z.array(z.string().min(1)).min(1).max(1000) })
