// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { config } from "../config"
import type { Account, Contact, Deal, InboxMessage, Signal } from "../domain/types"
import { logger } from "../lib/logger"

const sleep = (ms: number) => new Promise((r) => setTimeout(r, config.isTest ? 0 : ms))

// ---------------------------------------------------------------------------
// Adapter interfaces. Real vendor implementations (Clearbit, HubSpot, SES,
// Anthropic, …) implement these and are selected by the *_PROVIDER env vars.
// ---------------------------------------------------------------------------

export interface EnrichmentResult {
  patch: Partial<Pick<Account, "employees" | "revenue" | "technologies" | "city" | "description" | "linkedinUrl" | "industry" | "fundingStage">>
  sources: string[]
}

export interface EnrichmentProvider {
  enrichAccount(account: Account, waterfall: string[]): Promise<EnrichmentResult>
  findEmail(contact: Contact, domain: string): Promise<{ email: string | null; status: Contact["emailStatus"] }>
}

export interface CrmProvider {
  readonly name: string
  pushDeal(deal: Deal): Promise<{ crmId: string }>
}

export interface EmailProvider {
  send(input: { from?: string; to: string; subject: string; body: string }): Promise<{ messageId: string }>
}

export interface LlmProvider {
  draftOutreach(input: { account: Account; contact: Contact; signal?: Signal; senderName: string }): Promise<{ subject: string; body: string }>
  suggestReply(input: { message: InboxMessage; contact?: Contact; senderName: string }): Promise<string>
}

export interface VendorConnectionTester {
  test(integrationKey: string, apiKey: string): Promise<{ ok: boolean; message?: string }>
}

// ---------------------------------------------------------------------------
// Mock implementations (deterministic-ish, offline)
// ---------------------------------------------------------------------------

const TECH_POOL = ["Snowflake", "Segment", "HubSpot", "Salesforce", "Outreach", "Gong"]

const mockEnrichment: EnrichmentProvider = {
  async enrichAccount(account, waterfall) {
    await sleep(800)
    const addTech = TECH_POOL.find((t) => !account.technologies.includes(t))
    return {
      patch: {
        employees: account.employees || 50,
        technologies: addTech ? [...account.technologies, addTech] : account.technologies,
        city: account.city || "San Francisco",
        description: account.description || `${account.name} is a ${account.industry} company headquartered in ${account.country}.`,
        linkedinUrl: account.linkedinUrl || `https://linkedin.com/company/${account.domain.split(".")[0]}`,
      },
      sources: waterfall.length ? waterfall.slice(0, 2) : ["Clearbit"],
    }
  },
  async findEmail(contact, domain) {
    await sleep(300)
    if (contact.email && contact.emailStatus !== "missing") {
      // Deterministic verification outcome based on the address.
      const bad = [...contact.email].reduce((h, c) => h + c.charCodeAt(0), 0) % 9 === 0
      return { email: contact.email, status: bad ? "invalid" : "verified" }
    }
    const local = `${contact.firstName}.${contact.lastName}`.toLowerCase().normalize("NFD").replace(/[^a-z.]/g, "")
    return { email: `${local}@${domain}`, status: "verified" }
  },
}

const mockCrm = (name: string): CrmProvider => ({
  name,
  async pushDeal(deal) {
    return { crmId: deal.crmId ?? `${name.slice(0, 2).toUpperCase()}-${Math.floor(100000 + Math.random() * 899999)}` }
  },
})

const mockEmail: EmailProvider = {
  async send(input) {
    logger.debug({ to: input.to, subject: input.subject }, "mock email sent")
    return { messageId: `mock-${Date.now()}` }
  },
}

const OPENERS = [
  "Quick thought after seeing your team's recent activity",
  "Noticed some momentum at your company this week",
  "Timely idea given what your team is working on",
]

const mockLlm: LlmProvider = {
  async draftOutreach({ account, contact, signal, senderName }) {
    await sleep(600)
    if (signal) {
      const title = signal.title.charAt(0).toLowerCase() + signal.title.slice(1)
      return {
        subject: `${account.name}: ${signal.title.toLowerCase()}`,
        body: `Hi ${contact.firstName},\n\nSaw that ${account.name} ${title} — ${signal.detail.toLowerCase()}. Teams in ${account.industry} at your stage often use this moment to tighten how they prioritize accounts.\n\nWe help ${contact.department} leaders route the right accounts to reps automatically using live fit + intent scoring. Open to a quick 15-minute look next week?\n\nBest,\n${senderName}`,
      }
    }
    return {
      subject: `${OPENERS[Math.floor(Math.random() * OPENERS.length)]}, ${contact.firstName}`,
      body: `Hi ${contact.firstName},\n\n${account.name} looks like it's investing in growth right now. Most ${account.industry} teams we work with see reps waste ~30% of their week on accounts that aren't ready to buy.\n\nWe fix that by scoring every account on fit + live intent and routing only the hot ones. Worth comparing notes for 15 minutes?\n\nCheers,\n${senderName}`,
    }
  },
  async suggestReply({ message, contact, senderName }) {
    await sleep(500)
    const name = contact?.firstName ?? "there"
    switch (message.sentiment) {
      case "positive":
        return `Hi ${name},\n\nGreat to hear! Here's my calendar — pick any slot that works this week: https://cal.example.com/${senderName.toLowerCase().split(" ")[0]}\n\nI'll send over a short agenda once it's booked.\n\nBest,\n${senderName}`
      case "negative":
        return `Hi ${name},\n\nUnderstood — I've removed you from our outreach. Apologies for the interruption.\n\nBest,\n${senderName}`
      case "ooo":
        return `Hi ${name},\n\nNo rush at all — I'll follow up when you're back.\n\nBest,\n${senderName}`
      default:
        return `Hi ${name},\n\nThanks for the pointer! Would you mind making a quick intro, or should I reach out directly?\n\nBest,\n${senderName}`
    }
  },
}

const mockTester: VendorConnectionTester = {
  async test(_key, apiKey) {
    await sleep(700)
    return apiKey.length >= 8 ? { ok: true } : { ok: false, message: "API key looks invalid" }
  },
}

function warnUnimplemented(kind: string, value: string) {
  if (value !== "mock") logger.warn(`${kind}=${value} adapter not implemented yet; using mock`)
}

warnUnimplemented("ENRICHMENT_PROVIDER", config.ENRICHMENT_PROVIDER)
warnUnimplemented("CRM_PROVIDER", config.CRM_PROVIDER)
warnUnimplemented("EMAIL_PROVIDER", config.EMAIL_PROVIDER)
warnUnimplemented("LLM_PROVIDER", config.LLM_PROVIDER)

export const providers = {
  enrichment: mockEnrichment,
  crm: mockCrm(config.CRM_PROVIDER === "mock" ? "HubSpot" : config.CRM_PROVIDER),
  email: mockEmail,
  llm: mockLlm,
  connections: mockTester,
}
