// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import rateLimit from "@/mock-api/shims/express-rate-limit"
import { z } from "zod"
import { config } from "../../config"
import { createModule } from "../../lib/http"
import { authService } from "../organization/service"

export const authModule = createModule("Auth", "/auth")
const { route, router } = authModule

// Stricter limit on credential endpoints.
router.use(
  ["/login", "/register", "/accept-invite"],
  rateLimit({ windowMs: 15 * 60_000, limit: config.isProd ? 20 : 1000, standardHeaders: true, legacyHeaders: false }),
)

const password = z.string().min(8, "Password must be at least 8 characters").max(200)

route({
  method: "post",
  path: "/register",
  summary: "Create an organization and its owner account",
  auth: "none",
  body: z.object({
    orgName: z.string().trim().min(1).max(120),
    domain: z.string().trim().min(3).max(253),
    name: z.string().trim().min(1).max(120),
    email: z.string().trim().email(),
    password,
  }),
  handler: ({ body }) => authService.register(body),
})

route({
  method: "post",
  path: "/login",
  summary: "Sign in with email and password",
  auth: "none",
  status: 200,
  body: z.object({ email: z.string().trim().email(), password: z.string().min(1) }),
  handler: ({ body }) => authService.login(body.email, body.password),
})

route({
  method: "post",
  path: "/accept-invite",
  summary: "Accept a team invitation and set a password",
  auth: "none",
  status: 200,
  body: z.object({ token: z.string().min(10), password, name: z.string().trim().min(1).optional() }),
  handler: ({ body }) => authService.acceptInvite(body.token, body.password, body.name),
})

route({
  method: "get",
  path: "/me",
  summary: "Current user and organization",
  handler: ({ orgId, auth }) => authService.me(orgId, auth.userId),
})

route({
  method: "post",
  path: "/logout",
  summary: "Sign out (stateless JWT — client discards the token)",
  status: 204,
  roles: ["owner", "admin", "member", "viewer"],
  handler: () => undefined,
})

route({
  method: "post",
  path: "/change-password",
  summary: "Change the current user's password",
  status: 204,
  roles: ["owner", "admin", "member", "viewer"],
  body: z
    .object({ currentPassword: z.string().min(1), newPassword: password })
    .refine((b) => b.currentPassword !== b.newPassword, { message: "New password must differ", path: ["newPassword"] }),
  handler: async ({ orgId, auth, body }) => {
    await authService.changePassword(orgId, auth.userId, body.currentPassword, body.newPassword)
  },
})
