// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { db } from "../../db/index"
import { createModule } from "../../lib/http"

export const searchModule = createModule("Search", "/search")
const { route } = searchModule

const recent = { field: "updatedAt" as const, dir: "desc" as const }

export const searchService = {
  async search(orgId: string, rawQ: string, limit: number) {
    const q = rawQ.trim()
    const opts = { page: 1, pageSize: limit, sort: recent }
    const s = <F extends string>(fields: F[]) => (q ? { q, fields } : undefined)
    // "Jane Doe" should match first + last name together.
    const [first, ...restParts] = q.split(/\s+/)
    const rest = restParts.join(" ")
    const [accounts, contacts, deals, sequences] = await Promise.all([
      db.accounts.list(orgId, { ...opts, search: s(["name", "domain"]) }),
      rest
        ? db.contacts.list(orgId, { ...opts, where: { firstName: { contains: first! }, lastName: { contains: rest } } })
        : db.contacts.list(orgId, { ...opts, search: s(["firstName", "lastName", "email", "title"]) }),
      db.deals.list(orgId, { ...opts, search: s(["name"]) }),
      db.sequences.list(orgId, { ...opts, search: s(["name"]) }),
    ])
    return {
      accounts: accounts.items.map((a) => ({ id: a.id, name: a.name, domain: a.domain })),
      contacts: contacts.items.map((c) => ({
        id: c.id,
        name: `${c.firstName} ${c.lastName}`.trim(),
        title: c.title,
        email: c.email,
        accountId: c.accountId,
      })),
      deals: deals.items.map((d) => ({ id: d.id, name: d.name, accountId: d.accountId })),
      sequences: sequences.items.map((q) => ({ id: q.id, name: q.name })),
    }
  },
}

route({
  method: "get",
  path: "/",
  summary: "Global search across accounts, contacts, deals and sequences",
  description: "Case-insensitive contains match. An empty query returns the most recently updated items.",
  query: z.object({
    q: z.string().max(200).default(""),
    limit: z.coerce.number().int().min(1).max(25).default(8),
  }),
  handler: ({ orgId, query }) => searchService.search(orgId, query.q, query.limit),
})
