// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { config } from "../config"
import type {
  Activity,
  AgentRun,
  ApiKeyRecord,
  AppNotification,
  Account,
  Contact,
  Deal,
  Enrollment,
  IcpConfig,
  InboxMessage,
  Integration,
  Mailbox,
  Organization,
  OutreachDraft,
  PlaybookRule,
  Sequence,
  Signal,
  UserPreferences,
  UserRecord,
} from "../domain/types"
import { JsonRepository } from "./json/json-repository"
import { createPostgresRepository } from "./postgres/postgres-repository"
import type { Repository } from "./repository"

type IcpRecord = IcpConfig & { id: string }

function collection<T extends { id: string }>(name: string, idPrefix: string): Repository<T> {
  switch (config.DB_DRIVER) {
    case "json":
      return new JsonRepository<T>(name, config.dataDir, idPrefix)
    case "postgres":
      return createPostgresRepository<T>(name)
  }
}

/** Every collection the API persists. File names in db/ match the keys' snake_case names. */
export const db = {
  organizations: collection<Organization>("organizations", "org"),
  users: collection<UserRecord>("users", "usr"),
  userPreferences: collection<UserPreferences>("user_preferences", "pref"),
  apiKeys: collection<ApiKeyRecord>("api_keys", "key"),
  accounts: collection<Account>("accounts", "acc"),
  contacts: collection<Contact>("contacts", "con"),
  signals: collection<Signal>("signals", "sig"),
  icp: collection<IcpRecord>("icp_config", "icp"),
  playbooks: collection<PlaybookRule>("playbooks", "rule"),
  runs: collection<AgentRun>("agent_runs", "run"),
  drafts: collection<OutreachDraft>("drafts", "drf"),
  sequences: collection<Sequence>("sequences", "seq"),
  enrollments: collection<Enrollment>("enrollments", "enr"),
  mailboxes: collection<Mailbox>("mailboxes", "mb"),
  inbox: collection<InboxMessage>("inbox_messages", "msg"),
  deals: collection<Deal>("deals", "deal"),
  activities: collection<Activity>("activities", "act"),
  integrations: collection<Integration>("integrations", "int"),
  notifications: collection<AppNotification>("notifications", "ntf"),
}

export type Db = typeof db

/** Organizations are the tenant root: their orgId is their own id. */
export async function truncateAll() {
  for (const repo of Object.values(db)) await repo.truncate()
}
