// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import type { ID, Stored } from "../domain/types"

/**
 * Storage-agnostic query language. Kept deliberately small so it maps 1:1 onto SQL
 * (eq / IN / comparisons / ILIKE / IS NULL) when the Postgres driver is added.
 */
export type FieldCondition<V> =
  | V
  | null
  | {
      eq?: V | null
      ne?: V | null
      in?: V[]
      nin?: V[]
      gt?: V
      gte?: V
      lt?: V
      lte?: V
      /** true → field is not null/undefined; false → field is null/undefined */
      exists?: boolean
      /** case-insensitive substring match (strings) or membership (arrays) */
      contains?: string
    }

export type Where<T> = { [K in keyof T]?: FieldCondition<T[K] extends (infer U)[] ? U : T[K]> } & {
  $or?: Where<T>[]
}

export interface Sort<T> {
  field: keyof T & string
  dir: "asc" | "desc"
}

export interface ListQuery<T> {
  where?: Where<T>
  /** Free-text search across the given fields (case-insensitive). */
  search?: { q: string; fields: (keyof T & string)[] }
  sort?: Sort<T> | Sort<T>[]
  page?: number
  pageSize?: number
}

export interface Page<T> {
  items: T[]
  total: number
  page: number
  pageSize: number
}

export type CreateInput<T extends { id: ID }> = Omit<T, "id" | "orgId" | "createdAt" | "updatedAt"> & {
  id?: ID
  createdAt?: string
  updatedAt?: string
}

/**
 * Tenant-scoped repository. Every method takes the orgId so that no service can
 * accidentally read or write across organizations.
 */
export interface Repository<T extends { id: ID }> {
  readonly name: string
  list(orgId: ID, query?: ListQuery<Stored<T>>): Promise<Page<Stored<T>>>
  find(orgId: ID, where?: Where<Stored<T>>, sort?: Sort<Stored<T>> | Sort<Stored<T>>[]): Promise<Stored<T>[]>
  findOne(orgId: ID, where: Where<Stored<T>>): Promise<Stored<T> | null>
  get(orgId: ID, id: ID): Promise<Stored<T> | null>
  count(orgId: ID, where?: Where<Stored<T>>): Promise<number>
  create(orgId: ID, data: CreateInput<T>): Promise<Stored<T>>
  createMany(orgId: ID, data: CreateInput<T>[]): Promise<Stored<T>[]>
  update(orgId: ID, id: ID, patch: Partial<T>): Promise<Stored<T>>
  /** Applies a patch to each matching record; returns the updated records. */
  updateMany(orgId: ID, where: Where<Stored<T>>, patch: Partial<T> | ((r: Stored<T>) => Partial<T>)): Promise<Stored<T>[]>
  remove(orgId: ID, id: ID): Promise<boolean>
  removeMany(orgId: ID, where: Where<Stored<T>>): Promise<number>
  /** Cross-tenant lookup — only for auth (login by email, API key by hash). */
  findGlobal(where: Where<Stored<T>>): Promise<Stored<T> | null>
  /** Removes every record (all tenants). Used by reset/bootstrap scripts. */
  truncate(): Promise<void>
}
