// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { withAccounts, withContacts } from "../../lib/expand"
import { boolQuery, createModule, csvList, idParams, listQuery, paged, parseSort } from "../../lib/http"
import { activityService } from "../activities/service"
import { DEAL_SORT_FIELDS, pipelineService } from "./service"

export const pipelineModule = createModule("Pipeline", "/deals")
const { route } = pipelineModule

const stage = z.enum(["discovery", "qualified", "demo", "proposal", "negotiation", "closed_won", "closed_lost"])

const dealFields = z.object({
  name: z.string().trim().min(1).max(200),
  accountId: z.string().min(1),
  contactId: z.string().optional(),
  ownerId: z.string().optional(),
  stage,
  amount: z.coerce.number().min(0),
  probability: z.coerce.number().min(0).max(100).optional(),
  closeDate: z.string().min(8),
  source: z.string().max(100).optional(),
  notes: z.string().max(10_000).optional(),
})

const filters = listQuery.extend({
  ownerId: z.string().optional(),
  accountId: z.string().optional(),
  stage: csvList.pipe(z.array(stage).optional()),
  hideClosed: boolQuery,
  source: z.string().optional(),
})

route({
  method: "get",
  path: "/",
  summary: "List deals (with account + contact summaries)",
  description: "Use pageSize up to 1000 for the kanban board. Sort fields: " + DEAL_SORT_FIELDS.join(", "),
  query: filters,
  handler: async ({ orgId, query }) => {
    const sort = parseSort(query.sort, DEAL_SORT_FIELDS, { field: "updatedAt", dir: "desc" })
    const page = await pipelineService.list(orgId, query, query.page, query.pageSize, sort)
    return paged({ ...page, items: await withContacts(orgId, await withAccounts(orgId, page.items)) })
  },
})

route({
  method: "get",
  path: "/stats",
  summary: "Pipeline stats (open, weighted, won this quarter, win rate, by stage)",
  query: filters.pick({ ownerId: true, accountId: true, q: true }),
  handler: ({ orgId, query }) => pipelineService.stats(orgId, query),
})

route({
  method: "post",
  path: "/",
  summary: "Create a deal",
  body: dealFields,
  handler: ({ orgId, auth, body }) => pipelineService.create(orgId, auth.userId, body),
})

route({
  method: "post",
  path: "/sync-crm",
  summary: "Push unsynced deals to the connected CRM",
  status: 200,
  handler: ({ orgId }) => pipelineService.syncCrm(orgId),
})

route({
  method: "get",
  path: "/:id",
  summary: "Get a deal",
  params: idParams,
  handler: async ({ orgId, params }) => {
    const d = await pipelineService.get(orgId, params.id)
    return (await withContacts(orgId, await withAccounts(orgId, [d])))[0]
  },
})

route({
  method: "patch",
  path: "/:id",
  summary: "Update a deal (stage changes go through the move logic)",
  params: idParams,
  body: dealFields.omit({ accountId: true }).partial().extend({ contactId: z.string().nullable().optional() }),
  handler: ({ orgId, auth, params, body }) => {
    const { contactId, ...rest } = body
    // null clears the contact; omitted leaves it unchanged.
    const patch = contactId === undefined ? rest : { ...rest, contactId: contactId ?? undefined }
    return pipelineService.update(orgId, auth.userId, params.id, patch)
  },
})

route({
  method: "post",
  path: "/:id/move",
  summary: "Move a deal to another stage",
  status: 200,
  params: idParams,
  body: z.object({ stage }),
  handler: ({ orgId, auth, params, body }) => pipelineService.move(orgId, auth.userId, params.id, body.stage),
})

route({
  method: "delete",
  path: "/:id",
  summary: "Delete a deal",
  params: idParams,
  handler: ({ orgId, params }) => pipelineService.remove(orgId, params.id),
})

route({
  method: "get",
  path: "/:id/activities",
  summary: "Activity for a deal",
  params: idParams,
  query: z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(200).default(20) }),
  handler: async ({ orgId, params, query }) =>
    paged(await activityService.list(orgId, { dealId: params.id, page: query.page, pageSize: query.pageSize })),
})
