// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import type { Where } from "../../db/repository"
import { DEAL_STAGE_LABEL, DEAL_STAGES } from "../../domain/constants"
import type { Deal, DealStage, Stored } from "../../domain/types"
import { bus } from "../../events/bus"
import { badRequest, notFound } from "../../lib/errors"
import { nowIso } from "../../lib/ids"
import { providers } from "../../providers/index"
import { activityService } from "../activities/service"
import { accountService } from "../accounts/service"
import { notificationService } from "../notifications/service"

export const DEAL_SORT_FIELDS = ["name", "amount", "probability", "closeDate", "stage", "updatedAt", "createdAt"] as const

export interface DealFilters {
  ownerId?: string
  accountId?: string
  stage?: DealStage[]
  hideClosed?: boolean
  source?: string
  q?: string
}

export const probabilityFor = (stage: DealStage) => DEAL_STAGES.find((s) => s.id === stage)?.probability ?? 10
const isClosed = (stage: DealStage) => stage === "closed_won" || stage === "closed_lost"

export function dealWhere(f: DealFilters): Where<Stored<Deal>> {
  const stages = f.hideClosed
    ? (f.stage?.length ? f.stage : DEAL_STAGES.map((s) => s.id)).filter((s) => !isClosed(s))
    : f.stage
  return {
    ownerId: f.ownerId,
    accountId: f.accountId,
    stage: stages?.length ? { in: stages } : undefined,
    source: f.source ? { contains: f.source } : undefined,
    $or: f.q ? [{ name: { contains: f.q } }, { crmId: { contains: f.q } }] : undefined,
  }
}

export type DealCreateInput = Pick<Deal, "name" | "accountId" | "amount" | "stage" | "closeDate"> & Partial<Omit<Deal, "id" | "createdAt" | "updatedAt">>

export const pipelineService = {
  async list(orgId: string, f: DealFilters, page: number, pageSize: number, sort: { field: (typeof DEAL_SORT_FIELDS)[number]; dir: "asc" | "desc" }) {
    let where = dealWhere(f)
    if (f.q) {
      // Also match by account name / domain.
      const accounts = await db.accounts.find(orgId, { $or: [{ name: { contains: f.q } }, { domain: { contains: f.q } }] })
      where = { ...where, $or: [...(where.$or ?? []), { accountId: { in: accounts.map((a) => a.id) } }] }
    }
    if (sort.field === "stage") {
      // Sort by pipeline order rather than alphabetically.
      const order = DEAL_STAGES.map((s) => s.id)
      const all = await db.deals.find(orgId, where, { field: "updatedAt", dir: "desc" })
      const dir = sort.dir === "asc" ? 1 : -1
      all.sort((a, b) => (order.indexOf(a.stage) - order.indexOf(b.stage)) * dir)
      return { items: all.slice((page - 1) * pageSize, page * pageSize), total: all.length, page, pageSize }
    }
    return db.deals.list(orgId, { where, sort, page, pageSize })
  },

  async get(orgId: string, id: string) {
    const d = await db.deals.get(orgId, id)
    if (!d) throw notFound("Deal")
    return d
  },

  async create(orgId: string, actorId: string, input: DealCreateInput) {
    const account = await db.accounts.get(orgId, input.accountId)
    if (!account) throw badRequest("Account not found")
    if (input.contactId && !(await db.contacts.get(orgId, input.contactId))) throw badRequest("Contact not found")
    const deal = await db.deals.create(orgId, {
      ownerId: account.ownerId ?? actorId,
      probability: probabilityFor(input.stage),
      source: "Manual",
      notes: "",
      ...input,
    })
    if (["new", "researching", "engaged"].includes(account.stage)) {
      await accountService.update(orgId, account.id, { stage: "opportunity" }, "Deal created")
    }
    await activityService.log(orgId, {
      accountId: deal.accountId,
      dealId: deal.id,
      type: "stage_change",
      title: `Deal created: ${deal.name}`,
      actorId: actorId === "agent" ? "agent" : actorId,
    })
    return deal
  },

  async update(orgId: string, actorId: string, id: string, patch: Partial<Deal>) {
    const cur = await this.get(orgId, id)
    if (patch.stage && patch.stage !== cur.stage) {
      await this.move(orgId, actorId, id, patch.stage)
      delete patch.stage
      if (patch.probability === undefined) delete patch.probability
    }
    // Any edit invalidates the CRM sync marker.
    return db.deals.update(orgId, id, { ...patch, syncedAt: undefined })
  },

  async move(orgId: string, actorId: string, id: string, stage: DealStage) {
    const d = await this.get(orgId, id)
    if (d.stage === stage) return d
    const updated = await db.deals.update(orgId, id, {
      stage,
      probability: probabilityFor(stage),
      syncedAt: undefined,
      ...(isClosed(stage) ? { closeDate: nowIso() } : {}),
    })
    if (stage === "closed_won") {
      await accountService.update(orgId, d.accountId, { stage: "customer" }, "Deal closed won")
      await notificationService.notify(orgId, {
        kind: "deal",
        title: "🎉 Deal won",
        body: `${d.name} closed for $${d.amount.toLocaleString("en-US")}`,
        href: `/pipeline?deal=${d.id}`,
      })
    }
    await activityService.log(orgId, {
      accountId: d.accountId,
      dealId: id,
      type: "stage_change",
      title: `${d.name}: ${DEAL_STAGE_LABEL[d.stage]} → ${DEAL_STAGE_LABEL[stage]}`,
      actorId,
    })
    await bus.publish("deal.stage_changed", { orgId, dealId: id, from: d.stage, to: stage })
    return updated
  },

  async remove(orgId: string, id: string) {
    await this.get(orgId, id)
    await db.deals.remove(orgId, id)
  },

  async syncCrm(orgId: string) {
    const crm = await db.integrations.findOne(orgId, { category: "crm", connected: true })
    if (!crm) throw badRequest("Connect a CRM integration (HubSpot, Attio or Salesforce) first")
    const unsynced = await db.deals.find(orgId, { syncedAt: { exists: false } })
    const now = nowIso()
    for (const d of unsynced) {
      const { crmId } = await providers.crm.pushDeal(d)
      await db.deals.update(orgId, d.id, { crmId, syncedAt: now })
    }
    await db.integrations.update(orgId, crm.id, { lastSyncAt: now, status: "ok" })
    return { pushed: unsynced.length, crm: crm.name, syncedAt: now }
  },

  async stats(orgId: string, f: DealFilters) {
    const deals = await db.deals.find(orgId, { ...dealWhere({ ...f, hideClosed: false }) })
    const open = deals.filter((d) => !isClosed(d.stage))
    const won = deals.filter((d) => d.stage === "closed_won")
    const lost = deals.filter((d) => d.stage === "closed_lost")
    const quarterStart = new Date()
    quarterStart.setMonth(Math.floor(quarterStart.getMonth() / 3) * 3, 1)
    quarterStart.setHours(0, 0, 0, 0)
    const wonQuarter = won.filter((d) => new Date(d.closeDate) >= quarterStart)
    return {
      openPipeline: open.reduce((s, d) => s + d.amount, 0),
      openCount: open.length,
      weightedPipeline: Math.round(open.reduce((s, d) => s + (d.amount * d.probability) / 100, 0)),
      wonThisQuarter: wonQuarter.reduce((s, d) => s + d.amount, 0),
      wonThisQuarterCount: wonQuarter.length,
      winRate: won.length + lost.length ? Math.round((won.length / (won.length + lost.length)) * 1000) / 10 : 0,
      closedCount: won.length + lost.length,
      avgDealSize: deals.length ? Math.round(deals.reduce((s, d) => s + d.amount, 0) / deals.length) : 0,
      unsynced: deals.filter((d) => !d.syncedAt).length,
      byStage: DEAL_STAGES.map((s) => {
        const inStage = deals.filter((d) => d.stage === s.id)
        return { stage: s.id, label: s.label, count: inStage.length, amount: inStage.reduce((sum, d) => sum + d.amount, 0) }
      }),
    }
  },
}
