// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import type { ID, Stored } from "../../domain/types"
import { notFound } from "../../lib/errors"
import { newId, nowIso } from "../../lib/ids"
import type { CreateInput, FieldCondition, ListQuery, Page, Repository, Sort, Where } from "../repository"

const isObj = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v)

function matchCondition(value: unknown, cond: FieldCondition<unknown>): boolean {
  const values = Array.isArray(value) ? value : [value]
  if (!isObj(cond)) {
    return Array.isArray(value) ? value.includes(cond) : (value ?? null) === cond
  }
  const c = cond as Exclude<FieldCondition<unknown>, null | undefined> & Record<string, unknown>
  if ("eq" in c && !(Array.isArray(value) ? value.includes(c.eq) : (value ?? null) === c.eq)) return false
  if ("ne" in c && (value ?? null) === c.ne) return false
  if (c.in && !values.some((v) => (c.in as unknown[]).includes(v))) return false
  if (c.nin && values.some((v) => (c.nin as unknown[]).includes(v))) return false
  if (c.exists !== undefined && (value !== null && value !== undefined) !== c.exists) return false
  const cmp = value as string | number
  if (c.gt !== undefined && !(cmp > (c.gt as typeof cmp))) return false
  if (c.gte !== undefined && !(cmp >= (c.gte as typeof cmp))) return false
  if (c.lt !== undefined && !(cmp < (c.lt as typeof cmp))) return false
  if (c.lte !== undefined && !(cmp <= (c.lte as typeof cmp))) return false
  if (c.contains !== undefined) {
    const needle = String(c.contains).toLowerCase()
    if (!values.some((v) => String(v ?? "").toLowerCase().includes(needle))) return false
  }
  return true
}

export function matches<T>(record: T, where?: Where<T>): boolean {
  if (!where) return true
  for (const [key, cond] of Object.entries(where)) {
    if (cond === undefined) continue
    if (key === "$or") {
      const ors = cond as Where<T>[]
      if (ors.length && !ors.some((w) => matches(record, w))) return false
      continue
    }
    if (!matchCondition((record as Record<string, unknown>)[key], cond as FieldCondition<unknown>)) return false
  }
  return true
}

export function sortRecords<T>(items: T[], sort?: Sort<T> | Sort<T>[]) {
  const sorts = sort ? (Array.isArray(sort) ? sort : [sort]) : []
  if (!sorts.length) return items
  return items.sort((a, b) => {
    for (const s of sorts) {
      const av = (a as Record<string, unknown>)[s.field]
      const bv = (b as Record<string, unknown>)[s.field]
      if (av === bv) continue
      if (av === undefined || av === null) return 1
      if (bv === undefined || bv === null) return -1
      const r =
        typeof av === "number" && typeof bv === "number"
          ? av - bv
          : String(av).localeCompare(String(bv), undefined, { numeric: true, sensitivity: "base" })
      if (r !== 0) return s.dir === "desc" ? -r : r
    }
    return 0
  })
}

/**
 * In-memory collection (portable — no Node APIs). Reads are served from a Map; mutations are
 * serialized per collection and followed by `persistRows()`, which storage drivers override
 * (JSON files on the server, localStorage in the frontend mock runtime).
 */
export class MemoryRepository<T extends { id: ID }> implements Repository<T> {
  private cache: Map<ID, Stored<T>> | null = null
  private loading: Promise<Map<ID, Stored<T>>> | null = null
  private queue: Promise<unknown> = Promise.resolve()

  constructor(
    public readonly name: string,
    protected readonly idPrefix: string,
  ) {}

  /** Initial rows for the collection. Drivers override this to read from storage. */
  protected async loadRows(): Promise<Stored<T>[]> {
    return []
  }

  /** Called after every mutation with the full collection. Drivers override this to save. */
  protected async persistRows(rows: Stored<T>[]): Promise<void> {
    void rows
  }

  private async load(): Promise<Map<ID, Stored<T>>> {
    if (this.cache) return this.cache
    this.loading ??= (async () => {
      const rows = await this.loadRows()
      this.cache = new Map(rows.map((r) => [r.id, r]))
      return this.cache
    })()
    return this.loading
  }

  private async persist(map: Map<ID, Stored<T>>) {
    await this.persistRows([...map.values()])
  }

  /** Serializes mutations so concurrent requests never interleave file writes. */
  private mutate<R>(fn: (map: Map<ID, Stored<T>>) => R | Promise<R>): Promise<R> {
    const run = this.queue.then(async () => {
      const map = await this.load()
      const result = await fn(map)
      await this.persist(map)
      return result
    })
    this.queue = run.catch(() => undefined)
    return run
  }

  private scoped(map: Map<ID, Stored<T>>, orgId: ID) {
    return [...map.values()].filter((r) => r.orgId === orgId)
  }

  private clone<R>(v: R): R {
    return structuredClone(v)
  }

  async list(orgId: ID, query: ListQuery<Stored<T>> = {}): Promise<Page<Stored<T>>> {
    const map = await this.load()
    let rows = this.scoped(map, orgId).filter((r) => matches(r, query.where))
    if (query.search?.q.trim()) {
      const q = query.search.q.trim().toLowerCase()
      rows = rows.filter((r) =>
        query.search!.fields.some((f) => String((r as Record<string, unknown>)[f] ?? "").toLowerCase().includes(q)),
      )
    }
    sortRecords(rows, query.sort)
    const pageSize = Math.min(Math.max(query.pageSize ?? 25, 1), 1000)
    const page = Math.max(query.page ?? 1, 1)
    const items = rows.slice((page - 1) * pageSize, page * pageSize)
    return { items: this.clone(items), total: rows.length, page, pageSize }
  }

  async find(orgId: ID, where?: Where<Stored<T>>, sort?: Sort<Stored<T>> | Sort<Stored<T>>[]) {
    const map = await this.load()
    return this.clone(sortRecords(this.scoped(map, orgId).filter((r) => matches(r, where)), sort))
  }

  async findOne(orgId: ID, where: Where<Stored<T>>) {
    const map = await this.load()
    const found = this.scoped(map, orgId).find((r) => matches(r, where))
    return found ? this.clone(found) : null
  }

  async get(orgId: ID, id: ID) {
    const map = await this.load()
    const r = map.get(id)
    return r && r.orgId === orgId ? this.clone(r) : null
  }

  async count(orgId: ID, where?: Where<Stored<T>>) {
    const map = await this.load()
    return this.scoped(map, orgId).filter((r) => matches(r, where)).length
  }

  private build(orgId: ID, data: CreateInput<T>): Stored<T> {
    const now = nowIso()
    return {
      ...(data as object),
      id: data.id ?? newId(this.idPrefix),
      orgId,
      createdAt: data.createdAt ?? now,
      updatedAt: data.updatedAt ?? now,
    } as Stored<T>
  }

  create(orgId: ID, data: CreateInput<T>) {
    return this.mutate((map) => {
      const rec = this.build(orgId, data)
      map.set(rec.id, rec)
      return this.clone(rec)
    })
  }

  createMany(orgId: ID, data: CreateInput<T>[]) {
    return this.mutate((map) => {
      const recs = data.map((d) => this.build(orgId, d))
      for (const r of recs) map.set(r.id, r)
      return this.clone(recs)
    })
  }

  update(orgId: ID, id: ID, patch: Partial<T>) {
    return this.mutate((map) => {
      const cur = map.get(id)
      if (!cur || cur.orgId !== orgId) throw notFound(this.name.replace(/s$/, ""))
      const next = { ...cur, ...patch, id: cur.id, orgId: cur.orgId, createdAt: cur.createdAt, updatedAt: nowIso() }
      map.set(id, next)
      return this.clone(next)
    })
  }

  updateMany(orgId: ID, where: Where<Stored<T>>, patch: Partial<T> | ((r: Stored<T>) => Partial<T>)) {
    return this.mutate((map) => {
      const out: Stored<T>[] = []
      for (const cur of this.scoped(map, orgId)) {
        if (!matches(cur, where)) continue
        const p = typeof patch === "function" ? patch(cur) : patch
        const next = { ...cur, ...p, id: cur.id, orgId: cur.orgId, createdAt: cur.createdAt, updatedAt: nowIso() }
        map.set(cur.id, next)
        out.push(next)
      }
      return this.clone(out)
    })
  }

  remove(orgId: ID, id: ID) {
    return this.mutate((map) => {
      const cur = map.get(id)
      if (!cur || cur.orgId !== orgId) return false
      return map.delete(id)
    })
  }

  removeMany(orgId: ID, where: Where<Stored<T>>) {
    return this.mutate((map) => {
      let n = 0
      for (const r of this.scoped(map, orgId)) {
        if (matches(r, where)) {
          map.delete(r.id)
          n++
        }
      }
      return n
    })
  }

  async findGlobal(where: Where<Stored<T>>) {
    const map = await this.load()
    const found = [...map.values()].find((r) => matches(r, where))
    return found ? this.clone(found) : null
  }

  truncate() {
    return this.mutate((map) => {
      map.clear()
    })
  }
}
