// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { config } from "../../config"
import { db } from "../../db/index"
import { forbidden, notFound } from "../../lib/errors"
import { withAccounts, withContacts } from "../../lib/expand"
import { boolQuery, createModule, csvList, idParams, listQuery, paged } from "../../lib/http"
import { agentService } from "../agent/service"
import { signalService } from "./service"

const signalType = z.enum(["intent_topic", "website_visit", "hiring", "funding", "job_change", "tech_install", "social_engagement", "news"])

const ingestBody = z
  .object({
    type: signalType,
    accountId: z.string().optional(),
    domain: z.string().optional(),
    contactId: z.string().optional(),
    title: z.string().trim().min(1).max(300),
    detail: z.string().max(2000).optional(),
    strength: z.coerce.number().min(0).max(100),
    source: z.string().trim().max(100).optional(),
    occurredAt: z.iso.datetime().optional(),
  })
  .refine((b) => b.accountId || b.domain, { message: "accountId or domain is required", path: ["accountId"] })

async function expand(orgId: string, items: Awaited<ReturnType<typeof db.signals.find>>) {
  return withContacts(orgId, await withAccounts(orgId, items))
}

export const signalsModule = createModule("Signals", "/signals")
{
  const { route } = signalsModule

  route({
    method: "get",
    path: "/",
    summary: "List signals (with account and contact summaries)",
    query: listQuery.extend({
      type: csvList.pipe(z.array(signalType).optional()),
      source: csvList,
      processed: boolQuery,
      accountId: z.string().optional(),
      sinceDays: z.coerce.number().int().min(1).max(3650).optional(),
    }),
    handler: async ({ orgId, query }) => {
      const page = await signalService.list(orgId, query, query.page, query.pageSize)
      return paged({ ...page, items: await expand(orgId, page.items) })
    },
  })

  route({
    method: "get",
    path: "/stats",
    summary: "Signal volume stats (24h, 7d, pending, by source/type)",
    handler: ({ orgId }) => signalService.stats(orgId),
  })

  route({
    method: "post",
    path: "/",
    summary: "Ingest a signal; the agent processes it immediately when autopilot is on",
    body: ingestBody,
    handler: ({ orgId, body }) => signalService.ingest(orgId, body),
  })

  route({
    method: "post",
    path: "/simulate",
    summary: "Ingest a random realistic signal (demo/testing; ENABLE_SIMULATION)",
    handler: ({ orgId }) => {
      if (!config.enableSimulation) throw forbidden("Signal simulation is disabled")
      return signalService.simulate(orgId)
    },
  })

  route({
    method: "post",
    path: "/process-pending",
    summary: "Run the agent on every unprocessed signal",
    status: 200,
    handler: ({ orgId }) => agentService.processPending(orgId),
  })

  route({
    method: "get",
    path: "/:id",
    summary: "Get a signal with its agent runs",
    params: idParams,
    handler: async ({ orgId, params }) => {
      const s = await db.signals.get(orgId, params.id)
      if (!s) throw notFound("Signal")
      const [item] = await expand(orgId, [s])
      const runs = await db.runs.find(orgId, { signalId: s.id }, { field: "startedAt", dir: "desc" })
      const rules = await db.playbooks.find(orgId, { id: { in: runs.map((r) => r.ruleId).filter((x): x is string => !!x) } })
      return { ...item, runs: runs.map((r) => ({ ...r, ruleName: rules.find((x) => x.id === r.ruleId)?.name ?? null })) }
    },
  })

  route({
    method: "post",
    path: "/:id/process",
    summary: "Run the agent on one signal",
    status: 200,
    params: idParams,
    handler: ({ orgId, params }) => agentService.processSignal(orgId, params.id),
  })

  route({
    method: "delete",
    path: "/:id",
    summary: "Delete a signal",
    params: idParams,
    handler: async ({ orgId, params }) => {
      if (!(await db.signals.remove(orgId, params.id))) throw notFound("Signal")
    },
  })
}

/** Vendor / Zapier ingest authenticated by an org API key with the signals:write scope. */
export const webhooksModule = createModule("Webhooks", "/webhooks")
webhooksModule.route({
  method: "post",
  path: "/signals",
  summary: "Ingest signals from vendors (x-api-key)",
  description:
    "Accepts a single signal or `{ signals: [...] }` (max 100). Resolve the account by `accountId` or company `domain`.",
  auth: "apiKey",
  scope: "signals:write",
  status: 202,
  body: z.union([ingestBody, z.object({ signals: z.array(ingestBody).min(1).max(100) })]),
  handler: async ({ orgId, body }) => {
    const items = "signals" in body ? body.signals : [body]
    const results = []
    for (const [i, item] of items.entries()) {
      try {
        const r = await signalService.ingest(orgId, item)
        results.push({ index: i, ok: true, signalId: r.signal.id, runStatus: r.run?.status ?? "queued" })
      } catch (err) {
        results.push({ index: i, ok: false, error: (err as Error).message })
      }
    }
    return { accepted: results.filter((r) => r.ok).length, results }
  },
})
