// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import type { Where } from "../../db/repository"
import { SIGNAL_SOURCES } from "../../domain/constants"
import type { Signal, SignalType, Stored } from "../../domain/types"
import { bus } from "../../events/bus"
import { badRequest } from "../../lib/errors"
import { DAY_MS, nowIso } from "../../lib/ids"
import { activityService } from "../activities/service"
import { agentService } from "../agent/service"
import { contactService } from "../contacts/service"
import { normalizeDomain } from "../accounts/service"

export interface SignalFilters {
  type?: SignalType[]
  source?: string[]
  processed?: boolean
  accountId?: string
  sinceDays?: number
  q?: string
}

export interface IngestInput {
  type: SignalType
  accountId?: string
  /** Alternative to accountId for webhooks: resolve by company domain. */
  domain?: string
  contactId?: string
  title: string
  detail?: string
  strength: number
  source?: string
  occurredAt?: string
}

const SIM_TEMPLATES: Record<SignalType, { title: string; detail: string }> = {
  intent_topic: { title: "Surging on “AI SDR tools”", detail: "Topic score 84, 9 researchers in the last 48h" },
  website_visit: { title: "Visited pricing page", detail: "2 identified visitors, 5 pageviews in 6 minutes" },
  hiring: { title: "Hiring 3 Account Executives", detail: "New GTM job posts detected" },
  funding: { title: "Raised Series B", detail: "$40M led by Sequoia" },
  job_change: { title: "New VP Sales joined", detail: "Former champion at a customer account" },
  tech_install: { title: "Installed Salesforce", detail: "CRM migration detected" },
  social_engagement: { title: "Engaged with LinkedIn post", detail: "Liked and commented on our launch post" },
  news: { title: "Announced EMEA expansion", detail: "Press release mentions 40 new GTM hires" },
}

export function signalWhere(f: SignalFilters): Where<Stored<Signal>> {
  return {
    type: f.type?.length ? { in: f.type } : undefined,
    source: f.source?.length ? { in: f.source } : undefined,
    processed: f.processed,
    accountId: f.accountId,
    occurredAt: f.sinceDays ? { gte: new Date(Date.now() - f.sinceDays * DAY_MS).toISOString() } : undefined,
    $or: f.q ? [{ title: { contains: f.q } }, { detail: { contains: f.q } }] : undefined,
  }
}

export const signalService = {
  async list(orgId: string, f: SignalFilters, page: number, pageSize: number) {
    let where = signalWhere(f)
    if (f.q) {
      const accounts = await db.accounts.find(orgId, { name: { contains: f.q } })
      where = { ...where, $or: [...(where.$or ?? []), { accountId: { in: accounts.map((a) => a.id) } }] }
    }
    return db.signals.list(orgId, { where, sort: { field: "occurredAt", dir: "desc" }, page, pageSize })
  },

  /**
   * Stores a signal and — when autopilot is on — runs the orchestration agent on it.
   * Returns the created signal plus the agent run (null when queued).
   */
  async ingest(orgId: string, input: IngestInput) {
    let accountId = input.accountId
    if (!accountId && input.domain) {
      const acc = await db.accounts.findOne(orgId, { domain: normalizeDomain(input.domain), duplicateOf: { exists: false } })
      if (!acc) throw badRequest(`No account with domain ${input.domain}`)
      accountId = acc.id
    }
    if (!accountId) throw badRequest("accountId or domain is required")
    const account = await db.accounts.get(orgId, accountId)
    if (!account) throw badRequest("Account not found")
    if (input.contactId) {
      const c = await db.contacts.get(orgId, input.contactId)
      if (!c || c.accountId !== accountId) throw badRequest("Contact does not belong to the account")
    }
    const signal = await db.signals.create(orgId, {
      type: input.type,
      accountId,
      contactId: input.contactId,
      title: input.title,
      detail: input.detail ?? "",
      strength: input.strength,
      source: input.source ?? SIGNAL_SOURCES[input.type][0],
      occurredAt: input.occurredAt ?? nowIso(),
      processed: false,
    })
    await activityService.log(orgId, {
      accountId,
      contactId: signal.contactId,
      type: "signal",
      title: signal.title,
      detail: `${signal.source} · strength ${signal.strength}`,
      actorId: "system",
    })
    await bus.publish("signal.ingested", { orgId, signalId: signal.id })
    const { autopilot } = await agentService.getSettings(orgId)
    const run = autopilot ? await agentService.processSignal(orgId, signal.id) : null
    return { signal: autopilot ? { ...signal, processed: true } : signal, run }
  },

  async simulate(orgId: string) {
    const accounts = await db.accounts.find(orgId, { duplicateOf: { exists: false } }, { field: "fitScore", dir: "desc" })
    if (!accounts.length) throw badRequest("Add at least one account before simulating signals")
    const pool = accounts.slice(0, 30)
    const account = pool[Math.floor(Math.random() * pool.length)]
    const types = Object.keys(SIM_TEMPLATES) as SignalType[]
    const type = types[Math.floor(Math.random() * types.length)]
    const contact = await contactService.bestContact(orgId, account.id)
    const sources = SIGNAL_SOURCES[type]
    return this.ingest(orgId, {
      type,
      accountId: account.id,
      contactId: ["website_visit", "job_change", "social_engagement"].includes(type) ? contact?.id : undefined,
      source: sources[Math.floor(Math.random() * sources.length)],
      strength: 60 + Math.floor(Math.random() * 38),
      ...SIM_TEMPLATES[type],
    })
  },

  async stats(orgId: string) {
    const signals = await db.signals.find(orgId)
    const now = Date.now()
    const within = (days: number) => signals.filter((s) => now - new Date(s.occurredAt).getTime() <= days * DAY_MS)
    const last30 = within(30)
    const bySource = new Map<string, number>()
    for (const s of signals) bySource.set(s.source, (bySource.get(s.source) ?? 0) + 1)
    const byType = new Map<string, number>()
    for (const s of last30) byType.set(s.type, (byType.get(s.type) ?? 0) + 1)
    const sources = [...bySource.entries()].map(([source, count]) => ({ source, count })).sort((a, b) => b.count - a.count)
    return {
      total: signals.length,
      last24h: within(1).length,
      last7d: within(7).length,
      unprocessed: signals.filter((s) => !s.processed).length,
      topSource: sources[0]?.source ?? null,
      bySource: sources,
      byType30d: [...byType.entries()].map(([type, count]) => ({ type, count })),
    }
  },
}
