// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import { nowIso } from "../../lib/ids"
import { badRequest, notFound } from "../../lib/errors"

export const enrollmentService = {
  /**
   * Enrolls contacts into a sequence. Skips unsubscribed/bounced/invalid-email contacts and
   * contacts already actively enrolled in the same sequence.
   */
  async enroll(orgId: string, contactIds: string[], sequenceId: string) {
    const seq = await db.sequences.get(orgId, sequenceId)
    if (!seq) throw notFound("Sequence")
    if (!seq.steps.length) throw badRequest("Sequence has no steps")
    const unique = [...new Set(contactIds)]
    const [contacts, active] = await Promise.all([
      db.contacts.find(orgId, { id: { in: unique } }),
      db.enrollments.find(orgId, { sequenceId, status: "active", contactId: { in: unique } }),
    ])
    const activeSet = new Set(active.map((e) => e.contactId))
    const eligible = contacts.filter(
      (c) => !["unsubscribed", "bounced"].includes(c.status) && c.emailStatus !== "invalid" && !activeSet.has(c.id),
    )
    const now = nowIso()
    if (eligible.length) {
      await db.enrollments.createMany(
        orgId,
        eligible.map((c) => ({ sequenceId, contactId: c.id, currentStep: 0, status: "active" as const, enrolledAt: now, nextStepAt: now })),
      )
      await db.contacts.updateMany(orgId, { id: { in: eligible.map((c) => c.id) } }, { status: "in_sequence" })
      await db.sequences.update(orgId, sequenceId, {
        stats: { ...seq.stats, enrolled: seq.stats.enrolled + eligible.length },
      })
    }
    return {
      enrolled: eligible.length,
      skipped: unique.length - eligible.length,
      enrolledIds: eligible.map((c) => c.id),
      sequence: { id: seq.id, name: seq.name },
    }
  },
}
