// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { atLeast } from "../../middleware/auth"
import { boolQuery, createModule, csvList, idList, idParams, listQuery, paged, parseSort } from "../../lib/http"
import type { Enrollment, InboxMessage, Sequence } from "../../domain/types"
import { ENROLLMENT_SORT_FIELDS, SEQUENCE_SORT_FIELDS, outreachService } from "./service"

export const outreachModule = createModule("Outreach", "")
const { route } = outreachModule

// ---------- Schemas ----------
const SEQUENCE_STATUSES = ["active", "paused", "draft"] as const
const ENROLLMENT_STATUSES = ["active", "paused", "completed", "replied", "bounced", "unsubscribed"] as const
const SENTIMENTS = ["positive", "neutral", "negative", "ooo"] as const
const STEP_CHANNELS = ["email", "linkedin_connect", "linkedin_message", "call", "wait"] as const
const PROVIDERS = ["SES", "Google", "Microsoft", "Mailpool"] as const

const settingsSchema = z
  .object({
    sendDays: z.array(z.number().int().min(0).max(6)).min(1).max(7),
    startHour: z.number().int().min(0).max(23),
    endHour: z.number().int().min(1).max(24),
    timezone: z.string().trim().min(1).max(64),
    stopOnReply: z.boolean(),
    trackOpens: z.boolean(),
  })
  .refine((s) => s.endHour > s.startHour, { message: "endHour must be after startHour", path: ["endHour"] })

const sequenceCreate = z.object({
  name: z.string().trim().min(1).max(120),
  ownerId: z.string().min(1).optional(),
  mailboxIds: z.array(z.string().min(1)).max(50).optional(),
  status: z.enum(SEQUENCE_STATUSES).optional(),
  settings: settingsSchema.optional(),
})

const sequenceUpdate = z.object({
  name: z.string().trim().min(1).max(120).optional(),
  ownerId: z.string().min(1).optional(),
  mailboxIds: z.array(z.string().min(1)).max(50).optional(),
  status: z.enum(SEQUENCE_STATUSES).optional(),
  settings: settingsSchema.optional(),
})

const sequenceListQuery = listQuery.extend({ status: csvList.pipe(z.array(z.enum(SEQUENCE_STATUSES)).optional()) })
const enrollmentListQuery = listQuery.extend({ status: csvList.pipe(z.array(z.enum(ENROLLMENT_STATUSES)).optional()) })

const stepCreate = z.object({
  channel: z.enum(STEP_CHANNELS),
  dayOffset: z.number().int().min(0).max(365).optional(),
  subject: z.string().max(300).optional(),
  body: z.string().max(20_000).optional(),
})
const stepUpdate = z.object({
  channel: z.enum(STEP_CHANNELS).optional(),
  dayOffset: z.number().int().min(0).max(365).optional(),
  subject: z.string().max(300).optional(),
  body: z.string().max(20_000).optional(),
})
const stepParams = z.object({ id: z.string().min(1), stepId: z.string().min(1) })

const mailboxCreate = z.object({
  email: z.string().trim().max(254).pipe(z.email()),
  provider: z.enum(PROVIDERS),
  dailyLimit: z.number().int().min(1).max(2000),
})
const mailboxUpdate = z.object({
  dailyLimit: z.number().int().min(1).max(2000).optional(),
  warmupEnabled: z.boolean().optional(),
  status: z.enum(["healthy", "warning", "paused"]).optional(),
})

const inboxQuery = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(200).default(50),
  q: z.string().trim().optional(),
  sentiment: csvList.pipe(z.array(z.enum(SENTIMENTS)).optional()),
  archived: boolQuery,
  unread: boolQuery,
})

// ---------- Sequences ----------
route({
  method: "get",
  path: "/sequences",
  summary: "List sequences (with active enrollment counts and owner names)",
  query: sequenceListQuery,
  handler: async ({ orgId, query }) => {
    const sort = parseSort(query.sort, SEQUENCE_SORT_FIELDS, { field: "createdAt", dir: "desc" })
    return paged(
      await outreachService.listSequences(orgId, { status: query.status as Sequence["status"][] | undefined, q: query.q }, query.page, query.pageSize, sort),
    )
  },
})

route({
  method: "post",
  path: "/sequences",
  summary: "Create a sequence (starts with one empty email step)",
  body: sequenceCreate,
  handler: ({ orgId, auth, body }) => outreachService.createSequence(orgId, auth.userId, body),
})

route({
  method: "get",
  path: "/sequences/:id",
  summary: "Get a sequence",
  params: idParams,
  handler: ({ orgId, params }) => outreachService.getSequenceDetail(orgId, params.id),
})

route({
  method: "patch",
  path: "/sequences/:id",
  summary: "Update a sequence (name, status, owner, mailboxes, sending settings)",
  params: idParams,
  body: sequenceUpdate,
  handler: ({ orgId, params, body }) => outreachService.updateSequence(orgId, params.id, body),
})

route({
  method: "delete",
  path: "/sequences/:id",
  summary: "Delete a sequence and its enrollments",
  params: idParams,
  handler: async ({ orgId, params }) => {
    await outreachService.removeSequence(orgId, params.id)
  },
})

route({
  method: "post",
  path: "/sequences/:id/duplicate",
  summary: "Duplicate a sequence as a draft",
  params: idParams,
  handler: ({ orgId, params }) => outreachService.duplicateSequence(orgId, params.id),
})

// ---------- Steps ----------
route({
  method: "post",
  path: "/sequences/:id/steps",
  summary: "Append a step (dayOffset defaults to last step + 2)",
  params: idParams,
  body: stepCreate,
  handler: ({ orgId, params, body }) => outreachService.addStep(orgId, params.id, body),
})

route({
  method: "patch",
  path: "/sequences/:id/steps/:stepId",
  summary: "Update a step",
  params: stepParams,
  body: stepUpdate,
  handler: ({ orgId, params, body }) => outreachService.updateStep(orgId, params.id, params.stepId, body),
})

route({
  method: "delete",
  path: "/sequences/:id/steps/:stepId",
  summary: "Remove a step",
  params: stepParams,
  handler: async ({ orgId, params }) => {
    await outreachService.removeStep(orgId, params.id, params.stepId)
  },
})

route({
  method: "post",
  path: "/sequences/:id/steps/:stepId/move",
  summary: "Move a step up or down; returns the reordered steps",
  status: 200,
  params: stepParams,
  body: z.object({ direction: z.enum(["up", "down"]) }),
  handler: ({ orgId, params, body }) => outreachService.moveStep(orgId, params.id, params.stepId, body.direction),
})

// ---------- Enrollments ----------
route({
  method: "get",
  path: "/sequences/:id/enrollments",
  summary: "List enrollments in a sequence (with contact + account)",
  params: idParams,
  query: enrollmentListQuery,
  handler: async ({ orgId, params, query }) => {
    const sort = parseSort(query.sort, ENROLLMENT_SORT_FIELDS, { field: "enrolledAt", dir: "desc" })
    return paged(
      await outreachService.listEnrollments(
        orgId,
        params.id,
        { status: query.status as Enrollment["status"][] | undefined, q: query.q },
        query.page,
        query.pageSize,
        sort,
      ),
    )
  },
})

route({
  method: "get",
  path: "/sequences/:id/performance",
  summary: "Funnel, conversion rates and per-step breakdown",
  params: idParams,
  handler: ({ orgId, params }) => outreachService.performance(orgId, params.id),
})

route({
  method: "post",
  path: "/sequences/:id/enroll",
  summary: "Enroll contacts (skips unsubscribed/bounced/invalid and already-active)",
  status: 200,
  params: idParams,
  body: z.object({ contactIds: z.array(z.string().min(1)).min(1).max(1000) }),
  handler: ({ orgId, params, body }) => outreachService.enroll(orgId, params.id, body.contactIds),
})

route({
  method: "get",
  path: "/sequences/:id/enrollable",
  summary: "Up to 100 contacts not actively enrolled, flagged when they will be skipped",
  params: idParams,
  query: z.object({ q: z.string().trim().optional() }),
  handler: ({ orgId, params, query }) => outreachService.enrollable(orgId, params.id, query.q),
})

route({
  method: "post",
  path: "/enrollments/bulk-status",
  summary: "Set status on many enrollments",
  status: 200,
  body: idList.extend({ status: z.enum(["active", "paused", "completed"]) }),
  handler: ({ orgId, body }) => outreachService.bulkEnrollmentStatus(orgId, body.ids, body.status),
})

route({
  method: "post",
  path: "/enrollments/bulk-delete",
  summary: "Remove many enrollments",
  status: 200,
  body: idList,
  handler: ({ orgId, body }) => outreachService.bulkDeleteEnrollments(orgId, body.ids),
})

// ---------- Mailboxes ----------
route({
  method: "get",
  path: "/mailboxes",
  summary: "List sending mailboxes (with `usedBy` sequence count)",
  handler: ({ orgId }) => outreachService.listMailboxes(orgId),
})

route({
  method: "post",
  path: "/mailboxes",
  summary: "Connect a mailbox",
  roles: atLeast("admin"),
  body: mailboxCreate,
  handler: ({ orgId, body }) => outreachService.createMailbox(orgId, body),
})

route({
  method: "patch",
  path: "/mailboxes/:id",
  summary: "Update mailbox limit, warm-up or status",
  params: idParams,
  body: mailboxUpdate,
  handler: ({ orgId, params, body }) => outreachService.updateMailbox(orgId, params.id, body),
})

route({
  method: "delete",
  path: "/mailboxes/:id",
  summary: "Remove a mailbox (and from sequence rotations)",
  roles: atLeast("admin"),
  params: idParams,
  handler: async ({ orgId, params }) => {
    await outreachService.removeMailbox(orgId, params.id)
  },
})

// ---------- Inbox ----------
route({
  method: "get",
  path: "/inbox",
  summary: "List inbox replies (newest first). archived=true includes archived messages",
  query: inboxQuery,
  handler: async ({ orgId, query }) =>
    paged(
      await outreachService.listInbox(
        orgId,
        { sentiment: query.sentiment as InboxMessage["sentiment"][] | undefined, archived: query.archived, unread: query.unread, q: query.q },
        query.page,
        query.pageSize,
      ),
    ),
})

route({
  method: "get",
  path: "/inbox/counts",
  summary: "Unread total and per-sentiment counts",
  query: z.object({ archived: boolQuery }),
  handler: ({ orgId, query }) => outreachService.inboxCounts(orgId, query.archived),
})

route({
  method: "get",
  path: "/inbox/:id",
  summary: "Get an inbox message with its thread",
  params: idParams,
  handler: ({ orgId, params }) => outreachService.getMessageDetail(orgId, params.id),
})

route({
  method: "patch",
  path: "/inbox/:id",
  summary: "Mark read/archived or change sentiment",
  params: idParams,
  body: z.object({
    read: z.boolean().optional(),
    archived: z.boolean().optional(),
    sentiment: z.enum(SENTIMENTS).optional(),
  }),
  handler: ({ orgId, params, body }) => outreachService.updateMessage(orgId, params.id, body),
})

route({
  method: "post",
  path: "/inbox/:id/reply",
  summary: "Reply to a message (sends email, appends to thread)",
  params: idParams,
  body: z.object({ body: z.string().trim().min(1).max(20_000) }),
  handler: ({ orgId, auth, params, body }) => outreachService.reply(orgId, auth.userId, params.id, body.body),
})

route({
  method: "post",
  path: "/inbox/:id/suggest-reply",
  summary: "AI-suggested reply for a message",
  status: 200,
  params: idParams,
  handler: ({ orgId, auth, params }) => outreachService.suggestReply(orgId, auth.userId, params.id),
})

route({
  method: "post",
  path: "/inbox/:id/book-meeting",
  summary: "Book a meeting from a reply; creates or advances the account's deal",
  status: 200,
  params: idParams,
  handler: ({ orgId, auth, params }) => outreachService.bookMeeting(orgId, auth.userId, params.id),
})

// ---------- Stats ----------
route({
  method: "get",
  path: "/outreach/stats",
  summary: "Aggregate outreach stats across sequences",
  handler: ({ orgId }) => outreachService.stats(orgId),
})
