// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import type { Where } from "../../db/repository"
import type {
  Contact,
  Enrollment,
  InboxMessage,
  Mailbox,
  Sequence,
  SequenceSettings,
  SequenceStep,
  Stored,
} from "../../domain/types"
import { badRequest, conflict, notFound } from "../../lib/errors"
import { DAY_MS, newId, nowIso } from "../../lib/ids"
import { providers } from "../../providers/index"
import { activityService } from "../activities/service"
import { pipelineService } from "../pipeline/service"
import { enrollmentService } from "./enrollment"

export const SEQUENCE_SORT_FIELDS = ["name", "status", "createdAt", "updatedAt"] as const
export const ENROLLMENT_SORT_FIELDS = ["enrolledAt", "status", "currentStep", "nextStepAt"] as const

type SortOf<F extends string> = { field: F; dir: "asc" | "desc" }

const zeroStats = (): Sequence["stats"] => ({ enrolled: 0, sent: 0, opened: 0, replied: 0, meetings: 0, bounced: 0 })

/** Percentage with one decimal (0 when the denominator is 0). */
const pct = (part: number, whole: number) => (whole > 0 ? Math.round((part / whole) * 1000) / 10 : 0)

const blockedReason = (c: Pick<Contact, "status" | "emailStatus">): string | null =>
  c.status === "unsubscribed" ? "unsubscribed" : c.status === "bounced" ? "bounced" : c.emailStatus === "invalid" ? "invalid email" : null

/** Split `total` across `weights` so the parts sum exactly to `total` (largest remainder). */
function apportion(total: number, weights: number[]) {
  const sum = weights.reduce((a, b) => a + b, 0)
  if (!sum || !total) return weights.map(() => 0)
  const raw = weights.map((w) => (total * w) / sum)
  const out = raw.map(Math.floor)
  let rest = total - out.reduce((a, b) => a + b, 0)
  const order = raw.map((r, i) => ({ i, frac: r - Math.floor(r) })).sort((a, b) => b.frac - a.frac)
  for (const { i } of order) {
    if (rest <= 0) break
    out[i]++
    rest--
  }
  return out
}

async function activeCounts(orgId: string, sequenceIds: string[]) {
  const map = new Map<string, number>()
  if (!sequenceIds.length) return map
  const active = await db.enrollments.find(orgId, { status: "active", sequenceId: { in: sequenceIds } })
  for (const e of active) map.set(e.sequenceId, (map.get(e.sequenceId) ?? 0) + 1)
  return map
}

async function assertOwner(orgId: string, ownerId: string) {
  const user = await db.users.get(orgId, ownerId)
  if (!user) throw badRequest("Owner not found in this organization")
}

async function assertMailboxes(orgId: string, ids: string[]) {
  const unique = [...new Set(ids)]
  if (!unique.length) return unique
  const found = await db.mailboxes.count(orgId, { id: { in: unique } })
  if (found !== unique.length) throw badRequest("One or more mailboxes were not found")
  return unique
}

export interface SequenceInput {
  name: string
  ownerId?: string
  mailboxIds?: string[]
  status?: Sequence["status"]
  settings?: SequenceSettings
}

export type StepInput = Omit<SequenceStep, "id" | "dayOffset"> & { dayOffset?: number }

export interface InboxFilters {
  sentiment?: InboxMessage["sentiment"][]
  /** false/undefined → hide archived; true → include archived messages. */
  archived?: boolean
  unread?: boolean
  q?: string
}

export const outreachService = {
  // ---------------------------------------------------------------- Sequences
  async getSequence(orgId: string, id: string) {
    const seq = await db.sequences.get(orgId, id)
    if (!seq) throw notFound("Sequence")
    return seq
  },

  async listSequences(
    orgId: string,
    f: { status?: Sequence["status"][]; q?: string },
    page: number,
    pageSize: number,
    sort: SortOf<(typeof SEQUENCE_SORT_FIELDS)[number]>,
  ) {
    const result = await db.sequences.list(orgId, {
      where: { status: f.status?.length ? { in: f.status } : undefined },
      search: f.q ? { q: f.q, fields: ["name"] } : undefined,
      sort,
      page,
      pageSize,
    })
    const [counts, users] = await Promise.all([
      activeCounts(orgId, result.items.map((s) => s.id)),
      db.users.find(orgId, { id: { in: [...new Set(result.items.map((s) => s.ownerId))] } }),
    ])
    const names = new Map(users.map((u) => [u.id, u.name]))
    return {
      ...result,
      items: result.items.map((s) => ({ ...s, activeEnrollments: counts.get(s.id) ?? 0, ownerName: names.get(s.ownerId) ?? null })),
    }
  },

  async getSequenceDetail(orgId: string, id: string) {
    const seq = await this.getSequence(orgId, id)
    const [activeEnrollments, owner] = await Promise.all([
      db.enrollments.count(orgId, { sequenceId: id, status: "active" }),
      db.users.get(orgId, seq.ownerId),
    ])
    return { ...seq, activeEnrollments, ownerName: owner?.name ?? null }
  },

  async createSequence(orgId: string, actorId: string, input: SequenceInput) {
    const ownerId = input.ownerId ?? actorId
    await assertOwner(orgId, ownerId)
    const mailboxIds = await assertMailboxes(orgId, input.mailboxIds ?? [])
    const seq = await db.sequences.create(orgId, {
      name: input.name,
      status: input.status ?? "draft",
      ownerId,
      mailboxIds,
      steps: [{ id: newId("step"), channel: "email", dayOffset: 0, subject: "", body: "" }],
      stats: zeroStats(),
      ...(input.settings ? { settings: input.settings } : {}),
    })
    return this.getSequenceDetail(orgId, seq.id)
  },

  async updateSequence(orgId: string, id: string, patch: Partial<SequenceInput>) {
    const cur = await this.getSequence(orgId, id)
    const next: Partial<Sequence> = {}
    if (patch.name !== undefined) next.name = patch.name
    if (patch.ownerId !== undefined) {
      await assertOwner(orgId, patch.ownerId)
      next.ownerId = patch.ownerId
    }
    if (patch.mailboxIds !== undefined) next.mailboxIds = await assertMailboxes(orgId, patch.mailboxIds)
    if (patch.settings !== undefined) {
      if (patch.settings.endHour <= patch.settings.startHour) throw badRequest("endHour must be after startHour")
      next.settings = patch.settings
    }
    if (patch.status !== undefined) {
      if (patch.status === "active" && cur.status !== "active" && cur.steps.length === 0) {
        throw badRequest("Cannot activate a sequence with no steps")
      }
      next.status = patch.status
    }
    await db.sequences.update(orgId, id, next)
    return this.getSequenceDetail(orgId, id)
  },

  async removeSequence(orgId: string, id: string) {
    await this.getSequence(orgId, id)
    await db.enrollments.removeMany(orgId, { sequenceId: id })
    await db.playbooks.updateMany(orgId, { sequenceId: id }, { sequenceId: undefined })
    await db.drafts.updateMany(orgId, { sequenceId: id }, { sequenceId: undefined })
    await db.sequences.remove(orgId, id)
  },

  async duplicateSequence(orgId: string, id: string) {
    const src = await this.getSequence(orgId, id)
    const copy = await db.sequences.create(orgId, {
      name: `${src.name} (copy)`,
      status: "draft",
      ownerId: src.ownerId,
      mailboxIds: [...src.mailboxIds],
      steps: src.steps.map((st) => ({ ...st, id: newId("step") })),
      stats: zeroStats(),
      ...(src.settings ? { settings: { ...src.settings } } : {}),
    })
    return this.getSequenceDetail(orgId, copy.id)
  },

  // ---------------------------------------------------------------- Steps
  async addStep(orgId: string, sequenceId: string, input: StepInput) {
    const seq = await this.getSequence(orgId, sequenceId)
    const last = seq.steps[seq.steps.length - 1]
    const step: SequenceStep = {
      id: newId("step"),
      channel: input.channel,
      dayOffset: input.dayOffset ?? (last ? last.dayOffset + 2 : 0),
      ...(input.subject !== undefined ? { subject: input.subject } : input.channel === "email" ? { subject: "" } : {}),
      ...(input.body !== undefined ? { body: input.body } : input.channel !== "wait" ? { body: "" } : {}),
    }
    await db.sequences.update(orgId, sequenceId, { steps: [...seq.steps, step] })
    return step
  },

  async updateStep(orgId: string, sequenceId: string, stepId: string, patch: Partial<Omit<SequenceStep, "id">>) {
    const seq = await this.getSequence(orgId, sequenceId)
    const cur = seq.steps.find((s) => s.id === stepId)
    if (!cur) throw notFound("Step")
    const updated: SequenceStep = { ...cur, ...patch, id: cur.id }
    await db.sequences.update(orgId, sequenceId, { steps: seq.steps.map((s) => (s.id === stepId ? updated : s)) })
    return updated
  },

  async removeStep(orgId: string, sequenceId: string, stepId: string) {
    const seq = await this.getSequence(orgId, sequenceId)
    if (!seq.steps.some((s) => s.id === stepId)) throw notFound("Step")
    const steps = seq.steps.filter((s) => s.id !== stepId)
    if (!steps.length && seq.status === "active") throw badRequest("An active sequence must keep at least one step")
    await db.sequences.update(orgId, sequenceId, { steps })
  },

  async moveStep(orgId: string, sequenceId: string, stepId: string, direction: "up" | "down") {
    const seq = await this.getSequence(orgId, sequenceId)
    const i = seq.steps.findIndex((s) => s.id === stepId)
    if (i < 0) throw notFound("Step")
    const j = i + (direction === "up" ? -1 : 1)
    if (j < 0 || j >= seq.steps.length) throw badRequest(`Step is already at the ${direction === "up" ? "top" : "bottom"}`)
    const steps = [...seq.steps]
    ;[steps[i], steps[j]] = [steps[j], steps[i]]
    const updated = await db.sequences.update(orgId, sequenceId, { steps })
    return updated.steps
  },

  // ---------------------------------------------------------------- Enrollments
  async listEnrollments(
    orgId: string,
    sequenceId: string,
    f: { status?: Enrollment["status"][]; q?: string },
    page: number,
    pageSize: number,
    sort: SortOf<(typeof ENROLLMENT_SORT_FIELDS)[number]>,
  ) {
    await this.getSequence(orgId, sequenceId)
    const where: Where<Stored<Enrollment>> = { sequenceId, status: f.status?.length ? { in: f.status } : undefined }
    if (f.q) {
      const matching = await db.contacts.find(orgId, {
        $or: [{ firstName: { contains: f.q } }, { lastName: { contains: f.q } }, { email: { contains: f.q } }, { title: { contains: f.q } }],
      })
      where.contactId = { in: matching.map((c) => c.id) }
    }
    const result = await db.enrollments.list(orgId, { where, sort, page, pageSize })
    const contacts = await db.contacts.find(orgId, { id: { in: result.items.map((e) => e.contactId) } })
    const accounts = await db.accounts.find(orgId, { id: { in: [...new Set(contacts.map((c) => c.accountId))] } })
    const cMap = new Map(contacts.map((c) => [c.id, c]))
    const aMap = new Map(accounts.map((a) => [a.id, a]))
    return {
      ...result,
      items: result.items.map((e) => {
        const c = cMap.get(e.contactId)
        const a = c ? aMap.get(c.accountId) : undefined
        return {
          ...e,
          contact: c ? { id: c.id, firstName: c.firstName, lastName: c.lastName, title: c.title, email: c.email } : null,
          account: a ? { id: a.id, name: a.name } : null,
        }
      }),
    }
  },

  enroll(orgId: string, sequenceId: string, contactIds: string[]) {
    return enrollmentService.enroll(orgId, contactIds, sequenceId)
  },

  async enrollable(orgId: string, sequenceId: string, q?: string) {
    await this.getSequence(orgId, sequenceId)
    const active = await db.enrollments.find(orgId, { sequenceId, status: "active" })
    const where: Where<Stored<Contact>> = {
      id: active.length ? { nin: active.map((e) => e.contactId) } : undefined,
      $or: q
        ? [{ firstName: { contains: q } }, { lastName: { contains: q } }, { email: { contains: q } }, { title: { contains: q } }]
        : undefined,
    }
    const page = await db.contacts.list(orgId, {
      where,
      sort: [
        { field: "firstName", dir: "asc" },
        { field: "lastName", dir: "asc" },
      ],
      page: 1,
      pageSize: 100,
    })
    const accounts = await db.accounts.find(orgId, { id: { in: [...new Set(page.items.map((c) => c.accountId))] } })
    const aMap = new Map(accounts.map((a) => [a.id, a.name]))
    return {
      items: page.items.map((c) => {
        const reason = blockedReason(c)
        return {
          id: c.id,
          firstName: c.firstName,
          lastName: c.lastName,
          title: c.title,
          email: c.email,
          emailStatus: c.emailStatus,
          status: c.status,
          accountId: c.accountId,
          accountName: aMap.get(c.accountId) ?? null,
          willSkip: reason !== null,
          skipReason: reason,
        }
      }),
      total: page.total,
    }
  },

  async bulkEnrollmentStatus(orgId: string, ids: string[], status: "active" | "paused" | "completed") {
    const updated = await db.enrollments.updateMany(orgId, { id: { in: ids } }, { status })
    return { updated: updated.length }
  },

  async bulkDeleteEnrollments(orgId: string, ids: string[]) {
    const removed = await db.enrollments.removeMany(orgId, { id: { in: ids } })
    return { removed }
  },

  async performance(orgId: string, sequenceId: string) {
    const seq = await this.getSequence(orgId, sequenceId)
    const { stats, steps } = seq
    const emailIdx = steps.map((s, i) => (s.channel === "email" ? i : -1)).filter((i) => i >= 0)
    const sendW = emailIdx.map((_, k) => 0.72 ** k)
    const sent = apportion(stats.sent, sendW)
    const opened = apportion(stats.opened, sendW.map((w, k) => w * 0.9 ** k))
    const replied = apportion(stats.replied, sendW.map((w, k) => w * 0.85 ** k))

    let emailK = 0
    const stepRows = steps.map((step, index) => {
      const reached = Math.round(stats.enrolled * 0.86 ** index)
      const base = { stepId: step.id, index, channel: step.channel, dayOffset: step.dayOffset, subject: step.subject ?? null, reached }
      switch (step.channel) {
        case "email": {
          const k = emailK++
          // Not clamped to `sent` so the email rows always sum to the sequence totals.
          return { ...base, primary: sent[k], primaryLabel: "sent", secondary: opened[k], secondaryLabel: "opened", replied: replied[k] }
        }
        case "linkedin_connect":
          return { ...base, primary: Math.round(reached * 0.92), primaryLabel: "requests", secondary: Math.round(reached * 0.38), secondaryLabel: "accepted", replied: null }
        case "linkedin_message":
          return { ...base, primary: Math.round(reached * 0.4), primaryLabel: "messages", secondary: Math.round(reached * 0.31), secondaryLabel: "seen", replied: Math.round(reached * 0.06) }
        case "call":
          return { ...base, primary: Math.round(reached * 0.7), primaryLabel: "dials", secondary: Math.round(reached * 0.18), secondaryLabel: "connected", replied: Math.round(reached * 0.05) }
        default:
          return { ...base, primary: null, primaryLabel: "", secondary: null, secondaryLabel: "", replied: null }
      }
    })

    return {
      sequenceId: seq.id,
      stats,
      funnel: [
        { stage: "enrolled", label: "Enrolled", value: stats.enrolled },
        { stage: "sent", label: "Sent", value: stats.sent },
        { stage: "opened", label: "Opened", value: stats.opened },
        { stage: "replied", label: "Replied", value: stats.replied },
        { stage: "meetings", label: "Meetings", value: stats.meetings },
      ],
      rates: {
        openRate: pct(stats.opened, stats.sent),
        replyRate: pct(stats.replied, stats.sent),
        meetingRate: pct(stats.meetings, stats.replied),
        bounceRate: pct(stats.bounced, stats.sent),
      },
      steps: stepRows,
    }
  },

  async stats(orgId: string) {
    const [sequences, activeEnrollments] = await Promise.all([
      db.sequences.find(orgId),
      db.enrollments.count(orgId, { status: "active" }),
    ])
    const t = sequences.reduce((acc, q) => {
      for (const k of Object.keys(acc) as (keyof Sequence["stats"])[]) acc[k] += q.stats[k] ?? 0
      return acc
    }, zeroStats())
    return {
      ...t,
      openRate: pct(t.opened, t.sent),
      replyRate: pct(t.replied, t.sent),
      activeSequences: sequences.filter((s) => s.status === "active").length,
      totalSequences: sequences.length,
      activeEnrollments,
    }
  },

  // ---------------------------------------------------------------- Mailboxes
  async listMailboxes(orgId: string) {
    const [mailboxes, sequences] = await Promise.all([
      db.mailboxes.find(orgId, undefined, { field: "email", dir: "asc" }),
      db.sequences.find(orgId),
    ])
    return mailboxes.map((m) => ({ ...m, usedBy: sequences.filter((s) => s.mailboxIds.includes(m.id)).length }))
  },

  async createMailbox(orgId: string, input: Pick<Mailbox, "email" | "provider" | "dailyLimit">) {
    const email = input.email.trim().toLowerCase()
    if (await db.mailboxes.findOne(orgId, { email })) throw conflict(`Mailbox ${email} is already connected`)
    const mb = await db.mailboxes.create(orgId, {
      email,
      provider: input.provider,
      dailyLimit: input.dailyLimit,
      sentToday: 0,
      warmupEnabled: true,
      healthScore: 70,
      status: "warning",
    })
    return { ...mb, usedBy: 0 }
  },

  async updateMailbox(orgId: string, id: string, patch: Partial<Pick<Mailbox, "dailyLimit" | "warmupEnabled" | "status">>) {
    if (!(await db.mailboxes.get(orgId, id))) throw notFound("Mailbox")
    const mb = await db.mailboxes.update(orgId, id, patch)
    const usedBy = await db.sequences.count(orgId, { mailboxIds: id })
    return { ...mb, usedBy }
  },

  async removeMailbox(orgId: string, id: string) {
    if (!(await db.mailboxes.get(orgId, id))) throw notFound("Mailbox")
    await db.sequences.updateMany(orgId, { mailboxIds: id }, (s) => ({ mailboxIds: s.mailboxIds.filter((x) => x !== id) }))
    await db.mailboxes.remove(orgId, id)
  },

  // ---------------------------------------------------------------- Inbox
  async getMessage(orgId: string, id: string) {
    const m = await db.inbox.get(orgId, id)
    if (!m) throw notFound("Message")
    return m
  },

  async enrichMessages(orgId: string, messages: Stored<InboxMessage>[]) {
    const contacts = await db.contacts.find(orgId, { id: { in: [...new Set(messages.map((m) => m.contactId))] } })
    const seqIds = [...new Set(messages.map((m) => m.sequenceId).filter((x): x is string => !!x))]
    const [accounts, sequences] = await Promise.all([
      db.accounts.find(orgId, { id: { in: [...new Set(contacts.map((c) => c.accountId))] } }),
      seqIds.length ? db.sequences.find(orgId, { id: { in: seqIds } }) : Promise.resolve([]),
    ])
    const cMap = new Map(contacts.map((c) => [c.id, c]))
    const aMap = new Map(accounts.map((a) => [a.id, a]))
    const sMap = new Map(sequences.map((s) => [s.id, s.name]))
    return messages.map((m) => {
      const c = cMap.get(m.contactId)
      const a = c ? aMap.get(c.accountId) : undefined
      return {
        ...m,
        contact: c ? { id: c.id, firstName: c.firstName, lastName: c.lastName, title: c.title, accountId: c.accountId } : null,
        account: a ? { id: a.id, name: a.name } : null,
        sequenceName: m.sequenceId ? (sMap.get(m.sequenceId) ?? null) : null,
      }
    })
  },

  async inboxWhere(orgId: string, f: InboxFilters, includeSentiment: boolean): Promise<Where<Stored<InboxMessage>>> {
    const where: Where<Stored<InboxMessage>> = {
      archived: f.archived ? undefined : false,
      read: f.unread === undefined ? undefined : !f.unread,
      sentiment: includeSentiment && f.sentiment?.length ? { in: f.sentiment } : undefined,
    }
    if (f.q) {
      const contacts = await db.contacts.find(orgId, {
        $or: [{ firstName: { contains: f.q } }, { lastName: { contains: f.q } }, { email: { contains: f.q } }],
      })
      where.$or = [
        { subject: { contains: f.q } },
        { snippet: { contains: f.q } },
        { body: { contains: f.q } },
        ...(contacts.length ? [{ contactId: { in: contacts.map((c) => c.id) } }] : []),
      ]
    }
    return where
  },

  async listInbox(orgId: string, f: InboxFilters, page: number, pageSize: number) {
    const result = await db.inbox.list(orgId, {
      where: await this.inboxWhere(orgId, f, true),
      sort: { field: "receivedAt", dir: "desc" },
      page,
      pageSize,
    })
    return { ...result, items: await this.enrichMessages(orgId, result.items) }
  },

  async inboxCounts(orgId: string, archived?: boolean) {
    const [unread, visible] = await Promise.all([
      db.inbox.count(orgId, { read: false, archived: false }),
      db.inbox.find(orgId, { archived: archived ? undefined : false }),
    ])
    const bySentiment: Record<InboxMessage["sentiment"], number> = { positive: 0, neutral: 0, negative: 0, ooo: 0 }
    for (const m of visible) bySentiment[m.sentiment]++
    return { unread, all: visible.length, ...bySentiment }
  },

  async getMessageDetail(orgId: string, id: string) {
    const [m] = await this.enrichMessages(orgId, [await this.getMessage(orgId, id)])
    return m
  },

  async updateMessage(orgId: string, id: string, patch: Partial<Pick<InboxMessage, "read" | "archived" | "sentiment">>) {
    await this.getMessage(orgId, id)
    await db.inbox.update(orgId, id, patch)
    return this.getMessageDetail(orgId, id)
  },

  async reply(orgId: string, actorId: string, id: string, body: string) {
    const m = await this.getMessage(orgId, id)
    const contact = await db.contacts.get(orgId, m.contactId)
    const at = nowIso()
    if (m.channel === "email" && contact?.email) {
      const user = await db.users.get(orgId, actorId)
      await providers.email.send({
        from: user?.email,
        to: contact.email,
        subject: m.subject.toLowerCase().startsWith("re:") ? m.subject : `Re: ${m.subject}`,
        body,
      })
    }
    await db.inbox.update(orgId, id, { read: true, thread: [...m.thread, { from: "us", body, at }] })
    if (contact) await db.contacts.update(orgId, contact.id, { lastContactedAt: at })
    await activityService.log(orgId, {
      accountId: contact?.accountId,
      contactId: m.contactId,
      type: "email",
      title: `Replied: ${m.subject}`,
      detail: body.slice(0, 120),
      actorId,
    })
    return this.getMessageDetail(orgId, id)
  },

  async suggestReply(orgId: string, actorId: string, id: string) {
    const m = await this.getMessage(orgId, id)
    const [contact, user] = await Promise.all([db.contacts.get(orgId, m.contactId), db.users.get(orgId, actorId)])
    const senderName = user?.name.split(" ")[0] ?? "Team"
    const body = await providers.llm.suggestReply({ message: m, contact: contact ?? undefined, senderName })
    return { body }
  },

  async bookMeeting(orgId: string, actorId: string, id: string) {
    const m = await this.getMessage(orgId, id)
    const contact = await db.contacts.get(orgId, m.contactId)
    if (!contact) throw badRequest("The contact for this message no longer exists")

    await db.contacts.update(orgId, contact.id, { status: "meeting" })
    await db.enrollments.updateMany(orgId, { contactId: contact.id, status: "active" }, { status: "replied" })
    if (m.sequenceId) {
      const seq = await db.sequences.get(orgId, m.sequenceId)
      if (seq) await db.sequences.update(orgId, seq.id, { stats: { ...seq.stats, meetings: seq.stats.meetings + 1 } })
    }
    if (m.sentiment !== "positive" || !m.read) await db.inbox.update(orgId, id, { sentiment: "positive", read: true })
    await activityService.log(orgId, {
      accountId: contact.accountId,
      contactId: contact.id,
      type: "meeting",
      title: `Meeting booked with ${contact.firstName} ${contact.lastName}`,
      detail: m.subject,
      actorId,
    })

    const existing = await db.deals.findOne(orgId, {
      accountId: contact.accountId,
      stage: { nin: ["closed_won", "closed_lost"] },
    })
    if (existing) {
      const deal = existing.stage === "discovery" ? await pipelineService.move(orgId, actorId, existing.id, "qualified") : existing
      return { deal, created: false }
    }
    const account = await db.accounts.get(orgId, contact.accountId)
    const deal = await pipelineService.create(orgId, actorId, {
      name: `${account?.name ?? "New"} – Discovery`,
      accountId: contact.accountId,
      contactId: contact.id,
      amount: 24_000,
      stage: "discovery",
      closeDate: new Date(Date.now() + 40 * DAY_MS).toISOString(),
      source: "Sequence reply",
    })
    return { deal, created: true }
  },
}
