// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { config } from "../config"
import { logger } from "../lib/logger"

/** Domain events published between services. */
export interface DomainEvents {
  "signal.ingested": { orgId: string; signalId: string }
  "account.created": { orgId: string; accountId: string }
  "deal.stage_changed": { orgId: string; dealId: string; from: string; to: string }
  "draft.approved": { orgId: string; draftId: string }
}

type Handler<K extends keyof DomainEvents> = (payload: DomainEvents[K]) => void | Promise<void>

export interface EventBus {
  publish<K extends keyof DomainEvents>(type: K, payload: DomainEvents[K]): Promise<void>
  subscribe<K extends keyof DomainEvents>(type: K, handler: Handler<K>): void
}

/**
 * In-process bus (portable — no Node APIs). Handlers run asynchronously after the publisher
 * continues. Swap for EventBridge/SQS by implementing EventBus and selecting it with
 * EVENT_BUS_DRIVER in createBus().
 */
class MemoryEventBus implements EventBus {
  private handlers = new Map<keyof DomainEvents, Handler<keyof DomainEvents>[]>()

  async publish<K extends keyof DomainEvents>(type: K, payload: DomainEvents[K]) {
    for (const h of this.handlers.get(type) ?? []) {
      queueMicrotask(() => {
        Promise.resolve((h as Handler<K>)(payload)).catch((err) => logger.error({ err, type }, "Event handler failed"))
      })
    }
  }

  subscribe<K extends keyof DomainEvents>(type: K, handler: Handler<K>) {
    this.handlers.set(type, [...(this.handlers.get(type) ?? []), handler as Handler<keyof DomainEvents>])
  }
}

function createBus(): EventBus {
  if (config.EVENT_BUS_DRIVER !== "memory") {
    logger.warn(`EVENT_BUS_DRIVER=${config.EVENT_BUS_DRIVER} is not implemented yet; using the in-memory bus`)
  }
  return new MemoryEventBus()
}

export const bus = createBus()
