// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { config } from "../../config"
import { forbidden } from "../../lib/errors"
import { createModule } from "../../lib/http"
import { clearOrgData, seedDemoData } from "../../seed/demo"

export const adminModule = createModule("Admin", "/admin")

adminModule.route({
  method: "post",
  path: "/reset",
  summary: "Wipe this organization's data (dev only); optionally load the demo dataset",
  description: "Keeps the organization, users and API keys. Disabled when NODE_ENV=production or ENABLE_ADMIN_RESET=false.",
  roles: ["owner"],
  status: 200,
  body: z.object({ demo: z.boolean().default(false) }),
  handler: async ({ orgId, auth, body }) => {
    if (!config.enableAdminReset) throw forbidden("Admin reset is disabled")
    await clearOrgData(orgId)
    const counts = body.demo ? await seedDemoData(orgId, auth.userId) : null
    return { reset: true, demo: body.demo, counts }
  },
})
