// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { boolQuery, createModule, idParams, paged } from "../../lib/http"
import { atLeast } from "../../middleware/auth"
import { notificationService } from "./service"

export const notificationsModule = createModule("Notifications", "/notifications")
const { route } = notificationsModule
const everyone = atLeast("viewer")

route({
  method: "get",
  path: "/",
  summary: "Latest notifications",
  query: z.object({ unreadOnly: boolQuery, limit: z.coerce.number().int().min(1).max(200).default(50) }),
  handler: async ({ orgId, query }) => paged(await notificationService.list(orgId, { unreadOnly: query.unreadOnly, limit: query.limit })),
})

route({
  method: "post",
  path: "/:id/read",
  summary: "Mark one notification read",
  status: 200,
  roles: everyone,
  params: idParams,
  handler: ({ orgId, params }) => notificationService.markRead(orgId, params.id),
})

route({
  method: "post",
  path: "/read-all",
  summary: "Mark all notifications read",
  status: 200,
  roles: everyone,
  handler: ({ orgId }) => notificationService.markAllRead(orgId),
})
