// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { config } from "../../config"
import { db } from "../../db/index"
import type { AppNotification } from "../../domain/types"
import { nowIso } from "../../lib/ids"
import { logger } from "../../lib/logger"

const MAX_PER_ORG = 200

export const notificationService = {
  async notify(orgId: string, n: Omit<AppNotification, "id" | "at" | "read">) {
    const created = await db.notifications.create(orgId, { ...n, at: nowIso(), read: false })
    // Keep the feed bounded.
    const all = await db.notifications.find(orgId, undefined, { field: "at", dir: "desc" })
    if (all.length > MAX_PER_ORG) {
      await db.notifications.removeMany(orgId, { id: { in: all.slice(MAX_PER_ORG).map((x) => x.id) } })
    }
    if (config.SLACK_WEBHOOK_URL?.startsWith("https://hooks.slack.com/") && config.isProd) {
      fetch(config.SLACK_WEBHOOK_URL, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ text: `*${n.title}*\n${n.body}` }),
      }).catch((err) => logger.warn({ err }, "Slack notification failed"))
    }
    return created
  },

  list(orgId: string, opts: { unreadOnly?: boolean; limit: number }) {
    return db.notifications.list(orgId, {
      where: { read: opts.unreadOnly ? false : undefined },
      sort: { field: "at", dir: "desc" },
      pageSize: opts.limit,
    })
  },

  markRead(orgId: string, id: string) {
    return db.notifications.update(orgId, id, { read: true })
  },

  async markAllRead(orgId: string) {
    const updated = await db.notifications.updateMany(orgId, { read: false }, { read: true })
    return { updated: updated.length }
  },
}
