// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { db } from "../../db/index"
import { notFound } from "../../lib/errors"
import { withAccounts, withContacts } from "../../lib/expand"
import { createModule, csvList, idParams, listQuery, paged } from "../../lib/http"
import { atLeast } from "../../middleware/auth"
import { agentService } from "./service"

export const agentModule = createModule("Agent", "/agent")
const { route } = agentModule

const signalTrigger = z.enum(["any", "intent_topic", "website_visit", "hiring", "funding", "job_change", "tech_install", "social_engagement", "news"])
const action = z.enum(["rescore", "route_owner", "draft_outreach", "enroll_sequence", "create_deal", "notify", "enrich"])
const runStatus = z.enum(["completed", "awaiting_approval", "failed", "skipped"])
const draftStatus = z.enum(["pending", "approved", "rejected", "sent"])

// No defaults here: zod applies defaults even inside .partial(), which would clobber PATCHes.
const ruleFields = z.object({
  name: z.string().trim().min(1).max(120),
  description: z.string().max(1000),
  enabled: z.boolean(),
  trigger: signalTrigger,
  minScore: z.number().int().min(0).max(100),
  tiers: z.array(z.enum(["A", "B", "C", "D"])).min(1, "Select at least one tier"),
  actions: z.array(action).min(1),
  sequenceId: z.string().optional(),
  requireApproval: z.boolean(),
})
const ruleCreate = ruleFields.extend({
  description: z.string().max(1000).default(""),
  enabled: z.boolean().default(true),
  requireApproval: z.boolean().default(true),
})

// ---------- Settings ----------
route({
  method: "get",
  path: "/settings",
  summary: "Agent settings (autopilot)",
  handler: ({ orgId }) => agentService.getSettings(orgId),
})

route({
  method: "patch",
  path: "/settings",
  summary: "Turn autopilot on/off",
  body: z.object({ autopilot: z.boolean() }),
  handler: ({ orgId, body }) => agentService.setAutopilot(orgId, body.autopilot),
})

route({
  method: "get",
  path: "/stats",
  summary: "Run statistics",
  handler: ({ orgId }) => agentService.stats(orgId),
})

// ---------- Runs ----------
route({
  method: "get",
  path: "/runs",
  summary: "List agent runs (with account summary and playbook name)",
  query: listQuery.extend({ status: csvList.pipe(z.array(runStatus).optional()), accountId: z.string().optional() }),
  handler: async ({ orgId, query }) => {
    const page = await db.runs.list(orgId, {
      where: { status: query.status?.length ? { in: query.status } : undefined, accountId: query.accountId },
      sort: { field: "startedAt", dir: "desc" },
      page: query.page,
      pageSize: query.pageSize,
    })
    const rules = await db.playbooks.find(orgId)
    const items = (await withAccounts(orgId, page.items)).map((r) => ({
      ...r,
      ruleName: rules.find((x) => x.id === r.ruleId)?.name ?? null,
    }))
    return paged({ ...page, items })
  },
})

route({
  method: "get",
  path: "/runs/:id",
  summary: "Get a run with its signal, playbook and drafts",
  params: idParams,
  handler: async ({ orgId, params }) => {
    const run = await db.runs.get(orgId, params.id)
    if (!run) throw notFound("Run")
    const [[item], signal, rule, drafts] = await Promise.all([
      withAccounts(orgId, [run]),
      run.signalId ? db.signals.get(orgId, run.signalId) : null,
      run.ruleId ? db.playbooks.get(orgId, run.ruleId) : null,
      db.drafts.find(orgId, { runId: run.id }),
    ])
    return { ...item, ruleName: rule?.name ?? null, signal, drafts: await withContacts(orgId, drafts) }
  },
})

// ---------- Playbooks ----------
route({
  method: "get",
  path: "/playbooks",
  summary: "List playbooks",
  handler: async ({ orgId }) => {
    const [rules, seqs] = await Promise.all([db.playbooks.find(orgId, undefined, { field: "createdAt", dir: "asc" }), db.sequences.find(orgId)])
    return rules.map((r) => ({ ...r, sequenceName: seqs.find((s) => s.id === r.sequenceId)?.name ?? null }))
  },
})

route({
  method: "post",
  path: "/playbooks",
  summary: "Create a playbook",
  roles: atLeast("admin"),
  body: ruleCreate,
  handler: ({ orgId, body }) => agentService.createRule(orgId, body),
})

route({
  method: "patch",
  path: "/playbooks/:id",
  summary: "Update a playbook (e.g. enable/disable)",
  roles: atLeast("admin"),
  params: idParams,
  body: ruleFields.partial().extend({ sequenceId: z.string().nullable().optional() }),
  handler: ({ orgId, params, body }) => {
    const { sequenceId, ...rest } = body
    // null clears the sequence; omitted leaves it unchanged.
    return agentService.updateRule(orgId, params.id, sequenceId === undefined ? rest : { ...rest, sequenceId: sequenceId ?? undefined })
  },
})

route({
  method: "delete",
  path: "/playbooks/:id",
  summary: "Delete a playbook",
  roles: atLeast("admin"),
  params: idParams,
  handler: async ({ orgId, params }) => {
    if (!(await db.playbooks.remove(orgId, params.id))) throw notFound("Playbook")
  },
})

// ---------- Drafts ----------
route({
  method: "get",
  path: "/drafts",
  summary: "List outreach drafts (with account + contact)",
  query: listQuery.extend({ status: csvList.pipe(z.array(draftStatus).optional()) }),
  handler: async ({ orgId, query }) => {
    const page = await db.drafts.list(orgId, {
      where: { status: query.status?.length ? { in: query.status } : undefined },
      sort: { field: "createdAt", dir: "desc" },
      page: query.page,
      pageSize: query.pageSize,
    })
    return paged({ ...page, items: await withContacts(orgId, await withAccounts(orgId, page.items)) })
  },
})

route({
  method: "post",
  path: "/drafts/:id/approve",
  summary: "Approve (optionally edited) and send a draft",
  status: 200,
  params: idParams,
  body: z.object({ subject: z.string().min(1).max(300).optional(), body: z.string().min(1).max(20_000).optional() }),
  handler: ({ orgId, auth, params, body }) => agentService.approveDraft(orgId, auth.userId, params.id, body),
})

route({
  method: "post",
  path: "/drafts/:id/reject",
  summary: "Reject a draft",
  status: 200,
  params: idParams,
  handler: ({ orgId, params }) => agentService.rejectDraft(orgId, params.id),
})

route({
  method: "post",
  path: "/drafts/:id/regenerate",
  summary: "Regenerate a draft with the LLM provider",
  status: 200,
  params: idParams,
  handler: ({ orgId, params }) => agentService.regenerateDraft(orgId, params.id),
})
