// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import { ACTION_LABELS } from "../../domain/constants"
import type { AgentRun, AgentStep, OutreachDraft, PlaybookRule } from "../../domain/types"
import { badRequest, conflict, notFound } from "../../lib/errors"
import { newId, nowIso } from "../../lib/ids"
import { providers } from "../../providers/index"
import { activityService } from "../activities/service"
import { accountService } from "../accounts/service"
import { contactService } from "../contacts/service"
import { notificationService } from "../notifications/service"
import { enrollmentService } from "../outreach/enrollment"
import { pipelineService } from "../pipeline/service"
import { scoringService } from "../scoring/service"

const STEP_LABELS: Partial<Record<PlaybookRule["actions"][number], string>> = {
  draft_outreach: "Draft outreach with Claude",
  route_owner: "Route to account owner",
  enroll_sequence: "Enroll contacts in sequence",
  create_deal: "Create discovery deal",
  enrich: "Waterfall enrichment",
  notify: "Notify owner",
}

async function nextOwner(orgId: string) {
  const sellers = await db.users.find(orgId, { status: "active", role: { ne: "viewer" } })
  if (!sellers.length) return null
  const accounts = await db.accounts.find(orgId, { ownerId: { in: sellers.map((u) => u.id) } })
  const counts = sellers.map((u) => ({ u, n: accounts.filter((a) => a.ownerId === u.id).length }))
  counts.sort((a, b) => a.n - b.n)
  return counts[0].u
}

export const agentService = {
  async getSettings(orgId: string) {
    const org = await db.organizations.get(orgId, orgId)
    if (!org) throw notFound("Organization")
    return { autopilot: org.settings.autopilot }
  },

  async setAutopilot(orgId: string, autopilot: boolean) {
    const org = await db.organizations.get(orgId, orgId)
    if (!org) throw notFound("Organization")
    await db.organizations.update(orgId, orgId, { settings: { ...org.settings, autopilot } })
    return { autopilot }
  },

  /**
   * The orchestration loop: re-score → evaluate playbooks → execute the first matching
   * playbook's actions → record the run. Mirrors what EventBridge + Step Functions will do.
   */
  async processSignal(orgId: string, signalId: string): Promise<AgentRun> {
    const started = Date.now()
    const signal = await db.signals.get(orgId, signalId)
    if (!signal) throw notFound("Signal")
    const runId = newId("run")
    const { before, after } = await scoringService.rescoreAccount(orgId, signal.accountId, `Signal: ${signal.title}`)
    const account = await accountService.get(orgId, signal.accountId)
    const steps: AgentStep[] = []

    const candidates = await db.playbooks.find(orgId, { enabled: true, trigger: { in: ["any", signal.type] } })
    const rule = candidates.find((r) => account.score >= r.minScore && r.tiers.includes(account.tier))
    steps.push({
      action: "evaluate",
      label: "Evaluate signal against playbooks",
      status: "done",
      detail: rule
        ? `Matched “${rule.name}”`
        : candidates.length
          ? `${candidates.length} playbook(s) considered — score ${account.score} / Tier ${account.tier} below threshold`
          : "No enabled playbook for this signal type",
    })
    steps.push({ action: "rescore", label: "Re-score account", status: "done", detail: `${before} → ${after} (Tier ${account.tier})` })

    let status: AgentRun["status"] = rule ? "completed" : "skipped"
    if (rule) {
      for (const action of rule.actions.filter((a) => a !== "rescore")) {
        const label = STEP_LABELS[action] ?? ACTION_LABELS[action]
        try {
          if (action === "route_owner") {
            const current = await db.accounts.get(orgId, account.id)
            if (current?.ownerId) {
              const owner = await db.users.get(orgId, current.ownerId)
              steps.push({ action, label, status: "skipped", detail: `Already owned by ${owner?.name ?? "a teammate"}` })
            } else {
              const owner = await nextOwner(orgId)
              if (!owner) {
                steps.push({ action, label, status: "failed", detail: "No active sellers to route to" })
                continue
              }
              await accountService.assignOwner(orgId, [account.id], owner.id, "Agent routing")
              steps.push({ action, label, status: "done", detail: `Round-robin assigned to ${owner.name}` })
            }
          } else if (action === "enrich") {
            const r = await accountService.enrich(orgId, [account.id], "agent")
            steps.push({ action, label, status: "done", detail: `${r.results[0]?.sources.join(" → ") || "No providers"} refreshed` })
          } else if (action === "draft_outreach") {
            const contact = await contactService.bestContact(orgId, account.id)
            if (!contact) {
              steps.push({ action, label, status: "failed", detail: "No reachable contact on account" })
              continue
            }
            const current = await accountService.get(orgId, account.id)
            const sender = await db.users.get(orgId, current.ownerId ?? "")
            const draft = await providers.llm.draftOutreach({
              account: current,
              contact,
              signal,
              senderName: sender?.name.split(" ")[0] ?? "The team",
            })
            await db.drafts.create(orgId, {
              runId,
              accountId: account.id,
              contactId: contact.id,
              channel: signal.type === "job_change" ? "linkedin" : "email",
              subject: draft.subject,
              body: draft.body,
              rationale: `Tier ${current.tier} (score ${current.score}). Trigger: ${signal.source} — ${signal.title}. Chose ${contact.title || "this contact"} as the most senior reachable contact.`,
              status: rule.requireApproval ? "pending" : "sent",
              sequenceId: rule.sequenceId,
            })
            if (rule.requireApproval) {
              if (status !== "failed") status = "awaiting_approval" // a failure elsewhere in the run wins
              steps.push({ action, label, status: "pending", detail: `Draft for ${contact.firstName} ${contact.lastName} awaiting approval` })
            } else {
              await providers.email.send({ to: contact.email, subject: draft.subject, body: draft.body })
              await db.contacts.update(orgId, contact.id, { status: "in_sequence", lastContactedAt: nowIso() })
              steps.push({ action, label, status: "done", detail: `Sent to ${contact.firstName} ${contact.lastName}` })
            }
          } else if (action === "enroll_sequence") {
            const contact = await contactService.bestContact(orgId, account.id)
            const seq = rule.sequenceId ? await db.sequences.get(orgId, rule.sequenceId) : null
            if (!seq || !contact) {
              steps.push({ action, label, status: "failed", detail: !seq ? "Sequence not configured" : "No reachable contact" })
              status = "failed"
              continue
            }
            const r = await enrollmentService.enroll(orgId, [contact.id], seq.id)
            steps.push({
              action,
              label,
              status: r.enrolled ? "done" : "skipped",
              detail: r.enrolled ? `${contact.firstName} ${contact.lastName} → “${seq.name}”` : "Contact already enrolled or not eligible",
            })
          } else if (action === "create_deal") {
            const open = await db.deals.findOne(orgId, { accountId: account.id, stage: { nin: ["closed_won", "closed_lost"] } })
            if (open) {
              steps.push({ action, label, status: "skipped", detail: `Open deal exists: ${open.name}` })
            } else {
              const current = await accountService.get(orgId, account.id)
              await pipelineService.create(orgId, "agent", {
                name: `${current.name} – Discovery`,
                accountId: current.id,
                amount: Math.round((current.employees * 40) / 1000) * 1000 || 12_000,
                stage: "discovery",
                closeDate: new Date(Date.now() + 45 * 86_400_000).toISOString(),
                source: `Agent: ${signal.type.replace(/_/g, " ")}`,
                ownerId: current.ownerId ?? undefined,
              })
              steps.push({ action, label, status: "done", detail: "Discovery deal opened" })
            }
          } else if (action === "notify") {
            const current = await accountService.get(orgId, account.id)
            await notificationService.notify(orgId, {
              kind: "agent",
              title: `${current.name}: ${signal.title}`,
              body: `Tier ${current.tier} · score ${current.score}. ${rule.name}.`,
              href: `/accounts/${current.id}`,
            })
            steps.push({ action, label, status: "done", detail: "Owner notified" })
          }
        } catch (err) {
          status = "failed"
          steps.push({ action, label, status: "failed", detail: (err as Error).message })
        }
      }
      await db.playbooks.update(orgId, rule.id, { runs: rule.runs + 1 })
    }

    const run = await db.runs.create(orgId, {
      id: runId,
      signalId,
      accountId: account.id,
      ruleId: rule?.id,
      trigger: `${signal.source}: ${signal.title}`,
      startedAt: new Date(started).toISOString(),
      durationMs: Date.now() - started,
      status,
      steps,
      scoreBefore: before,
      scoreAfter: after,
    })
    await db.signals.update(orgId, signalId, { processed: true })
    await activityService.log(orgId, {
      accountId: account.id,
      type: "agent",
      title: rule ? `Agent ran “${rule.name}”` : "Agent evaluated signal",
      detail: steps.map((s) => s.label).join(" → "),
      actorId: "agent",
    })
    return run
  },

  async processPending(orgId: string) {
    const pending = await db.signals.find(orgId, { processed: false }, { field: "occurredAt", dir: "asc" })
    const runs = []
    for (const s of pending) runs.push(await this.processSignal(orgId, s.id))
    return { processed: runs.length, runs }
  },

  // ---------- Playbooks ----------
  async validateRule(orgId: string, rule: Partial<PlaybookRule>) {
    if (rule.actions?.includes("enroll_sequence") && !rule.sequenceId) {
      throw badRequest("Pick a sequence for the “Enroll in sequence” action")
    }
    if (rule.sequenceId && !(await db.sequences.get(orgId, rule.sequenceId))) throw badRequest("Sequence not found")
  },

  async createRule(orgId: string, input: Omit<PlaybookRule, "id" | "runs">) {
    await this.validateRule(orgId, input)
    const actions = [...new Set(["rescore" as const, ...input.actions])]
    return db.playbooks.create(orgId, { ...input, actions, runs: 0 })
  },

  async updateRule(orgId: string, id: string, patch: Partial<PlaybookRule>) {
    const cur = await db.playbooks.get(orgId, id)
    if (!cur) throw notFound("Playbook")
    await this.validateRule(orgId, { ...cur, ...patch })
    if (patch.actions) patch.actions = [...new Set(["rescore" as const, ...patch.actions])]
    return db.playbooks.update(orgId, id, patch)
  },

  // ---------- Drafts ----------
  async getDraft(orgId: string, id: string) {
    const d = await db.drafts.get(orgId, id)
    if (!d) throw notFound("Draft")
    return d
  },

  async resolveRunStep(orgId: string, runId: string | undefined, outcome: "done" | "skipped", detail: string) {
    if (!runId) return
    const run = await db.runs.get(orgId, runId)
    if (!run) return
    await db.runs.update(orgId, runId, {
      status: run.status === "awaiting_approval" ? "completed" : run.status,
      steps: run.steps.map((s) => (s.status === "pending" ? { ...s, status: outcome, detail } : s)),
    })
  },

  async approveDraft(orgId: string, actorId: string, id: string, edits: Partial<Pick<OutreachDraft, "subject" | "body">>) {
    const d = await this.getDraft(orgId, id)
    if (d.status !== "pending") throw conflict(`Draft is already ${d.status}`)
    const contact = await contactService.get(orgId, d.contactId)
    const actor = await db.users.get(orgId, actorId)
    const subject = edits.subject ?? d.subject
    const body = edits.body ?? d.body
    await providers.email.send({ to: contact.email, subject, body })
    const draft = await db.drafts.update(orgId, id, { subject, body, status: "sent" })
    await this.resolveRunStep(orgId, d.runId, "done", `Approved & sent by ${actor?.name ?? "reviewer"}`)
    await db.contacts.update(orgId, contact.id, { status: "in_sequence", lastContactedAt: nowIso() })
    const enrollment = d.sequenceId ? await enrollmentService.enroll(orgId, [contact.id], d.sequenceId).catch(() => null) : null
    await activityService.log(orgId, {
      accountId: d.accountId,
      contactId: d.contactId,
      type: d.channel === "email" ? "email" : "note",
      title: `Sent: ${subject}`,
      detail: "Agent draft approved",
      actorId,
    })
    return { draft, contact: { id: contact.id, name: `${contact.firstName} ${contact.lastName}` }, enrollment }
  },

  async rejectDraft(orgId: string, id: string) {
    const d = await this.getDraft(orgId, id)
    if (d.status !== "pending") throw conflict(`Draft is already ${d.status}`)
    const draft = await db.drafts.update(orgId, id, { status: "rejected" })
    await this.resolveRunStep(orgId, d.runId, "skipped", "Draft rejected by reviewer")
    return draft
  },

  async regenerateDraft(orgId: string, id: string) {
    const d = await this.getDraft(orgId, id)
    if (d.status !== "pending") throw conflict(`Draft is already ${d.status}`)
    const [account, contact] = await Promise.all([accountService.get(orgId, d.accountId), contactService.get(orgId, d.contactId)])
    const sender = await db.users.get(orgId, account.ownerId ?? "")
    const out = await providers.llm.draftOutreach({ account, contact, senderName: sender?.name.split(" ")[0] ?? "The team" })
    return db.drafts.update(orgId, id, out)
  },

  async stats(orgId: string) {
    const [runs, pending] = await Promise.all([db.runs.find(orgId), db.drafts.count(orgId, { status: "pending" })])
    const dayAgo = Date.now() - 86_400_000
    const weekAgo = Date.now() - 7 * 86_400_000
    const completed = runs.filter((r) => r.status === "completed").length
    const failed = runs.filter((r) => r.status === "failed").length
    return {
      runsToday: runs.filter((r) => new Date(r.startedAt).getTime() > dayAgo).length,
      runs7d: runs.filter((r) => new Date(r.startedAt).getTime() > weekAgo).length,
      totalRuns: runs.length,
      actionsTaken: runs.reduce((s, r) => s + r.steps.filter((st) => st.status === "done" && st.action !== "evaluate").length, 0),
      awaitingApproval: pending,
      completed,
      failed,
      successRate: completed + failed ? Math.round((completed / (completed + failed)) * 1000) / 10 : 100,
      byStatus: ["completed", "awaiting_approval", "failed", "skipped"].map((s) => ({ status: s, count: runs.filter((r) => r.status === s).length })),
    }
  },
}
