// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { db } from "../../db/index"
import { badRequest } from "../../lib/errors"
import { createModule, csvList, paged } from "../../lib/http"
import { activityService } from "./service"

export const activitiesModule = createModule("Activities", "/activities")
const { route } = activitiesModule

const type = z.enum(["note", "email", "call", "meeting", "stage_change", "enrichment", "score_change", "agent", "signal"])

route({
  method: "get",
  path: "/",
  summary: "List activities",
  query: z.object({
    accountId: z.string().optional(),
    contactId: z.string().optional(),
    dealId: z.string().optional(),
    type: csvList,
    page: z.coerce.number().int().min(1).default(1),
    pageSize: z.coerce.number().int().min(1).max(200).default(50),
  }),
  handler: async ({ orgId, query }) => paged(await activityService.list(orgId, query)),
})

route({
  method: "post",
  path: "/",
  summary: "Log a note, call, meeting or email",
  body: z
    .object({
      type: type.default("note"),
      title: z.string().trim().min(1).max(300),
      detail: z.string().max(5000).optional(),
      accountId: z.string().optional(),
      contactId: z.string().optional(),
      dealId: z.string().optional(),
      at: z.iso.datetime().optional(),
    })
    .refine((b) => b.accountId || b.contactId || b.dealId, { message: "Link the activity to an account, contact or deal" }),
  handler: async ({ orgId, auth, body }) => {
    if (body.accountId && !(await db.accounts.get(orgId, body.accountId))) throw badRequest("Account not found")
    if (body.contactId && !(await db.contacts.get(orgId, body.contactId))) throw badRequest("Contact not found")
    if (body.dealId && !(await db.deals.get(orgId, body.dealId))) throw badRequest("Deal not found")
    return activityService.log(orgId, { ...body, actorId: auth.userId })
  },
})
