// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import type { Activity } from "../../domain/types"
import { nowIso } from "../../lib/ids"

export type ActivityInput = Omit<Activity, "id" | "at"> & { at?: string }

export const activityService = {
  log(orgId: string, input: ActivityInput) {
    return db.activities.create(orgId, { ...input, at: input.at ?? nowIso() })
  },

  logMany(orgId: string, inputs: ActivityInput[]) {
    if (!inputs.length) return Promise.resolve([])
    const at = nowIso()
    return db.activities.createMany(
      orgId,
      inputs.map((i) => ({ ...i, at: i.at ?? at })),
    )
  },

  list(orgId: string, filter: { accountId?: string; contactId?: string; dealId?: string; type?: string[]; page: number; pageSize: number }) {
    return db.activities.list(orgId, {
      where: {
        accountId: filter.accountId,
        contactId: filter.contactId,
        dealId: filter.dealId,
        type: filter.type ? { in: filter.type as Activity["type"][] } : undefined,
      },
      sort: { field: "at", dir: "desc" },
      page: filter.page,
      pageSize: filter.pageSize,
    })
  },
}
