// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import type { Account, IcpConfig, Signal, Tier } from "../../domain/types"

const clamp = (n: number, min = 0, max = 100) => Math.max(min, Math.min(max, n))

export interface FitBreakdown {
  label: string
  points: number
  max: number
  matched: boolean
  detail: string
}

/** Fit score: how well an account matches the org's ICP definition (0-100). */
export function fitBreakdown(account: Account, icp: IcpConfig): FitBreakdown[] {
  const industry = icp.industries.includes(account.industry)
  const country = icp.countries.includes(account.country)
  const sizeOk = account.employees >= icp.employeeMin && account.employees <= icp.employeeMax
  const nearSize =
    !sizeOk && account.employees >= icp.employeeMin * 0.5 && account.employees <= icp.employeeMax * 1.5
  const revenueOk = account.revenue >= icp.revenueMin
  const techMatches = account.technologies.filter((t) => icp.technologies.includes(t))
  const funding = icp.fundingStages.includes(account.fundingStage)

  return [
    { label: "Industry", max: 25, matched: industry, points: industry ? 25 : 0, detail: account.industry },
    {
      label: "Company size",
      max: 20,
      matched: sizeOk,
      points: sizeOk ? 20 : nearSize ? 8 : 0,
      detail: `${account.employees.toLocaleString()} employees`,
    },
    { label: "Geography", max: 15, matched: country, points: country ? 15 : 0, detail: account.country },
    {
      label: "Revenue",
      max: 15,
      matched: revenueOk,
      points: revenueOk ? 15 : 0,
      detail: `$${(account.revenue / 1_000_000).toFixed(1)}M`,
    },
    {
      label: "Tech stack",
      max: 15,
      matched: techMatches.length > 0,
      points: Math.min(15, techMatches.length * 5),
      detail: techMatches.length ? techMatches.join(", ") : "No matching tech",
    },
    { label: "Funding stage", max: 10, matched: funding, points: funding ? 10 : 0, detail: account.fundingStage },
  ]
}

export function computeFit(account: Account, icp: IcpConfig) {
  return clamp(fitBreakdown(account, icp).reduce((s, b) => s + b.points, 0))
}

/** Intent score: weighted, time-decayed sum of recent signals (0-100). */
export function computeIntent(signals: Signal[], icp: IcpConfig, now = Date.now()) {
  let total = 0
  for (const s of signals) {
    const ageDays = (now - new Date(s.occurredAt).getTime()) / 86_400_000
    if (ageDays > icp.intentDecayDays * 3) continue
    const decay = Math.pow(0.5, ageDays / icp.intentDecayDays)
    const weight = (icp.signalWeights[s.type] ?? 50) / 100
    total += s.strength * weight * decay * 0.45
  }
  return Math.round(clamp(total))
}

export function combineScore(fit: number, intent: number, icp: IcpConfig) {
  const w = icp.fitWeight / 100
  return Math.round(fit * w + intent * (1 - w))
}

export function tierFor(score: number, icp: IcpConfig): Tier {
  if (score >= icp.tierThresholds.A) return "A"
  if (score >= icp.tierThresholds.B) return "B"
  if (score >= icp.tierThresholds.C) return "C"
  return "D"
}

export function scoreAccount(account: Account, signals: Signal[], icp: IcpConfig) {
  const fit = computeFit(account, icp)
  const intent = computeIntent(
    signals.filter((s) => s.accountId === account.id),
    icp,
  )
  const score = combineScore(fit, intent, icp)
  return { fit, intent, score, tier: tierFor(score, icp) }
}
