// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { defaultIcp } from "../../domain/constants"
import type { IcpConfig } from "../../domain/types"
import { createModule } from "../../lib/http"
import { nowIso } from "../../lib/ids"
import { atLeast } from "../../middleware/auth"
import { scoringService } from "./service"

export const scoringModule = createModule("ICP & Scoring", "/icp")
const { route } = scoringModule

const weight = z.number().min(0).max(100)

export const icpSchema = z
  .object({
    industries: z.array(z.string()).min(1, "Select at least one industry"),
    countries: z.array(z.string()),
    employeeMin: z.number().int().min(0),
    employeeMax: z.number().int().min(0),
    revenueMin: z.number().min(0),
    technologies: z.array(z.string()),
    fundingStages: z.array(z.string()),
    fitWeight: weight,
    signalWeights: z.object({
      intent_topic: weight,
      website_visit: weight,
      hiring: weight,
      funding: weight,
      job_change: weight,
      tech_install: weight,
      social_engagement: weight,
      news: weight,
    }),
    intentDecayDays: z.number().min(1).max(365),
    tierThresholds: z.object({ A: weight, B: weight, C: weight }),
  })
  .refine((c) => c.employeeMin <= c.employeeMax, { message: "Min employees must be ≤ max", path: ["employeeMin"] })
  .refine((c) => c.tierThresholds.A > c.tierThresholds.B && c.tierThresholds.B > c.tierThresholds.C, {
    message: "Tier thresholds must satisfy A > B > C",
    path: ["tierThresholds"],
  })

route({
  method: "get",
  path: "/",
  summary: "Get the organization's ICP configuration",
  handler: ({ orgId }) => scoringService.getIcp(orgId),
})

route({
  method: "put",
  path: "/",
  summary: "Replace the ICP configuration and re-score every account",
  roles: atLeast("admin"),
  body: icpSchema,
  handler: ({ orgId, body }) => scoringService.updateIcp(orgId, body),
})

route({
  method: "post",
  path: "/preview",
  summary: "Preview scores/tiers under a draft ICP (nothing is saved)",
  status: 200,
  roles: atLeast("viewer"),
  body: z.object({ icp: icpSchema, top: z.number().int().min(1).max(100).default(10) }),
  handler: ({ orgId, body }) => scoringService.preview(orgId, { ...(body.icp as IcpConfig), updatedAt: nowIso() }, body.top),
})

route({
  method: "get",
  path: "/defaults",
  summary: "Default ICP configuration (for 'reset to defaults')",
  handler: () => defaultIcp(nowIso()),
})
