// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import { defaultIcp } from "../../domain/constants"
import type { Account, IcpConfig, Stored, Tier } from "../../domain/types"
import { DAY_MS, nowIso } from "../../lib/ids"
import { activityService } from "../activities/service"
import { combineScore, computeIntent, fitBreakdown, scoreAccount } from "./engine"

const HISTORY_LIMIT = 20

export const scoringService = {
  async getIcp(orgId: string): Promise<IcpConfig> {
    const found = await db.icp.get(orgId, orgId)
    if (found) return found
    return db.icp.create(orgId, { ...defaultIcp(nowIso()), id: orgId })
  },

  async updateIcp(orgId: string, patch: Partial<IcpConfig>) {
    const cur = await this.getIcp(orgId)
    const icp = await db.icp.update(orgId, orgId, { ...cur, ...patch, id: orgId, updatedAt: nowIso() })
    const changed = await this.rescoreAll(orgId, "ICP configuration updated")
    return { icp, changed }
  },

  /** Recomputes one account's score; appends history + activity when it changes. */
  async rescoreAccount(orgId: string, accountId: string, reason: string) {
    const [account, icp, signals] = await Promise.all([
      db.accounts.get(orgId, accountId),
      this.getIcp(orgId),
      db.signals.find(orgId, { accountId }),
    ])
    if (!account) return { before: 0, after: 0, tier: "D" as Tier, account: null }
    const sc = scoreAccount(account, signals, icp)
    const updated = await db.accounts.update(orgId, accountId, {
      fitScore: sc.fit,
      intentScore: sc.intent,
      score: sc.score,
      tier: sc.tier,
      scoreHistory: [...account.scoreHistory, { at: nowIso(), fit: sc.fit, intent: sc.intent, score: sc.score, reason }].slice(-HISTORY_LIMIT),
    })
    if (sc.score !== account.score) {
      await activityService.log(orgId, {
        accountId,
        type: "score_change",
        title: `Score ${account.score} → ${sc.score} (Tier ${sc.tier})`,
        detail: reason,
        actorId: "system",
      })
    }
    return { before: account.score, after: sc.score, tier: sc.tier, account: updated }
  },

  async rescoreMany(orgId: string, ids: string[], reason: string) {
    const results = []
    for (const id of ids) results.push({ id, ...(await this.rescoreAccount(orgId, id, reason)) })
    return results.map(({ id, before, after, tier }) => ({ id, before, after, tier }))
  },

  /** Bulk recompute for every account; returns how many changed score or tier. */
  async rescoreAll(orgId: string, reason: string) {
    const [icp, accounts, signals] = await Promise.all([this.getIcp(orgId), db.accounts.find(orgId), db.signals.find(orgId)])
    const byAccount = groupBy(signals, (s) => s.accountId)
    const now = nowIso()
    let changed = 0
    const next = new Map<string, ReturnType<typeof scoreAccount>>()
    for (const a of accounts) {
      const sc = scoreAccount(a, byAccount.get(a.id) ?? [], icp)
      if (sc.score !== a.score || sc.tier !== a.tier) changed++
      next.set(a.id, sc)
    }
    await db.accounts.updateMany(orgId, {}, (a) => {
      const sc = next.get(a.id)!
      return {
        fitScore: sc.fit,
        intentScore: sc.intent,
        score: sc.score,
        tier: sc.tier,
        scoreHistory: [...a.scoreHistory, { at: now, fit: sc.fit, intent: sc.intent, score: sc.score, reason }].slice(-HISTORY_LIMIT),
      }
    })
    return changed
  },

  /** Scores for a draft ICP without persisting anything. */
  async preview(orgId: string, draft: IcpConfig, top = 10) {
    const [accounts, signals, current] = await Promise.all([
      db.accounts.find(orgId, { duplicateOf: { exists: false } }),
      db.signals.find(orgId),
      this.getIcp(orgId),
    ])
    const byAccount = groupBy(signals, (s) => s.accountId)
    const tiers: Tier[] = ["A", "B", "C", "D"]
    const dist = Object.fromEntries(tiers.map((t) => [t, { tier: t, current: 0, draft: 0 }])) as Record<Tier, { tier: Tier; current: number; draft: number }>
    let promoted = 0
    let demoted = 0
    let sumCurrent = 0
    let sumDraft = 0
    const rows = accounts.map((a) => {
      const cur = scoreAccount(a, byAccount.get(a.id) ?? [], current)
      const nxt = scoreAccount(a, byAccount.get(a.id) ?? [], draft)
      dist[cur.tier].current++
      dist[nxt.tier].draft++
      if (nxt.tier < cur.tier) promoted++
      if (nxt.tier > cur.tier) demoted++
      sumCurrent += cur.score
      sumDraft += nxt.score
      return { id: a.id, name: a.name, domain: a.domain, industry: a.industry, currentScore: cur.score, currentTier: cur.tier, score: nxt.score, tier: nxt.tier, delta: nxt.score - cur.score }
    })
    rows.sort((a, b) => b.score - a.score)
    const n = accounts.length || 1
    return {
      total: accounts.length,
      distribution: tiers.map((t) => dist[t]),
      tierChanges: promoted + demoted,
      promoted,
      demoted,
      avgCurrent: Math.round(sumCurrent / n),
      avgDraft: Math.round(sumDraft / n),
      top: rows.slice(0, top),
    }
  },

  async breakdown(orgId: string, account: Stored<Account>) {
    const [icp, signals] = await Promise.all([
      this.getIcp(orgId),
      db.signals.find(orgId, { accountId: account.id }, { field: "occurredAt", dir: "desc" }),
    ])
    const now = Date.now()
    const contributors = signals
      .map((s) => {
        const ageDays = (now - new Date(s.occurredAt).getTime()) / DAY_MS
        const decay = ageDays > icp.intentDecayDays * 3 ? 0 : Math.pow(0.5, ageDays / icp.intentDecayDays)
        const weight = (icp.signalWeights[s.type] ?? 50) / 100
        return { signal: s, weight, decay, points: Math.round(s.strength * weight * decay * 0.45 * 10) / 10 }
      })
      .filter((c) => c.points > 0)
      .slice(0, 20)
    const fit = fitBreakdown(account, icp)
    const fitTotal = fit.reduce((s, b) => s + b.points, 0)
    const intent = computeIntent(signals, icp)
    return {
      fit,
      fitScore: Math.min(100, fitTotal),
      intentScore: intent,
      score: combineScore(Math.min(100, fitTotal), intent, icp),
      fitWeight: icp.fitWeight,
      intentDecayDays: icp.intentDecayDays,
      contributors,
    }
  },
}

export function groupBy<T, K>(items: T[], key: (t: T) => K) {
  const m = new Map<K, T[]>()
  for (const i of items) {
    const k = key(i)
    const arr = m.get(k)
    if (arr) arr.push(i)
    else m.set(k, [i])
  }
  return m
}
