// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import bcrypt from "bcryptjs"
import { db } from "../db/index"
import { defaultIcp, INTEGRATION_CATALOG } from "../domain/constants"
import type { Stored } from "../domain/types"
import { nowIso, randomHex } from "../lib/ids"
import { generateSeed } from "./generate"

/** Password given to the demo teammates created by seedDemoData. */
export const DEMO_MEMBER_PASSWORD = "Password123!"

/** Collections that hold tenant business data (not org, users, API keys, preferences). */
const DATA_COLLECTIONS = [
  db.accounts,
  db.contacts,
  db.signals,
  db.playbooks,
  db.runs,
  db.drafts,
  db.sequences,
  db.enrollments,
  db.mailboxes,
  db.inbox,
  db.deals,
  db.activities,
  db.notifications,
] as const

/** Removes all business data for an org and restores default ICP + disconnected integration catalog. */
export async function clearOrgData(orgId: string) {
  for (const repo of DATA_COLLECTIONS) await repo.removeMany(orgId, {})
  await db.icp.removeMany(orgId, {})
  await db.icp.create(orgId, { ...defaultIcp(nowIso()), id: orgId })
  await db.integrations.removeMany(orgId, {})
  await db.integrations.createMany(
    orgId,
    INTEGRATION_CATALOG.map((c) => ({
      ...c,
      connected: false,
      status: "disconnected" as const,
      settings: {
        autoSync: true,
        syncInterval: "hourly",
        writeBack: c.category === "crm",
        ...(c.category === "enrichment" || c.category === "contacts" ? { useInWaterfall: true } : {}),
        ...(c.category === "llm" ? { model: "claude-opus-5", tokenBudget: "5000" } : {}),
      },
    })),
  )
  const org = await db.organizations.get(orgId, orgId)
  if (org) await db.organizations.update(orgId, orgId, { settings: { ...org.settings, autopilot: true } })
}

type WithTimestamps = { id: string; createdAt?: string; updatedAt?: string }

/**
 * Loads the demo dataset into an org. The org's `ownerId` user plays "Jordan Lee"
 * (usr_1); the other demo teammates are created as real users (password DEMO_MEMBER_PASSWORD).
 */
export async function seedDemoData(orgId: string, ownerId: string) {
  const org = await db.organizations.get(orgId, orgId)
  if (!org) throw new Error(`Organization ${orgId} not found`)
  const seed = generateSeed()
  const suffix = randomHex(3)

  // ---- users: map demo usr_N → real users in this org ----
  const userMap = new Map<string, string>([["usr_1", ownerId]])
  const passwordHash = await bcrypt.hash(DEMO_MEMBER_PASSWORD, 10)
  const existing = await db.users.find(orgId)
  for (const u of seed.users.slice(1)) {
    const email = `${u.email.split("@")[0]}@${org.domain}`
    const found = existing.find((e) => e.email === email) ?? (await db.users.findGlobal({ email }))
    if (found) {
      userMap.set(u.id, found.orgId === orgId ? found.id : ownerId)
      continue
    }
    const created = await db.users.create(orgId, {
      name: u.name,
      email,
      role: u.role,
      title: u.title,
      status: u.status,
      avatarColor: u.avatarColor,
      lastActiveAt: u.lastActiveAt,
      passwordHash: u.status === "active" ? passwordHash : undefined,
      inviteToken: u.status === "invited" ? `inv_demo_${suffix}_${u.id}` : undefined,
    })
    userMap.set(u.id, created.id)
  }

  // ---- remap every placeholder id (acc_1, con_2, …) to a unique id for this org ----
  const idPattern = /\b(acc|acc_dup|con|sig|rule|seq|mb|msg|deal|run|drf|act|enr|ntf)_([0-9]+)\b/g
  const remapped = JSON.parse(
    JSON.stringify({
      accounts: seed.accounts,
      contacts: seed.contacts,
      signals: seed.signals,
      rules: seed.rules,
      runs: seed.runs,
      drafts: seed.drafts,
      sequences: seed.sequences,
      enrollments: seed.enrollments,
      mailboxes: seed.mailboxes,
      inbox: seed.inbox,
      deals: seed.deals,
      activities: seed.activities,
      notifications: seed.notifications,
    })
      .replace(idPattern, (_m, p: string, n: string) => `${p}_${n}${suffix}`)
      .replace(/"usr_\d+"/g, (m) => JSON.stringify(userMap.get(JSON.parse(m)) ?? ownerId)),
  ) as Omit<typeof seed, "org" | "currentUserId" | "users" | "apiKeys" | "icp" | "integrations">

  const withTimes = <T extends WithTimestamps>(rows: T[], at: (r: T) => string | undefined) =>
    rows.map((r) => {
      const ts = at(r) ?? nowIso()
      return { ...r, createdAt: r.createdAt ?? ts, updatedAt: r.updatedAt ?? ts } as T & { createdAt: string; updatedAt: string }
    })
  const insert = async <T extends { id: string }>(repo: { createMany: (orgId: string, rows: never[]) => Promise<Stored<T>[]> }, rows: unknown[]) =>
    (await repo.createMany(orgId, rows as never[])).length

  const counts = {
    accounts: await insert(db.accounts, remapped.accounts),
    contacts: await insert(db.contacts, remapped.contacts),
    signals: await insert(db.signals, withTimes(remapped.signals, (s) => s.occurredAt)),
    sequences: await insert(db.sequences, remapped.sequences),
    playbooks: await insert(db.playbooks, withTimes(remapped.rules, () => undefined)),
    runs: await insert(db.runs, withTimes(remapped.runs, (r) => r.startedAt)),
    drafts: await insert(db.drafts, remapped.drafts),
    enrollments: await insert(db.enrollments, withTimes(remapped.enrollments, (e) => e.enrolledAt)),
    mailboxes: await insert(db.mailboxes, withTimes(remapped.mailboxes, () => undefined)),
    inbox: await insert(db.inbox, withTimes(remapped.inbox, (m) => m.receivedAt)),
    deals: await insert(db.deals, remapped.deals),
    activities: await insert(db.activities, withTimes(remapped.activities, (a) => a.at)),
    notifications: await insert(db.notifications, withTimes(remapped.notifications, (n) => n.at)),
  }

  // Integrations: apply the demo connection state onto the org's catalog records.
  const ints = await db.integrations.find(orgId)
  for (const demo of seed.integrations) {
    const rec = ints.find((i) => i.key === demo.key)
    if (!rec) continue
    await db.integrations.update(orgId, rec.id, {
      connected: demo.connected,
      status: demo.status,
      lastSyncAt: demo.lastSyncAt,
      apiKeyMasked: demo.apiKeyMasked,
      usage: demo.usage,
      settings: demo.settings,
    })
  }
  await db.icp.update(orgId, orgId, { ...seed.icp, id: orgId })
  return counts
}
