// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import type {
  AccountStage,
  AgentActionType,
  DealStage,
  IcpConfig,
  Integration,
  SignalType,
  StepChannel,
} from "./types"

// Business constants shared by services and served to clients via GET /meta.

export const INDUSTRIES = [
  "SaaS",
  "Fintech",
  "Healthcare",
  "E-commerce",
  "Cybersecurity",
  "Logistics",
  "Manufacturing",
  "EdTech",
  "Media",
  "Real Estate",
]

export const COUNTRIES = ["United States", "United Kingdom", "Germany", "Canada", "India", "Australia", "France", "Netherlands"]

export const TECHNOLOGIES = [
  "Salesforce",
  "HubSpot",
  "Snowflake",
  "AWS",
  "GCP",
  "Segment",
  "Stripe",
  "Zendesk",
  "Intercom",
  "Marketo",
  "Outreach",
  "Gong",
  "Slack",
  "Okta",
]

export const FUNDING_STAGES = ["Bootstrapped", "Seed", "Series A", "Series B", "Series C", "Series D+", "Public"]

export const SIGNAL_LABELS: Record<SignalType, string> = {
  intent_topic: "Intent topic",
  website_visit: "Website visit",
  hiring: "Hiring",
  funding: "Funding",
  job_change: "Job change",
  tech_install: "Tech install",
  social_engagement: "Social engagement",
  news: "News",
}

export const SIGNAL_SOURCES: Record<SignalType, string[]> = {
  intent_topic: ["Bombora"],
  website_visit: ["RB2B"],
  hiring: ["Apify", "Linkup"],
  funding: ["Linkup", "Apollo.io"],
  job_change: ["Trigify.io", "Apollo.io"],
  tech_install: ["Clearbit", "Apify"],
  social_engagement: ["Trigify.io"],
  news: ["Linkup"],
}

export const STAGE_LABELS: Record<AccountStage, string> = {
  new: "New",
  researching: "Researching",
  engaged: "Engaged",
  opportunity: "Opportunity",
  customer: "Customer",
  disqualified: "Disqualified",
}

export const DEAL_STAGES: { id: DealStage; label: string; probability: number }[] = [
  { id: "discovery", label: "Discovery", probability: 10 },
  { id: "qualified", label: "Qualified", probability: 25 },
  { id: "demo", label: "Demo", probability: 40 },
  { id: "proposal", label: "Proposal", probability: 60 },
  { id: "negotiation", label: "Negotiation", probability: 80 },
  { id: "closed_won", label: "Closed won", probability: 100 },
  { id: "closed_lost", label: "Closed lost", probability: 0 },
]

export const ACTION_LABELS: Record<AgentActionType, string> = {
  rescore: "Re-score account",
  route_owner: "Route to owner",
  draft_outreach: "Draft outreach",
  enroll_sequence: "Enroll in sequence",
  create_deal: "Create deal",
  notify: "Notify owner",
  enrich: "Enrich account",
}

export const STEP_CHANNEL_LABELS: Record<StepChannel, string> = {
  email: "Email",
  linkedin_connect: "LinkedIn connect",
  linkedin_message: "LinkedIn message",
  call: "Call task",
  wait: "Wait",
}

export const API_SCOPES = ["accounts:read", "accounts:write", "signals:write", "outreach:read", "outreach:write", "pipeline:read", "pipeline:write"]

export const DEAL_STAGE_LABEL = Object.fromEntries(DEAL_STAGES.map((s) => [s.id, s.label])) as Record<DealStage, string>

export const SENIORITY_ORDER = ["C-Level", "VP", "Director", "Manager", "IC"] as const

export type IntegrationCatalogEntry = Pick<Integration, "key" | "name" | "category" | "description" | "feeds">

export const INTEGRATION_CATALOG: IntegrationCatalogEntry[] = [
  { key: "clearbit", name: "Clearbit", category: "enrichment", description: "Firmographic and technographic company enrichment.", feeds: "Entity service" },
  { key: "apollo", name: "Apollo.io", category: "contacts", description: "B2B contact database and TAM sourcing API.", feeds: "Entity service" },
  { key: "fullenrich", name: "FullEnrich", category: "enrichment", description: "Waterfall email & phone enrichment across 15+ providers.", feeds: "Entity service" },
  { key: "prospeo", name: "Prospeo", category: "enrichment", description: "Email finder and verifier from LinkedIn URLs.", feeds: "Entity service" },
  { key: "limadata", name: "Limadata", category: "contacts", description: "Real-time person and company data.", feeds: "Entity service" },
  { key: "bombora", name: "Bombora", category: "intent", description: "Company surge intent data across B2B topics.", feeds: "Signal ingestion" },
  { key: "rb2b", name: "RB2B", category: "intent", description: "Person-level website visitor identification.", feeds: "Signal ingestion" },
  { key: "trigify", name: "Trigify.io", category: "intent", description: "Social engagement and job-change signals.", feeds: "Signal ingestion" },
  { key: "apify", name: "Apify", category: "scraping", description: "Scrape job boards, websites and review sites.", feeds: "Entity service" },
  { key: "linkup", name: "Linkup", category: "scraping", description: "Web search API for news and account research.", feeds: "Entity service" },
  { key: "ses", name: "AWS SES", category: "email", description: "Transactional and outbound email sending.", feeds: "Outreach service" },
  { key: "mailpool", name: "Mailpool", category: "email", description: "Managed inboxes with warm-up and deliverability.", feeds: "Outreach service" },
  { key: "instantly", name: "Instantly.ai", category: "email", description: "Cold email infrastructure with warm-up network.", feeds: "Outreach service" },
  { key: "heyreach", name: "HeyReach", category: "linkedin", description: "LinkedIn automation across multiple sender accounts.", feeds: "Outreach service" },
  { key: "fireflies", name: "Fireflies.ai", category: "calls", description: "Call recording, transcription and insights.", feeds: "Analytics" },
  { key: "hubspot", name: "HubSpot", category: "crm", description: "Bi-directional sync of companies, contacts and deals.", feeds: "CRM/Pipeline" },
  { key: "attio", name: "Attio", category: "crm", description: "Sync records and lists with Attio.", feeds: "CRM/Pipeline" },
  { key: "salesforce", name: "Salesforce", category: "crm", description: "Enterprise CRM sync for accounts, leads and opportunities.", feeds: "CRM/Pipeline" },
  { key: "anthropic", name: "Anthropic (Claude)", category: "llm", description: "Powers agentic scoring, research and outreach drafting.", feeds: "Scoring + orchestration" },
]

export function defaultIcp(now: string): IcpConfig {
  return {
    industries: ["SaaS", "Fintech", "Cybersecurity", "E-commerce"],
    countries: ["United States", "United Kingdom", "Canada", "Germany"],
    employeeMin: 50,
    employeeMax: 2000,
    revenueMin: 5_000_000,
    technologies: ["Salesforce", "HubSpot", "Snowflake", "Segment", "Outreach"],
    fundingStages: ["Series A", "Series B", "Series C", "Series D+"],
    fitWeight: 55,
    signalWeights: {
      intent_topic: 70,
      website_visit: 90,
      hiring: 60,
      funding: 75,
      job_change: 80,
      tech_install: 45,
      social_engagement: 35,
      news: 30,
    },
    intentDecayDays: 14,
    tierThresholds: { A: 70, B: 52, C: 35 },
    updatedAt: now,
  }
}
