// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { z } from "zod"
import { db } from "../../db/index"
import { withAccounts } from "../../lib/expand"
import { createModule, csvList, idList, idParams, listQuery, paged, parseSort } from "../../lib/http"
import { activityService } from "../activities/service"
import { enrollmentService } from "../outreach/enrollment"
import { CONTACT_SORT_FIELDS, contactService } from "./service"

export const contactsModule = createModule("Contacts", "/contacts")
const { route } = contactsModule

const seniority = z.enum(["C-Level", "VP", "Director", "Manager", "IC"])
const emailStatus = z.enum(["verified", "unverified", "invalid", "missing"])
const status = z.enum(["new", "in_sequence", "replied", "meeting", "unsubscribed", "bounced"])

const contactFields = z.object({
  accountId: z.string().min(1),
  firstName: z.string().trim().min(1).max(100),
  lastName: z.string().trim().min(1).max(100),
  title: z.string().trim().max(200).optional(),
  seniority: seniority.optional(),
  department: z.string().trim().max(100).optional(),
  email: z.union([z.string().trim().email(), z.literal("")]).optional(),
  phone: z.string().trim().max(50).optional(),
  linkedinUrl: z.string().trim().max(500).optional(),
  location: z.string().trim().max(200).optional(),
  ownerId: z.string().nullable().optional(),
  status: status.optional(),
})

route({
  method: "get",
  path: "/",
  summary: "List contacts (each with its account summary)",
  description: "Filters: accountId, seniority, emailStatus, status (comma-separated), ownerId, q. Sort fields: " + CONTACT_SORT_FIELDS.join(", "),
  query: listQuery.extend({
    accountId: z.string().optional(),
    seniority: csvList.pipe(z.array(seniority).optional()),
    emailStatus: csvList.pipe(z.array(emailStatus).optional()),
    status: csvList.pipe(z.array(status).optional()),
    ownerId: z.string().optional(),
  }),
  handler: async ({ orgId, query }) => {
    const sort = parseSort(query.sort, CONTACT_SORT_FIELDS, { field: "firstName", dir: "asc" })
    const page = await contactService.list(orgId, query, query.page, query.pageSize, sort)
    return paged({ ...page, items: await withAccounts(orgId, page.items) })
  },
})

route({
  method: "post",
  path: "/",
  summary: "Create a contact",
  body: contactFields,
  handler: ({ orgId, auth, body }) => contactService.create(orgId, auth.userId, body),
})

route({
  method: "get",
  path: "/:id",
  summary: "Get a contact",
  params: idParams,
  handler: async ({ orgId, params }) => (await withAccounts(orgId, [await contactService.get(orgId, params.id)]))[0],
})

route({
  method: "patch",
  path: "/:id",
  summary: "Update a contact (email changes reset verification)",
  params: idParams,
  body: contactFields.partial(),
  handler: ({ orgId, params, body }) => contactService.update(orgId, params.id, body),
})

route({
  method: "delete",
  path: "/:id",
  summary: "Delete a contact",
  params: idParams,
  handler: async ({ orgId, params }) => {
    await contactService.get(orgId, params.id)
    await contactService.removeMany(orgId, [params.id])
  },
})

route({
  method: "post",
  path: "/bulk-delete",
  summary: "Delete many contacts",
  status: 200,
  body: idList,
  handler: async ({ orgId, body }) => ({ deleted: await contactService.removeMany(orgId, body.ids) }),
})

route({
  method: "post",
  path: "/verify-emails",
  summary: "Verify or find emails via the enrichment provider",
  status: 200,
  body: idList,
  handler: ({ orgId, body }) => contactService.verifyEmails(orgId, body.ids),
})

route({
  method: "post",
  path: "/enroll",
  summary: "Enroll contacts in a sequence",
  status: 200,
  body: z.object({ contactIds: z.array(z.string()).min(1).max(1000), sequenceId: z.string().min(1) }),
  handler: ({ orgId, body }) => enrollmentService.enroll(orgId, body.contactIds, body.sequenceId),
})

route({
  method: "get",
  path: "/:id/enrollments",
  summary: "Sequence enrollments for a contact",
  params: idParams,
  handler: async ({ orgId, params }) => {
    const enrollments = await db.enrollments.find(orgId, { contactId: params.id }, { field: "enrolledAt", dir: "desc" })
    const seqs = await db.sequences.find(orgId, { id: { in: enrollments.map((e) => e.sequenceId) } })
    return enrollments.map((e) => {
      const s = seqs.find((q) => q.id === e.sequenceId)
      return { ...e, sequence: s ? { id: s.id, name: s.name, status: s.status, stepCount: s.steps.length } : null }
    })
  },
})

route({
  method: "get",
  path: "/:id/activities",
  summary: "Activity for a contact",
  params: idParams,
  query: z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(200).default(50) }),
  handler: async ({ orgId, params, query }) =>
    paged(await activityService.list(orgId, { contactId: params.id, page: query.page, pageSize: query.pageSize })),
})
