// AUTO-GENERATED by scripts/sync-mock-core.mjs from backend/src — do not edit. Run `npm run mock:sync`.
import { db } from "../../db/index"
import type { Where } from "../../db/repository"
import { SENIORITY_ORDER } from "../../domain/constants"
import type { Contact, Stored } from "../../domain/types"
import { badRequest, notFound } from "../../lib/errors"
import { providers } from "../../providers/index"
import { activityService } from "../activities/service"

export const CONTACT_SORT_FIELDS = ["firstName", "lastName", "title", "seniority", "status", "emailStatus", "lastContactedAt", "createdAt"] as const

export interface ContactFilters {
  accountId?: string
  seniority?: Contact["seniority"][]
  emailStatus?: Contact["emailStatus"][]
  status?: Contact["status"][]
  ownerId?: string
  q?: string
}

export function contactWhere(f: ContactFilters): Where<Stored<Contact>> {
  return {
    accountId: f.accountId,
    seniority: f.seniority?.length ? { in: f.seniority } : undefined,
    emailStatus: f.emailStatus?.length ? { in: f.emailStatus } : undefined,
    status: f.status?.length ? { in: f.status } : undefined,
    ownerId: f.ownerId,
    $or: f.q
      ? [{ firstName: { contains: f.q } }, { lastName: { contains: f.q } }, { email: { contains: f.q } }, { title: { contains: f.q } }]
      : undefined,
  }
}

export type ContactCreateInput = Pick<Contact, "accountId" | "firstName" | "lastName"> & Partial<Omit<Contact, "id" | "createdAt">>

export const contactService = {
  list(orgId: string, f: ContactFilters, page: number, pageSize: number, sort: { field: (typeof CONTACT_SORT_FIELDS)[number]; dir: "asc" | "desc" }) {
    const extra = sort.field === "firstName" ? [{ field: "lastName" as const, dir: sort.dir }] : []
    return db.contacts.list(orgId, { where: contactWhere(f), sort: [sort, ...extra], page, pageSize })
  },

  async get(orgId: string, id: string) {
    const c = await db.contacts.get(orgId, id)
    if (!c) throw notFound("Contact")
    return c
  },

  async create(orgId: string, actorId: string, input: ContactCreateInput) {
    const account = await db.accounts.get(orgId, input.accountId)
    if (!account) throw badRequest("Account not found")
    const email = input.email?.trim().toLowerCase() ?? ""
    if (email) {
      const exists = await db.contacts.findOne(orgId, { email })
      if (exists) throw badRequest(`A contact with ${email} already exists`)
    }
    const created = await db.contacts.create(orgId, {
      title: "",
      seniority: "IC",
      department: "",
      linkedinUrl: "",
      location: [account.city, account.country].filter(Boolean).join(", "),
      ownerId: account.ownerId,
      ...input,
      email,
      status: input.status ?? "new",
      emailStatus: input.emailStatus ?? (email ? "unverified" : "missing"),
    })
    await activityService.log(orgId, {
      accountId: created.accountId,
      contactId: created.id,
      type: "note",
      title: `Contact ${created.firstName} ${created.lastName} added`,
      actorId,
    })
    return created
  },

  async update(orgId: string, id: string, patch: Partial<Contact>) {
    const cur = await this.get(orgId, id)
    if (patch.email !== undefined) {
      patch.email = patch.email.trim().toLowerCase()
      if (patch.email !== cur.email) patch.emailStatus = patch.emailStatus ?? (patch.email ? "unverified" : "missing")
    }
    if (patch.accountId && patch.accountId !== cur.accountId && !(await db.accounts.get(orgId, patch.accountId))) {
      throw badRequest("Account not found")
    }
    return db.contacts.update(orgId, id, patch)
  },

  async removeMany(orgId: string, ids: string[]) {
    await db.enrollments.removeMany(orgId, { contactId: { in: ids } })
    await db.drafts.removeMany(orgId, { contactId: { in: ids } })
    await db.inbox.removeMany(orgId, { contactId: { in: ids } })
    return db.contacts.removeMany(orgId, { id: { in: ids } })
  },

  async verifyEmails(orgId: string, ids: string[]) {
    const contacts = await db.contacts.find(orgId, { id: { in: ids } })
    const accounts = new Map((await db.accounts.find(orgId, { id: { in: contacts.map((c) => c.accountId) } })).map((a) => [a.id, a]))
    const counts = { verified: 0, invalid: 0, found: 0 }
    for (const c of contacts) {
      const wasMissing = c.emailStatus === "missing" || !c.email
      const res = await providers.enrichment.findEmail(c, accounts.get(c.accountId)?.domain ?? "example.com")
      await db.contacts.update(orgId, c.id, { email: res.email ?? c.email, emailStatus: res.status })
      if (res.status === "verified") counts.verified++
      if (res.status === "invalid") counts.invalid++
      if (wasMissing && res.email) counts.found++
    }
    return { processed: contacts.length, ...counts }
  },

  /** Most senior reachable contact on an account (used by the agent). */
  async bestContact(orgId: string, accountId: string) {
    const contacts = await db.contacts.find(orgId, { accountId, status: { nin: ["unsubscribed", "bounced"] } })
    return (
      contacts.sort((a, b) => SENIORITY_ORDER.indexOf(a.seniority) - SENIORITY_ORDER.indexOf(b.seniority))[0] ?? null
    )
  },
}
